'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api} from '../../lib/api';

const money=n=>Number(n||0).toLocaleString('ko-KR')+' P';
const level=s=>`Lv.${Number(s?.level||1)}`;

export default function MarketPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[categories,setCategories]=useState([]),[products,setProducts]=useState([]),[activeCategory,setActiveCategory]=useState(''),[seller,setSeller]=useState(null),[sellers,setSellers]=useState([]),[trades,setTrades]=useState([]),[wallet,setWallet]=useState(null);
 const [sellerName,setSellerName]=useState(''),[sellerIntro,setSellerIntro]=useState('');
 const [product,setProduct]=useState({category_id:'',title:'',description:'',price:'',stock:''});
 const [direct,setDirect]=useState({seller_id:'',amount:'',title:'직접 협의 거래',description:'',category_id:''});
 const [selectedTrade,setSelectedTrade]=useState(null),[messages,setMessages]=useState([]),[chatText,setChatText]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 async function load(category=''){try{const [c,p,s,t,w,me]=await Promise.all([api.marketCategories(),api.marketProducts(category),api.marketSellers(),api.marketTrades(),api.wallet(),api.sellerMe()]);setCategories(c.items||[]);setProducts(p.items||[]);setSellers(s.items||[]);setTrades(t.items||[]);setWallet(w.wallet||null);setSeller(me.item||null)}catch(e){alert(e.message)}}
 useEffect(()=>{if(session)load('')},[session]);
 async function chooseCategory(id){setActiveCategory(String(id||''));try{const p=await api.marketProducts(id||'');setProducts(p.items||[])}catch(e){alert(e.message)}}
 if(!ready)return <div className="authPage"><div className="authCard">자유시장을 불러오는 중...</div></div>;
 if(!session)return <div className="authPage"><div className="authCard"><h1>HUB24 <span>MARKET</span></h1><p>먼저 로그인하세요.</p><a className="btn primary" href="/">로그인 화면</a></div></div>;
 const myId=session.user.id;
 async function applySeller(){if(!sellerName.trim())return alert('판매자명을 입력하세요.');try{await api.sellerApply({seller_name:sellerName.trim(),introduction:sellerIntro||null});await load(activeCategory);alert('판매자 등록 신청이 접수되었습니다.')}catch(e){alert(e.message)}}
 async function addProduct(){if(!product.title.trim()||Number(product.price)<0)return alert('상품명과 가격을 확인하세요.');try{await api.createProduct({category_id:product.category_id?Number(product.category_id):null,title:product.title,description:product.description||null,price:Number(product.price),stock:product.stock===''?null:Number(product.stock)});setProduct({category_id:'',title:'',description:'',price:'',stock:''});await load(activeCategory);alert('판매상품을 등록했습니다.')}catch(e){alert(e.message)}}
 async function buy(p){const qty=Number(prompt('구매 수량을 입력하세요.','1')||0);if(qty<=0)return;if(!confirm(`${p.title}\n${money(Number(p.price)*qty)}를 에스크로로 결제할까요?`))return;try{const r=await api.buyProduct(p.id,qty);await load(activeCategory);alert(`에스크로 거래가 생성되었습니다. 거래 #${r.trade_id}`)}catch(e){alert(e.message)}}
 async function createDirect(){if(!direct.seller_id||Number(direct.amount)<=0)return alert('판매자와 에스크로 금액을 확인하세요.');if(!confirm(`${money(direct.amount)}를 에스크로에 보관하고 거래요청을 보낼까요?`))return;try{const r=await api.directEscrow({seller_id:direct.seller_id,amount:Number(direct.amount),title:direct.title||'직접 협의 거래',description:direct.description||null,category_id:direct.category_id?Number(direct.category_id):null});setDirect({seller_id:'',amount:'',title:'직접 협의 거래',description:'',category_id:''});await load(activeCategory);alert(`직접 에스크로 거래 #${r.trade_id}가 생성되었습니다.`)}catch(e){alert(e.message)}}
 async function openTrade(t){setSelectedTrade(t);try{const r=await api.tradeMessages(t.id);setMessages(r.items||[])}catch(e){alert(e.message)}}
 async function sendChat(){if(!selectedTrade||!chatText.trim())return;try{await api.sendTradeMessage(selectedTrade.id,chatText.trim());setChatText('');await openTrade(selectedTrade)}catch(e){alert(e.message)}}
 async function action(fn,id,msg){if(msg&&!confirm(msg))return;try{await api[fn](id);await load(activeCategory);if(selectedTrade?.id===id){const t=(await api.marketTrades()).items.find(x=>x.id===id);if(t)await openTrade(t)} }catch(e){alert(e.message)}}
 const approved=seller?.status==='APPROVED';
 return <main className="content" style={{maxWidth:1500,margin:'0 auto'}}>
   <div className="head"><div><h1>자유시장</h1><p>판매상품 · 직접 협의 거래 · HUB24 에스크로</p></div><div className="actions compact"><span className="badge ok">사용 가능 {money(wallet?.available_balance)}</span><button className="btn" onClick={()=>load(activeCategory)}>새로고침</button></div></div>

   <section className="card"><div className="head"><div><h2>판매상품</h2><p>자유시장을 열면 항상 전체 상품이 먼저 표시됩니다.</p></div></div><div className="filters" style={{marginBottom:14}}><button className={!activeCategory?'active':''} onClick={()=>chooseCategory('')}>전체보기</button>{categories.map(c=><button className={String(activeCategory)===String(c.id)?'active':''} key={c.id} onClick={()=>chooseCategory(c.id)}>{c.name}</button>)}</div>
    <div className="marketProducts">{products.length?products.map(p=><div className="marketProduct" key={p.id}><div><small>{p.category?.name||'기타'}</small><h3>{p.title}</h3><p>{p.description||'상품 설명이 없습니다.'}</p></div><div className="sellerMeta"><b>{p.seller?.seller_name||'판매자'}</b><span>{level(p.seller)} · 완료 {Number(p.seller?.completed_sales||0).toLocaleString()}건 · 분쟁 {Number(p.seller?.dispute_count||0)}건</span></div><div className="productBottom"><div><strong>{money(p.price)}</strong><small>재고 {p.stock==null?'제한 없음':p.stock}</small></div><button className="btn primary" onClick={()=>buy(p)}>에스크로 구매</button></div></div>):<div className="empty">해당 카테고리에 판매상품이 없습니다.</div>}</div>
   </section>

   <div className="two" style={{marginTop:14}}>
    <section className="card"><h2>직접 에스크로 요청</h2><p style={{color:'#8292a8',fontSize:11}}>상품 등록 없이 판매자와 실시간으로 협의한 거래도 금액을 직접 지정해 에스크로를 걸 수 있습니다.</p><div className="form"><label className="field full"><span>상대 판매자</span><select className="input" value={direct.seller_id} onChange={e=>setDirect({...direct,seller_id:e.target.value})}><option value="">판매자 선택</option>{sellers.filter(s=>String(s.user_id)!==String(myId)).map(s=><option value={s.user_id} key={s.user_id}>{s.seller_name} · {level(s)} · 완료 {s.completed_sales||0}건</option>)}</select></label><label className="field"><span>에스크로 금액</span><input className="input" type="number" value={direct.amount} onChange={e=>setDirect({...direct,amount:e.target.value})} placeholder="10000"/></label><label className="field"><span>카테고리</span><select className="input" value={direct.category_id} onChange={e=>setDirect({...direct,category_id:e.target.value})}><option value="">선택 안 함</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field full"><span>거래 제목</span><input className="input" value={direct.title} onChange={e=>setDirect({...direct,title:e.target.value})}/></label><label className="field full"><span>협의 내용</span><textarea className="textarea" value={direct.description} onChange={e=>setDirect({...direct,description:e.target.value})}/></label></div><div className="actions"><button className="btn primary" onClick={createDirect}>이 금액으로 에스크로 요청</button></div><div className="note">요청 즉시 구매자의 사용 가능 포인트가 차감되고 같은 금액이 에스크로에 보관됩니다. 판매자가 완료 요청 후 구매자가 확인해야 지급됩니다.</div></section>
    <section className="card"><h2>판매자센터</h2>{!seller?<><p style={{color:'#8292a8',fontSize:11}}>정식 판매자로 등록하면 자유시장 상품 등록과 판매대금 정산 기능을 사용할 수 있습니다.</p><label className="field"><span>판매자명</span><input className="input" value={sellerName} onChange={e=>setSellerName(e.target.value)}/></label><label className="field" style={{marginTop:10}}><span>판매자 소개</span><textarea className="textarea" value={sellerIntro} onChange={e=>setSellerIntro(e.target.value)}/></label><div className="actions"><button className="btn primary" onClick={applySeller}>판매자 등록 신청</button></div></>:!approved?<div><b>판매자 상태: {seller.status}</b><div className="note">관리자 승인 후 상품을 등록할 수 있습니다. 직접 에스크로 구매 기능은 일반 회원도 사용할 수 있습니다.</div></div>:<><div className="jobstats"><b>{seller.seller_name}</b><span className="badge ok">{level(seller)}</span><span>완료 {seller.completed_sales||0}건</span><span>누적 {money(seller.total_sales_amount)}</span></div><div className="form"><label className="field"><span>카테고리</span><select className="input" value={product.category_id} onChange={e=>setProduct({...product,category_id:e.target.value})}><option value="">기타</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field"><span>가격</span><input className="input" type="number" value={product.price} onChange={e=>setProduct({...product,price:e.target.value})}/></label><label className="field full"><span>상품명</span><input className="input" value={product.title} onChange={e=>setProduct({...product,title:e.target.value})}/></label><label className="field"><span>재고 (빈 값=제한 없음)</span><input className="input" type="number" value={product.stock} onChange={e=>setProduct({...product,stock:e.target.value})}/></label><label className="field full"><span>상품 설명</span><textarea className="textarea" value={product.description} onChange={e=>setProduct({...product,description:e.target.value})}/></label></div><div className="actions"><button className="btn primary" onClick={addProduct}>판매상품 등록</button></div></>}</section>
   </div>

   <section className="card" style={{marginTop:14}}><h2>내 거래</h2><div className="tradeGrid"><div className="tradeList">{trades.length?trades.map(t=><button key={t.id} className={selectedTrade?.id===t.id?'active':''} onClick={()=>openTrade(t)}><b>#{t.id} · {t.title_snapshot}</b><span>{t.trade_type==='DIRECT'?'직접협의':'상품'} · {money(t.amount)} · {t.status}</span></button>):<div className="empty">거래가 없습니다.</div>}</div><div className="tradeDetail">{selectedTrade?<><div className="head"><div><h2>거래 #{selectedTrade.id}</h2><p>{selectedTrade.title_snapshot} · {money(selectedTrade.amount)}</p></div><span className="badge wait">{selectedTrade.status}</span></div><div className="tradeActions">{String(selectedTrade.seller_id)===String(myId)&&['ESCROWED','ACCEPTED'].includes(selectedTrade.status)&&<button className="btn primary" onClick={()=>action('sellerComplete',selectedTrade.id,'판매완료를 요청할까요?')}>판매완료 요청</button>}{String(selectedTrade.buyer_id)===String(myId)&&['ESCROWED','ACCEPTED','SELLER_COMPLETED'].includes(selectedTrade.status)&&<button className="btn primary" onClick={()=>action('buyerComplete',selectedTrade.id,`${money(selectedTrade.amount)}를 판매자에게 지급할까요?`)}>거래완료 · 지급</button>}{!['COMPLETED','CANCELLED','ADMIN_RESOLVED'].includes(selectedTrade.status)&&<><button className="btn" onClick={()=>action('cancelTrade',selectedTrade.id,'거래 취소를 요청할까요?')}>취소 요청</button><button className="btn danger" onClick={()=>action('disputeTrade',selectedTrade.id,'분쟁을 접수할까요? 에스크로가 동결됩니다.')}>문제 신고</button></>}</div><div className="tradeChat">{messages.length?messages.map(m=><div className={'tradeMsg '+(m.sender_type==='SYSTEM'?'system':'')} key={m.id}><small>{m.sender_type} · {m.created_at?.replace('T',' ').slice(0,19)}</small><p>{m.message}</p></div>):<div className="empty">대화가 없습니다.</div>}</div><div className="actions"><input className="input" value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="거래 메시지 입력" onKeyDown={e=>e.key==='Enter'&&sendChat()}/><button className="btn primary" onClick={sendChat}>전송</button></div></>:<div className="empty">왼쪽에서 거래를 선택하세요.</div>}</div></div></section>
 </main>
}
