'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {supabase} from '../../lib/supabase';
import {api} from '../../lib/api';

const money=n=>Number(n||0).toLocaleString('ko-KR')+' P';
const level=s=>`Lv.${Number(s?.level||1)}`;

export default function MarketPage(){
 const params=useSearchParams();
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[categories,setCategories]=useState([]),[products,setProducts]=useState([]),[sellers,setSellers]=useState([]),[trades,setTrades]=useState([]),[activeCategory,setActiveCategory]=useState(''),[view,setView]=useState('products');
 const [query,setQuery]=useState(''),[sort,setSort]=useState('latest');
 const [directOpen,setDirectOpen]=useState(false),[direct,setDirect]=useState({seller_id:'',seller_name:'',amount:'',title:'직접 협의 거래',description:'',category_id:''});
 const [selectedTrade,setSelectedTrade]=useState(null),[messages,setMessages]=useState([]),[chatText,setChatText]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 useEffect(()=>{const q=params.get('view');if(q==='trades'||q==='sellers')setView(q);else setView('products')},[params]);
 async function load(category=''){try{const [c,p,s,t]=await Promise.all([api.marketCategories(),api.marketProducts(category),api.marketSellers(),api.marketTrades()]);setCategories(c.items||[]);setProducts(p.items||[]);setSellers(s.items||[]);setTrades(t.items||[])}catch(e){alert(e.message)}}
 useEffect(()=>{if(session)load('')},[session]);
 async function chooseCategory(id){setActiveCategory(String(id||''));try{const p=await api.marketProducts(id||'');setProducts(p.items||[])}catch(e){alert(e.message)}}
 if(!ready)return <div className="authPage"><div className="authCard">자유시장을 불러오는 중...</div></div>;
 if(!session)return <div className="authPage"><div className="authCard"><h1>HUB24 <span>MARKET</span></h1><p>먼저 로그인하세요.</p><a className="btn primary" href="/">로그인 화면</a></div></div>;
 const myId=session.user.id;
 const shownProducts=useMemo(()=>{
   let list=products.filter(p=>!query.trim()||String(p.title||'').toLowerCase().includes(query.trim().toLowerCase())||String(p.description||'').toLowerCase().includes(query.trim().toLowerCase())||String(p.seller?.seller_name||'').toLowerCase().includes(query.trim().toLowerCase()));
   if(sort==='low')list=[...list].sort((a,b)=>Number(a.price)-Number(b.price));
   if(sort==='high')list=[...list].sort((a,b)=>Number(b.price)-Number(a.price));
   if(sort==='sales')list=[...list].sort((a,b)=>Number(b.seller?.completed_sales||0)-Number(a.seller?.completed_sales||0));
   return list;
 },[products,query,sort]);
 async function buy(p){const qty=Number(prompt('구매 수량을 입력하세요.','1')||0);if(qty<=0)return;if(!confirm(`${p.title}\n${money(Number(p.price)*qty)}를 에스크로로 결제할까요?`))return;try{const r=await api.buyProduct(p.id,qty);await load(activeCategory);alert(`에스크로 거래 #${r.trade_id}가 생성되었습니다.`);setView('trades')}catch(e){alert(e.message)}}
 function openDirect(s){setDirect({seller_id:String(s.user_id),seller_name:s.seller_name,amount:'',title:`${s.seller_name} 직접 협의 거래`,description:'',category_id:''});setDirectOpen(true)}
 async function createDirect(){if(!direct.seller_id||Number(direct.amount)<=0)return alert('에스크로 금액을 확인하세요.');if(!confirm(`${money(direct.amount)}를 에스크로에 보관하고 거래요청을 보낼까요?`))return;try{const r=await api.directEscrow({seller_id:direct.seller_id,amount:Number(direct.amount),title:direct.title||'직접 협의 거래',description:direct.description||null,category_id:direct.category_id?Number(direct.category_id):null});setDirectOpen(false);await load(activeCategory);alert(`직접 에스크로 거래 #${r.trade_id}가 생성되었습니다.`);setView('trades')}catch(e){alert(e.message)}}
 async function openTrade(t){setSelectedTrade(t);try{const r=await api.tradeMessages(t.id);setMessages(r.items||[])}catch(e){alert(e.message)}}
 async function sendChat(){if(!selectedTrade||!chatText.trim())return;try{await api.sendTradeMessage(selectedTrade.id,chatText.trim());setChatText('');await openTrade(selectedTrade)}catch(e){alert(e.message)}}
 async function act(fn,id,msg){if(msg&&!confirm(msg))return;try{await api[fn](id);await load(activeCategory);const fresh=(await api.marketTrades()).items.find(x=>x.id===id);if(fresh)await openTrade(fresh)}catch(e){alert(e.message)}}
 return <main className="marketPage">
   <section className="marketHero">
    <div><span className="eyebrow">HUB24 MARKET</span><h1>자유시장</h1><p>검증된 판매자와 에스크로로 안전하게 거래하세요.</p></div>
    <div className="marketHeroActions"><a className="softButton" href="/seller">판매자센터</a><button className="softButton" onClick={()=>setView('trades')}>내 거래</button></div>
   </section>
   <div className="marketViewTabs"><button className={view==='products'?'active':''} onClick={()=>setView('products')}>상품 보기</button><button className={view==='sellers'?'active':''} onClick={()=>setView('sellers')}>직접 거래 판매자</button><button className={view==='trades'?'active':''} onClick={()=>setView('trades')}>내 거래</button></div>
   {view==='products'&&<><section className="shopToolbar"><div className="marketSearch"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="상품명 또는 판매자 검색"/></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="latest">최신순</option><option value="low">낮은 가격순</option><option value="high">높은 가격순</option><option value="sales">판매 많은 순</option></select></section><div className="categoryRail"><button className={!activeCategory?'active':''} onClick={()=>chooseCategory('')}>전체보기</button>{categories.map(c=><button className={String(activeCategory)===String(c.id)?'active':''} key={c.id} onClick={()=>chooseCategory(c.id)}>{c.name}</button>)}</div><section className="productGrid">{shownProducts.length?shownProducts.map(p=><article className="shopCard" key={p.id}><div className="shopCardTop"><span>{p.category?.name||'기타'}</span><small>{p.stock==null?'재고 제한 없음':`재고 ${p.stock}`}</small></div><div className="productVisual"><span>{String(p.title||'H').slice(0,1).toUpperCase()}</span></div><div className="shopCardBody"><h3>{p.title}</h3><p>{p.description||'상품 설명이 없습니다.'}</p><div className="sellerStrip"><div className="sellerAvatar">{String(p.seller?.seller_name||'S').slice(0,1)}</div><div><b>{p.seller?.seller_name||'판매자'}</b><span>{level(p.seller)} · 완료 {Number(p.seller?.completed_sales||0).toLocaleString()}건</span></div></div><div className="shopPrice"><strong>{money(p.price)}</strong><button onClick={()=>buy(p)}>구매하기</button></div></div></article>):<div className="marketEmpty">조건에 맞는 상품이 없습니다.</div>}</section></>}
   {view==='sellers'&&<section className="sellerBrowse"><div className="sectionTitle"><h2>직접 거래 가능 판매자</h2><p>상품 등록 없이 실시간 협의가 필요한 거래는 판매자에게 금액을 직접 지정해 에스크로 요청할 수 있습니다.</p></div><div className="sellerGrid">{sellers.filter(s=>String(s.user_id)!==String(myId)).length?sellers.filter(s=>String(s.user_id)!==String(myId)).map(s=><article className="sellerCard" key={s.user_id}><div className="sellerCardHead"><div className="sellerBigAvatar">{String(s.seller_name||'S').slice(0,1)}</div><div><h3>{s.seller_name}</h3><span>{level(s)} · 정식 판매자</span></div></div><p>{s.introduction||'판매자 소개가 없습니다.'}</p><div className="sellerStats"><div><b>{Number(s.completed_sales||0).toLocaleString()}</b><span>완료 거래</span></div><div><b>{s.dispute_count||0}</b><span>분쟁</span></div><div><b>{money(s.total_sales_amount)}</b><span>누적 거래</span></div></div><button className="sellerAction" onClick={()=>openDirect(s)}>직접 에스크로 요청</button></article>):<div className="marketEmpty">등록된 판매자가 없습니다.</div>}</div></section>}
   {view==='trades'&&<section className="tradeWorkspace"><div className="sectionTitle"><h2>내 거래</h2><p>구매 및 직접 협의 거래의 진행상태와 대화를 확인합니다.</p></div><div className="tradeGrid"><div className="tradeList">{trades.length?trades.map(t=><button key={t.id} className={selectedTrade?.id===t.id?'active':''} onClick={()=>openTrade(t)}><b>#{t.id} · {t.title_snapshot}</b><span>{t.trade_type==='DIRECT'?'직접협의':'상품'} · {money(t.amount)} · {t.status}</span></button>):<div className="empty">거래가 없습니다.</div>}</div><div className="tradeDetail">{selectedTrade?<><div className="head"><div><h2>거래 #{selectedTrade.id}</h2><p>{selectedTrade.title_snapshot} · {money(selectedTrade.amount)}</p></div><span className="badge wait">{selectedTrade.status}</span></div><div className="tradeActions">{String(selectedTrade.seller_id)===String(myId)&&['ESCROWED','ACCEPTED'].includes(selectedTrade.status)&&<button className="btn primary" onClick={()=>act('sellerComplete',selectedTrade.id,'판매완료를 요청할까요?')}>판매완료 요청</button>}{String(selectedTrade.buyer_id)===String(myId)&&['ESCROWED','ACCEPTED','SELLER_COMPLETED'].includes(selectedTrade.status)&&<button className="btn primary" onClick={()=>act('buyerComplete',selectedTrade.id,`${money(selectedTrade.amount)}를 판매자에게 지급할까요?`)}>거래완료 · 지급</button>}{!['COMPLETED','CANCELLED','ADMIN_RESOLVED'].includes(selectedTrade.status)&&<><button className="btn" onClick={()=>act('cancelTrade',selectedTrade.id,'거래 취소를 요청할까요?')}>취소 요청</button><button className="btn danger" onClick={()=>act('disputeTrade',selectedTrade.id,'분쟁을 접수할까요?')}>문제 신고</button></>}</div><div className="tradeChat">{messages.length?messages.map(m=><div className={'tradeMsg '+(m.sender_type==='SYSTEM'?'system':'')} key={m.id}><small>{m.sender_type} · {m.created_at?.replace('T',' ').slice(0,19)}</small><p>{m.message}</p></div>):<div className="empty">대화가 없습니다.</div>}</div><div className="tradeComposer"><input value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="거래 메시지 입력" onKeyDown={e=>e.key==='Enter'&&sendChat()}/><button onClick={sendChat}>전송</button></div></>:<div className="marketEmpty">왼쪽에서 거래를 선택하세요.</div>}</div></div></section>}
   {directOpen&&<div className="modalBack"><div className="modal directModal"><div className="head"><div><h2>직접 에스크로 요청</h2><p>{direct.seller_name} 판매자와 협의한 금액을 안전하게 보관합니다.</p></div><button className="x" onClick={()=>setDirectOpen(false)}>×</button></div><div className="form"><label className="field"><span>에스크로 금액</span><input className="input" type="number" value={direct.amount} onChange={e=>setDirect({...direct,amount:e.target.value})} placeholder="10000"/></label><label className="field"><span>카테고리</span><select className="input" value={direct.category_id} onChange={e=>setDirect({...direct,category_id:e.target.value})}><option value="">선택 안 함</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field full"><span>거래 제목</span><input className="input" value={direct.title} onChange={e=>setDirect({...direct,title:e.target.value})}/></label><label className="field full"><span>협의 내용</span><textarea className="textarea" value={direct.description} onChange={e=>setDirect({...direct,description:e.target.value})}/></label></div><div className="escrowNotice">요청 즉시 해당 금액이 사용 가능 포인트에서 차감되어 에스크로에 보관됩니다. 거래 완료 전까지 판매자에게 지급되지 않습니다.</div><div className="actions"><button className="btn" onClick={()=>setDirectOpen(false)}>취소</button><button className="btn primary" onClick={createDirect}>에스크로 요청</button></div></div></div>}
 </main>
}
