'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api} from '../../lib/api';
import {noticeApi} from '../../lib/notice-api';
import PaidBannerGrid from '../paid-banner-grid';

const money=n=>Number(n||0).toLocaleString('ko-KR')+' P';
const level=s=>`Lv.${Number(s?.level||1)}`;
const isVip=s=>!!(s?.vip_until&&new Date(s.vip_until).getTime()>Date.now());
const date=v=>v?String(v).replace('T',' ').slice(0,16):'-';

export default function MarketPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[categories,setCategories]=useState([]),[products,setProducts]=useState([]),[trades,setTrades]=useState([]),[notices,setNotices]=useState([]),[selectedNotice,setSelectedNotice]=useState(null);
 const [activeCategory,setActiveCategory]=useState(''),[view,setView]=useState('products'),[query,setQuery]=useState(''),[sort,setSort]=useState('latest');
 const [directOpen,setDirectOpen]=useState(false),[direct,setDirect]=useState({seller_id:'',seller_name:'',amount:'',title:'직접 협의 거래',description:'',category_id:''});
 const [selectedTrade,setSelectedTrade]=useState(null),[messages,setMessages]=useState([]),[chatText,setChatText]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)});if(typeof window!=='undefined'){const q=new URLSearchParams(window.location.search).get('view');if(q==='trades'||q==='vip')setView(q)}},[]);
 async function load(category=''){try{const [c,p,t,n]=await Promise.all([api.marketCategories(),api.marketProducts(category),api.marketTrades(),noticeApi.list()]);setCategories(c.items||[]);setProducts(p.items||[]);setTrades(t.items||[]);setNotices(n.items||[])}catch(e){alert(e.message)}}
 useEffect(()=>{if(session)load('')},[session]);
 async function chooseCategory(id){setActiveCategory(String(id||''));try{const p=await api.marketProducts(id||'');setProducts(p.items||[])}catch(e){alert(e.message)}}
 if(!ready)return <div className="authPage"><div className="authCard">자유시장을 불러오는 중...</div></div>;
 if(!session)return <div className="authPage"><div className="authCard"><h1>ANGEL PAY <span>N PAY</span></h1><p>먼저 로그인하세요.</p><a className="btn primary" href="/">로그인 화면</a></div></div>;
 const myId=session.user.id;
 function sorted(list){let out=list.filter(p=>{const q=query.trim().toLowerCase();if(!q)return true;return String(p.title||'').toLowerCase().includes(q)||String(p.description||'').toLowerCase().includes(q)||String(p.seller?.seller_name||'').toLowerCase().includes(q)});if(sort==='low')out=[...out].sort((a,b)=>Number(a.price)-Number(b.price));if(sort==='high')out=[...out].sort((a,b)=>Number(b.price)-Number(a.price));if(sort==='sales')out=[...out].sort((a,b)=>Number(b.seller?.completed_sales||0)-Number(a.seller?.completed_sales||0));if(sort==='latest')out=[...out].sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')));return out}
 const shownProducts=sorted(products);
 const vipProducts=sorted(products.filter(p=>isVip(p.seller)));
 async function buy(p){const qty=Number(prompt('구매 수량을 입력하세요.','1')||0);if(qty<=0)return;if(!confirm(`${p.title}\n${money(Number(p.price)*qty)}를 에스크로로 결제할까요?`))return;try{const r=await api.buyProduct(p.id,qty);await load(activeCategory);alert(`에스크로 거래 #${r.trade_id}가 생성되었습니다.`);setView('trades')}catch(e){alert(e.message)}}
 function openDirect(p){const s=p.seller||{};setDirect({seller_id:String(p.seller_id),seller_name:s.seller_name||'판매자',amount:'',title:`${p.title} · 직접 협의 거래`,description:`상품: ${p.title}`,category_id:p.category_id?String(p.category_id):''});setDirectOpen(true)}
 async function createDirect(){if(!direct.seller_id||Number(direct.amount)<=0)return alert('에스크로 금액을 확인하세요.');if(!confirm(`${money(direct.amount)}를 에스크로에 보관하고 거래요청을 보낼까요?`))return;try{const r=await api.directEscrow({seller_id:direct.seller_id,amount:Number(direct.amount),title:direct.title||'직접 협의 거래',description:direct.description||null,category_id:direct.category_id?Number(direct.category_id):null});setDirectOpen(false);await load(activeCategory);alert(`직접 에스크로 거래 #${r.trade_id}가 생성되었습니다.`);setView('trades')}catch(e){alert(e.message)}}
 async function openTrade(t){setSelectedTrade(t);try{const r=await api.tradeMessages(t.id);setMessages(r.items||[])}catch(e){alert(e.message)}}
 async function sendChat(){if(!selectedTrade||!chatText.trim())return;try{await api.sendTradeMessage(selectedTrade.id,chatText.trim());setChatText('');await openTrade(selectedTrade)}catch(e){alert(e.message)}}
 async function tradeAction(fn,id,msg){if(msg&&!confirm(msg))return;try{await api[fn](id);await load(activeCategory);const fresh=(await api.marketTrades()).items.find(x=>x.id===id);if(fresh)await openTrade(fresh)}catch(e){alert(e.message)}}
 function ProductCard({p}){return <article className={'shopCard '+(isVip(p.seller)?'vipCard':'')}><div className="shopImageWrap">{p.image_url?<img src={p.image_url} alt={p.title}/>:<div className="imageMissing">IMAGE</div>}{isVip(p.seller)&&<span className="vipRibbon">VIP</span>}<span className="shopCategory">{p.category?.name||'기타'}</span></div><div className="shopCardBody"><h3>{p.title}</h3><p>{p.description||'상품 설명이 없습니다.'}</p><div className="sellerStrip"><div className="sellerAvatar">{String(p.seller?.seller_name||'S').slice(0,1)}</div><div><b>{p.seller?.seller_name||'판매자'} {isVip(p.seller)&&<em>VIP</em>}</b><span>{level(p.seller)} · 완료 {Number(p.seller?.completed_sales||0).toLocaleString()}건 · 최저가 {Number(p.seller?.minimum_price||0)>0?money(p.seller.minimum_price):'미등록'}</span>{p.seller?.telegram_username&&<span className="sellerTelegramLine">Telegram {p.seller.telegram_username}</span>}</div></div><div className="shopPrice"><div><strong>{money(p.price)}</strong><small>{p.stock==null?'재고 제한 없음':`재고 ${p.stock}`}</small></div><button onClick={()=>buy(p)}>구매</button></div><a className="productChatButton" href={`/messages?seller=${encodeURIComponent(p.seller_id)}&product=${p.id}`}>1:1 대화 요청</a><button className="directFromProduct" onClick={()=>openDirect(p)}>판매자에게 직접 에스크로 요청</button></div></article>}
 function NoticePost({n}){return <button type="button" onClick={()=>setSelectedNotice(n)} style={{gridColumn:'1 / -1',width:'100%',border:'1px solid #315b86',borderRadius:10,background:'#0d1d31',padding:'12px 14px',display:'flex',gap:12,alignItems:'center',textAlign:'left',cursor:'pointer',color:'#fff'}}><span style={{flex:'0 0 auto',padding:'4px 8px',borderRadius:7,background:'#2d7fd3',color:'#fff',fontSize:10,fontWeight:950}}>공지</span><b style={{fontSize:13,color:'#f2f7ff',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',flex:1}}>{n.title}</b><small style={{color:'#7290ad',whiteSpace:'nowrap'}}>{date(n.created_at)}</small></button>}
 return <main className="marketPage">
  <section className="marketHero"><div><span className="eyebrow">ANGEL PAY · N PAY MARKET</span><h1>자유시장</h1><p>엔페이 에스크로를 통해 판매상품을 비교하고 안전하게 거래하세요.</p></div><div className="marketHeroActions"><a className="softButton" href="/messages">1:1 대화</a><a className="softButton" href="/seller">판매자센터</a><button className="softButton" onClick={()=>setView('trades')}>내 거래</button></div></section>
  <div className="marketViewTabs"><button className={view==='products'?'active':''} onClick={()=>setView('products')}>전체 상품</button><button className={view==='vip'?'active':''} onClick={()=>setView('vip')}>VIP 판매자</button><button className={view==='trades'?'active':''} onClick={()=>setView('trades')}>내 거래</button></div>
  <PaidBannerGrid/>
  {(view==='products'||view==='vip')&&<><section className="shopToolbar"><div className="marketSearch"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="상품명 또는 판매자 검색"/></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="latest">최신순</option><option value="low">가격 낮은순</option><option value="high">가격 높은순</option><option value="sales">판매 많은순</option></select></section><div className="categoryRail"><button className={!activeCategory?'active':''} onClick={()=>chooseCategory('')}>전체보기</button>{categories.map(c=><button className={String(activeCategory)===String(c.id)?'active':''} key={c.id} onClick={()=>chooseCategory(c.id)}>{c.name}</button>)}</div></>}
  {view==='products'&&<section className="productGrid">{notices.map(n=><NoticePost n={n} key={'notice-'+n.id}/>)}{shownProducts.length?shownProducts.map(p=><ProductCard p={p} key={p.id}/>):!notices.length&&<div className="marketEmpty">조건에 맞는 상품이 없습니다.</div>}</section>}
  {view==='vip'&&<section><div className="vipBoardIntro"><div><span className="vipTag">VIP SELLER</span><h2>VIP 판매자 상품</h2><p>VIP 등록 기간이 유효한 판매자의 상품만 모아봅니다. VIP 상품은 전체 상품에도 함께 노출됩니다.</p></div><a href="/seller">VIP 판매자 등록</a></div><div className="productGrid">{notices.map(n=><NoticePost n={n} key={'vip-notice-'+n.id}/>)}{vipProducts.length?vipProducts.map(p=><ProductCard p={p} key={p.id}/>):!notices.length&&<div className="marketEmpty">현재 등록된 VIP 판매자 상품이 없습니다.</div>}</div></section>}
  {view==='trades'&&<section className="tradeWorkspace"><div className="sectionTitle"><h2>내 거래</h2><p>상품 구매와 직접 협의 거래의 진행상태를 확인합니다.</p></div><div className="tradeGrid"><div className="tradeList">{trades.length?trades.map(t=><button key={t.id} className={selectedTrade?.id===t.id?'active':''} onClick={()=>openTrade(t)}><b>#{t.id} · {t.title_snapshot}</b><span>{t.trade_type==='DIRECT'?'직접협의':'상품'} · {money(t.amount)} · {t.status}</span></button>):<div className="empty">거래가 없습니다.</div>}</div><div className="tradeDetail">{selectedTrade?<><div className="head"><div><h2>거래 #{selectedTrade.id}</h2><p>{selectedTrade.title_snapshot} · {money(selectedTrade.amount)}</p></div><span className="badge wait">{selectedTrade.status}</span></div><div className="tradeActions">{String(selectedTrade.seller_id)===String(myId)&&['ESCROWED','ACCEPTED'].includes(selectedTrade.status)&&<button className="btn primary" onClick={()=>tradeAction('sellerComplete',selectedTrade.id,'판매완료를 요청할까요?')}>판매완료 요청</button>}{String(selectedTrade.buyer_id)===String(myId)&&['ESCROWED','ACCEPTED','SELLER_COMPLETED'].includes(selectedTrade.status)&&<button className="btn primary" onClick={()=>tradeAction('buyerComplete',selectedTrade.id,`${money(selectedTrade.amount)}를 판매자에게 지급할까요?`)}>거래완료 · 지급</button>}{!['COMPLETED','CANCELLED','ADMIN_RESOLVED'].includes(selectedTrade.status)&&<><button className="btn" onClick={()=>tradeAction('cancelTrade',selectedTrade.id,'거래 취소를 요청할까요?')}>취소 요청</button><button className="btn danger" onClick={()=>tradeAction('disputeTrade',selectedTrade.id,'분쟁을 접수할까요?')}>문제 신고</button></>}</div><div className="tradeChat">{messages.length?messages.map(m=><div className={'tradeMsg '+(m.sender_type==='SYSTEM'?'system':'')} key={m.id}><small>{m.sender_type} · {m.created_at?.replace('T',' ').slice(0,19)}</small><p>{m.message}</p></div>):<div className="empty">대화가 없습니다.</div>}</div><div className="tradeComposer"><input value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="거래 메시지 입력" onKeyDown={e=>e.key==='Enter'&&sendChat()}/><button onClick={sendChat}>전송</button></div></>:<div className="marketEmpty">왼쪽에서 거래를 선택하세요.</div>}</div></div></section>}
  {selectedNotice&&<div className="modalBack" onClick={()=>setSelectedNotice(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="head"><div><h2><span className="pinBadge" style={{marginRight:8}}>공지</span>{selectedNotice.title}</h2><p>ANGEL PAY 운영팀 · {date(selectedNotice.created_at)}</p></div><button className="x" onClick={()=>setSelectedNotice(null)}>×</button></div><div className="postBody" style={{whiteSpace:'pre-wrap',marginTop:14}}>{selectedNotice.content}</div><div className="actions" style={{marginTop:18}}><button className="btn primary" onClick={()=>setSelectedNotice(null)}>확인</button></div></div></div>}
  {directOpen&&<div className="modalBack"><div className="modal directModal"><div className="head"><div><h2>판매자에게 직접 에스크로 요청</h2><p>{direct.seller_name} 판매자에게 협의 금액을 직접 제안합니다.</p></div><button className="x" onClick={()=>setDirectOpen(false)}>×</button></div><div className="form"><label className="field"><span>에스크로 금액</span><input className="input" type="number" value={direct.amount} onChange={e=>setDirect({...direct,amount:e.target.value})}/></label><label className="field"><span>카테고리</span><select className="input" value={direct.category_id} onChange={e=>setDirect({...direct,category_id:e.target.value})}><option value="">선택 안 함</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field full"><span>거래 제목</span><input className="input" value={direct.title} onChange={e=>setDirect({...direct,title:e.target.value})}/></label><label className="field full"><span>협의 내용</span><textarea className="textarea" value={direct.description} onChange={e=>setDirect({...direct,description:e.target.value})}/></label></div><div className="escrowNotice">요청 금액은 즉시 에스크로에 보관되며 거래 완료 전까지 판매자에게 지급되지 않습니다.</div><div className="actions"><button className="btn" onClick={()=>setDirectOpen(false)}>취소</button><button className="btn primary" onClick={createDirect}>에스크로 요청</button></div></div></div>}
 </main>
}
