'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api} from '../../lib/api';
const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';
const dt=x=>x?String(x).replace('T',' ').slice(0,16):'-';
export default function ReferralPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[me,setMe]=useState(null),[members,setMembers]=useState([]),[board,setBoard]=useState({month:'',items:[],king:null}),[busy,setBusy]=useState(false),[customCode,setCustomCode]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 async function load(){try{const [m,ms,b]=await Promise.all([api.referralMe(),api.referralMembers(),api.referralLeaderboard()]);setMe(m);setMembers(ms.items||[]);setBoard(b)}catch(e){alert(e.message)}}
 useEffect(()=>{if(session)load()},[session]);
 async function issue(){const code=customCode.trim().toUpperCase();if(!/^[A-Z0-9]{4,10}$/.test(code))return alert('추천코드는 영문/숫자 4~10자로 입력하세요.');setBusy(true);try{const r=await api.issueReferralCode(code);await load();setCustomCode('');alert(`추천코드가 생성되었습니다.\n${r.code}`)}catch(e){alert(String(e.message||'').includes('ALREADY_USED')?'이미 사용 중인 추천코드입니다.':e.message)}finally{setBusy(false)}}
 async function copy(){if(!me?.code)return;try{await navigator.clipboard.writeText(me.code);alert('추천코드를 복사했습니다.')}catch{alert(me.code)}}
 if(!ready)return <div className="authPage"><div className="authCard">추천인 정보를 불러오는 중...</div></div>;
 if(!session)return <div className="authPage"><div className="authCard"><h1>ANGEL PAY</h1><p>먼저 로그인하세요.</p><a className="btn primary" href="/">로그인 화면</a></div></div>;
 const stats=[['이번달 유효추천',`${Number(me?.monthly_referrals||0).toLocaleString()}명`],['누적 가입추천',`${Number(me?.total_referrals||0).toLocaleString()}명`],['유효 추천',`${Number(me?.valid_referrals||0).toLocaleString()}명`],['누적 보상',fmt(me?.total_reward)]];
 return <main className="content" style={{maxWidth:1250,margin:'0 auto',paddingTop:34}}><div className="head"><div><span className="eyebrow">N PAY REFERRAL</span><h1 style={{margin:'7px 0 5px'}}>추천인</h1><p>추천 회원의 관리자 승인 입금 금액 기준 2%가 추천 보상으로 지급됩니다.</p></div><button className="btn" onClick={load}>새로고침</button></div>
 <section className="card" style={{marginTop:18}}><div className="head"><div><h2>내 추천코드</h2><p>원하는 코드를 직접 만들 수 있으며 최초 생성 후 변경할 수 없습니다.</p></div>{me?.code&&<button className="btn primary" onClick={copy}>코드 복사</button>}</div>{me?.code?<div style={{fontSize:28,fontWeight:950,letterSpacing:2,padding:'20px 0'}}>{me.code}</div>:<div style={{display:'flex',gap:8,alignItems:'end',maxWidth:520,marginTop:16}}><label className="field" style={{flex:1}}><span>추천코드 만들기</span><input className="input" value={customCode} maxLength={10} onChange={e=>setCustomCode(e.target.value.replace(/[^a-zA-Z0-9]/g,'').toUpperCase())} placeholder="예: ANGEL7"/></label><button className="btn primary" disabled={busy} onClick={issue}>{busy?'생성 중...':'추천코드 생성'}</button></div>}</section>
 <div className="stats" style={{marginTop:14}}>{stats.map(([l,v])=><div className="stat" key={l}><small>{l}</small><strong>{v}</strong></div>)}</div>
 <section className="card" style={{marginTop:14}}><div className="head"><div><h2>내 추천인 현황</h2><p>추천코드로 가입한 회원의 입금 및 보상 현황입니다.</p></div><span className="badge">총 {members.length}명</span></div><div className="table"><table><thead><tr><th>회원</th><th>가입일</th><th>상태</th><th>첫 승인입금</th><th>누적 승인입금</th><th>이번달 보상</th><th>누적 보상</th></tr></thead><tbody>{members.length?members.map(x=><tr key={x.user_id}><td>{x.name}</td><td>{dt(x.joined_at)}</td><td>{x.qualified?<span className="badge ok">유효추천</span>:<span className="badge">대기</span>}</td><td>{fmt(x.first_approved_deposit)}<small style={{display:'block'}}>{dt(x.first_approved_deposit_at)}</small></td><td>{fmt(x.total_approved_deposit)}</td><td>{fmt(x.monthly_reward)}</td><td>{fmt(x.total_reward)}</td></tr>):<tr><td colSpan="7" className="empty">아직 추천 가입자가 없습니다.</td></tr>}</tbody></table></div></section>
 <section className="card" style={{marginTop:14}}><div className="head"><div><h2>{board.month} 추천왕</h2><p>첫 승인 입금 기준을 충족한 유효 추천회원만 집계합니다.</p></div>{board.king&&<span className="badge ok">현재 1위 · {board.king.name}</span>}</div><div className="table"><table><thead><tr><th>순위</th><th>회원</th><th>유효 추천</th><th>이번달 추천보상</th></tr></thead><tbody>{board.items?.length?board.items.map(r=><tr key={r.user_id} style={r.is_me?{fontWeight:900}:null}><td>{r.rank===1?'👑 1':r.rank}</td><td>{r.name}{r.is_me?' (나)':''}</td><td>{Number(r.referral_count||0).toLocaleString()}명</td><td>{fmt(r.reward_amount)}</td></tr>):<tr><td colSpan="4" className="empty">이번달 유효 추천 실적이 없습니다.</td></tr>}</tbody></table></div></section>
 <section className="card" style={{marginTop:14}}><h2>추천 보상 기준</h2><div className="note">첫 승인 입금 {fmt(me?.qualification_charge||10000)} 이상이면 유효 추천으로 인정됩니다. 승인 입금 금액의 {Number(me?.reward_rate_percent||2)}%만 지급되며 출금에는 보상이 없습니다. 추천회원 1명당 월 상한은 {fmt(me?.monthly_reward_cap_per_referred||100000)}입니다.</div></section></main>;
}
