'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api,BASE} from '../../lib/api';

const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';
export default function AdminPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[data,setData]=useState(null),[banners,setBanners]=useState([]),[fee,setFee]=useState(''),[minWithdraw,setMinWithdraw]=useState(''),[vipPrice,setVipPrice]=useState('150000'),[vipDays,setVipDays]=useState('30'),[cat,setCat]=useState({name:'',slug:'',sort_order:'0'});
 const [banner,setBanner]=useState({title:'',target_url:'',sort_order:'0'}),[bannerFile,setBannerFile]=useState(null),[bannerPreview,setBannerPreview]=useState(''),[bannerBusy,setBannerBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 async function load(){try{const [r,b]=await Promise.all([api.adminMarketOverview(),api.adminBanners()]);setData(r);setBanners(b.items||[]);setFee(String(r.settings?.withdrawal_fee_percent??3));setMinWithdraw(String(r.settings?.minimum_withdrawal??10000));setVipPrice(String(r.settings?.vip_price??150000));setVipDays(String(r.settings?.vip_days??30))}catch(e){alert(e.message)}}
 useEffect(()=>{if(session?.user?.app_metadata?.role==='admin')load()},[session]);
 if(!ready)return <div className="authPage"><div className="authCard"><h1>HUB24 <span>ADMIN</span></h1><p>권한 확인 중...</p></div></div>;
 const isAdmin=session?.user?.app_metadata?.role==='admin';
 if(!session||!isAdmin)return <div className="authPage"><div className="authCard"><h1>HUB24 <span>ADMIN</span></h1><p>관리자 권한이 없습니다.</p><a className="btn" href="/">사용자 화면으로 이동</a></div></div>;
 async function saveSettings(){try{await api.adminMarketSettings({withdrawal_fee_percent:Number(fee),minimum_withdrawal:Number(minWithdraw)});await api.adminVipSettings({vip_price:Number(vipPrice),vip_days:Number(vipDays)});await load();alert('마켓 설정을 저장했습니다.')}catch(e){alert(e.message)}}
 async function addCategory(){if(!cat.name||!cat.slug)return alert('카테고리명과 slug를 입력하세요.');try{await api.adminAddCategory({name:cat.name,slug:cat.slug,sort_order:Number(cat.sort_order||0)});setCat({name:'',slug:'',sort_order:'0'});await load()}catch(e){alert(e.message)}}
 async function toggleCategory(c){try{await api.adminUpdateCategory(c.id,{is_active:!c.is_active});await load()}catch(e){alert(e.message)}}
 async function sellerStatus(id,status){try{await api.adminSellerStatus(id,status);await load()}catch(e){alert(e.message)}}
 async function tradeResolve(id,action){if(!confirm(action==='REFUND'?'구매자에게 에스크로를 환불할까요?':'판매자에게 에스크로를 지급할까요?'))return;try{await api.adminResolveTrade(id,action);await load()}catch(e){alert(e.message)}}
 async function chargeResolve(id,action){try{await api.adminResolveCharge(id,action);await load()}catch(e){alert(e.message)}}
 async function withdrawalResolve(id,action){if(!confirm(action==='PAID'?'외부 지급을 완료한 출금건으로 처리할까요?':'출금을 반려하고 판매대금을 복구할까요?'))return;try{await api.adminResolveWithdrawal(id,action);await load()}catch(e){alert(e.message)}}
 async function uploadBanner(){if(!bannerFile)return alert('배너 이미지를 등록하세요.');if(!banner.title.trim())return alert('배너 제목을 입력하세요.');if(!bannerFile.type?.startsWith('image/'))return alert('이미지 파일만 등록할 수 있습니다.');setBannerBusy(true);try{const ext=(bannerFile.name.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'').toLowerCase();const path=`${session.user.id}/banners/${Date.now()}-${Math.random().toString(36).slice(2,8)}.${ext}`;const {error}=await supabase.storage.from('market-media').upload(path,bannerFile,{cacheControl:'3600',upsert:false,contentType:bannerFile.type});if(error)throw error;const {data:pub}=supabase.storage.from('market-media').getPublicUrl(path);await api.adminAddBanner({title:banner.title.trim(),image_url:pub.publicUrl,target_url:banner.target_url||null,sort_order:Number(banner.sort_order||0),is_active:true});setBanner({title:'',target_url:'',sort_order:'0'});setBannerFile(null);setBannerPreview('');await load();alert('광고 배너를 등록했습니다.')}catch(e){alert(e.message)}finally{setBannerBusy(false)}}
 async function toggleBanner(b){try{await api.adminUpdateBanner(b.id,{is_active:!b.is_active});await load()}catch(e){alert(e.message)}}
 async function deleteBanner(b){if(!confirm('이 광고 배너를 삭제할까요?'))return;try{await api.adminDeleteBanner(b.id);await load()}catch(e){alert(e.message)}}
 const d=data||{categories:[],sellers:[],trades:[],charges:[],withdrawals:[]};
 return <main className="content" style={{maxWidth:1500,margin:'0 auto'}}>
  <div className="head"><div><h1>HUB24 ADMIN</h1><p>마켓 · 에스크로 · 포인트 운영</p></div><div className="actions compact"><button className="btn" onClick={load}>새로고침</button><a className="btn" href="/">사용자 화면</a></div></div>
  <section className="card"><h2>운영 설정</h2><div className="form"><label className="field"><span>판매자 출금 수수료 (%)</span><input className="input" type="number" step="0.1" value={fee} onChange={e=>setFee(e.target.value)}/></label><label className="field"><span>최소 출금액 (P)</span><input className="input" type="number" value={minWithdraw} onChange={e=>setMinWithdraw(e.target.value)}/></label><label className="field"><span>VIP 판매자 가격 (P)</span><input className="input" type="number" value={vipPrice} onChange={e=>setVipPrice(e.target.value)}/></label><label className="field"><span>VIP 판매자 이용기간 (일)</span><input className="input" type="number" value={vipDays} onChange={e=>setVipDays(e.target.value)}/></label></div><div className="actions"><button className="btn primary" onClick={saveSettings}>설정 저장</button></div><div className="note">기본 VIP 판매자 등록값은 150,000P / 30일입니다. service_role key 등 민감정보는 표시하지 않습니다.</div></section>
  <section className="card" style={{marginTop:14}}><div className="head"><div><h2>자유시장 광고배너</h2><p>자유시장 상단 탭 아래 광고영역에 노출됩니다.</p></div></div><div className="form"><label className="field"><span>배너 제목</span><input className="input" value={banner.title} onChange={e=>setBanner({...banner,title:e.target.value})}/></label><label className="field"><span>클릭 링크</span><input className="input" value={banner.target_url} onChange={e=>setBanner({...banner,target_url:e.target.value})} placeholder="https://..."/></label><label className="field"><span>정렬 순서</span><input className="input" type="number" value={banner.sort_order} onChange={e=>setBanner({...banner,sort_order:e.target.value})}/></label><label className="field"><span>배너 이미지</span><input className="input" type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0]||null;setBannerFile(f);setBannerPreview(f?URL.createObjectURL(f):'')}}/></label></div>{bannerPreview&&<img src={bannerPreview} alt="배너 미리보기" style={{width:'100%',maxWidth:560,height:120,objectFit:'cover',borderRadius:10,marginTop:12}}/>}<div className="actions"><button className="btn primary" disabled={bannerBusy} onClick={uploadBanner}>{bannerBusy?'업로드 중...':'광고배너 등록'}</button></div><div className="adminBannerGrid">{banners.length?banners.map(b=><div className="adminBannerCard" key={b.id}><img src={b.image_url} alt={b.title}/><div><b>{b.title}</b><span>{b.is_active?'노출중':'숨김'} · 순서 {b.sort_order}</span><div className="adminBannerActions"><button onClick={()=>toggleBanner(b)}>{b.is_active?'숨기기':'노출하기'}</button><button onClick={()=>deleteBanner(b)}>삭제</button></div></div></div>):<div className="empty">등록된 광고배너가 없습니다.</div>}</div></section>
  <section className="card" style={{marginTop:14}}><div className="head"><div><h2>자유시장 카테고리</h2><p>사용자 자유시장 카테고리 메뉴에 즉시 반영됩니다.</p></div></div><div className="form"><label className="field"><span>카테고리명</span><input className="input" value={cat.name} onChange={e=>setCat({...cat,name:e.target.value})}/></label><label className="field"><span>slug</span><input className="input" value={cat.slug} onChange={e=>setCat({...cat,slug:e.target.value})} placeholder="digital-goods"/></label><label className="field"><span>정렬순서</span><input className="input" type="number" value={cat.sort_order} onChange={e=>setCat({...cat,sort_order:e.target.value})}/></label></div><div className="actions"><button className="btn primary" onClick={addCategory}>카테고리 추가</button></div><div className="table" style={{marginTop:14}}><table><thead><tr><th>ID</th><th>카테고리</th><th>slug</th><th>정렬</th><th>상태</th><th>관리</th></tr></thead><tbody>{d.categories.map(c=><tr key={c.id}><td>#{c.id}</td><td>{c.name}</td><td>{c.slug}</td><td>{c.sort_order}</td><td>{c.is_active?'노출':'숨김'}</td><td><button className="btn" onClick={()=>toggleCategory(c)}>{c.is_active?'숨기기':'노출하기'}</button></td></tr>)}</tbody></table></div></section>
  <section className="card" style={{marginTop:14}}><h2>판매자 관리</h2><div className="table"><table><thead><tr><th>판매자</th><th>상태</th><th>VIP 만료</th><th>레벨</th><th>완료</th><th>누적 판매</th><th>분쟁</th><th>관리</th></tr></thead><tbody>{d.sellers.length?d.sellers.map(s=><tr key={s.user_id}><td>{s.seller_name}</td><td>{s.status}</td><td>{s.vip_until?String(s.vip_until).replace('T',' ').slice(0,16):'-'}</td><td>Lv.{s.level}</td><td>{s.completed_sales||0}</td><td>{fmt(s.total_sales_amount)}</td><td>{s.dispute_count||0}</td><td className="nowrap"><button className="btn primary" onClick={()=>sellerStatus(s.user_id,'APPROVED')}>승인</button> <button className="btn danger" onClick={()=>sellerStatus(s.user_id,'SUSPENDED')}>정지</button> <button className="btn" onClick={()=>sellerStatus(s.user_id,'REJECTED')}>반려</button></td></tr>):<tr><td colSpan="8" className="empty">판매자 신청이 없습니다.</td></tr>}</tbody></table></div></section>
  <section className="card" style={{marginTop:14}}><h2>에스크로 / 분쟁 거래</h2><div className="table"><table><thead><tr><th>거래</th><th>유형</th><th>제목</th><th>금액</th><th>상태</th><th>생성</th><th>중개</th></tr></thead><tbody>{d.trades.length?d.trades.map(t=><tr key={t.id}><td>#{t.id}</td><td>{t.trade_type}</td><td>{t.title_snapshot}</td><td>{fmt(t.amount)}</td><td>{t.status}</td><td>{t.created_at?.replace('T',' ').slice(0,19)}</td><td className="nowrap">{!['COMPLETED','CANCELLED'].includes(t.status)&&<><button className="btn" onClick={()=>tradeResolve(t.id,'REFUND')}>구매자 환불</button> <button className="btn primary" onClick={()=>tradeResolve(t.id,'RELEASE')}>판매자 지급</button></>}</td></tr>):<tr><td colSpan="7" className="empty">거래가 없습니다.</td></tr>}</tbody></table></div></section>
  <div className="two" style={{marginTop:14}}><section className="card"><h2>충전 승인</h2><div className="table"><table><thead><tr><th>ID</th><th>회원</th><th>금액</th><th>상태</th><th>처리</th></tr></thead><tbody>{d.charges.length?d.charges.map(r=><tr key={r.id}><td>#{r.id}</td><td>{String(r.user_id).slice(0,8)}...</td><td>{fmt(r.amount)}</td><td>{r.status}</td><td>{r.status==='PENDING'&&<><button className="btn primary" onClick={()=>chargeResolve(r.id,'APPROVE')}>승인</button> <button className="btn danger" onClick={()=>chargeResolve(r.id,'REJECT')}>반려</button></>}</td></tr>):<tr><td colSpan="5" className="empty">충전 신청이 없습니다.</td></tr>}</tbody></table></div></section><section className="card"><h2>출금 관리</h2><div className="table"><table><thead><tr><th>ID</th><th>신청</th><th>수수료</th><th>실지급</th><th>상태</th><th>처리</th></tr></thead><tbody>{d.withdrawals.length?d.withdrawals.map(r=><tr key={r.id}><td>#{r.id}</td><td>{fmt(r.requested_amount)}</td><td>{fmt(r.fee_amount)}</td><td>{fmt(r.payout_amount)}</td><td>{r.status}</td><td>{r.status==='PENDING'&&<><button className="btn primary" onClick={()=>withdrawalResolve(r.id,'PAID')}>지급완료</button> <button className="btn danger" onClick={()=>withdrawalResolve(r.id,'REJECT')}>반려</button></>}</td></tr>):<tr><td colSpan="6" className="empty">출금 신청이 없습니다.</td></tr>}</tbody></table></div></section></div>
  <section className="card" style={{marginTop:14}}><h2>시스템</h2><label className="field"><span>Worker URL</span><input className="input" readOnly value={BASE}/></label></section>
 </main>
}
