'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api} from '../../lib/api';

const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';

export default function AdminPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[data,setData]=useState(null),[fee,setFee]=useState(''),[minWithdraw,setMinWithdraw]=useState(''),[vipPrice,setVipPrice]=useState('150000'),[vipDays,setVipDays]=useState('30'),[cat,setCat]=useState({name:'',slug:'',sort_order:'0'});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 async function load(){try{const r=await api.adminMarketOverview();setData(r);setFee(String(r.settings?.withdrawal_fee_percent??3));setMinWithdraw(String(r.settings?.minimum_withdrawal??10000));setVipPrice(String(r.settings?.vip_price??150000));setVipDays(String(r.settings?.vip_days??30))}catch(e){alert(e.message)}}
 useEffect(()=>{if(session?.user?.app_metadata?.role==='admin')load()},[session]);
 if(!ready)return <div className="authPage"><div className="authCard"><h1>ANGEL PAY <span>ADMIN</span></h1><p>권한 확인 중...</p></div></div>;
 const isAdmin=session?.user?.app_metadata?.role==='admin';
 if(!session||!isAdmin)return <div className="authPage"><div className="authCard"><h1>ANGEL PAY <span>ADMIN</span></h1><p>관리자 권한이 없습니다.</p><a className="btn" href="/">사용자 화면으로 이동</a></div></div>;
 async function saveSettings(){try{await api.adminMarketSettings({withdrawal_fee_percent:Number(fee),minimum_withdrawal:Number(minWithdraw)});await api.adminVipSettings({vip_price:Number(vipPrice),vip_days:Number(vipDays)});await load();alert('마켓 설정을 저장했습니다.')}catch(e){alert(e.message)}}
 async function addCategory(){if(!cat.name||!cat.slug)return alert('카테고리명과 slug를 입력하세요.');try{await api.adminAddCategory({name:cat.name,slug:cat.slug,sort_order:Number(cat.sort_order||0)});setCat({name:'',slug:'',sort_order:'0'});await load()}catch(e){alert(e.message)}}
 async function toggleCategory(c){try{await api.adminUpdateCategory(c.id,{is_active:!c.is_active});await load()}catch(e){alert(e.message)}}
 async function sellerStatus(id,status){try{await api.adminSellerStatus(id,status);await load()}catch(e){alert(e.message)}}
 async function tradeResolve(id,action){if(!confirm(action==='REFUND'?'구매자에게 에스크로를 환불할까요?':'판매자에게 에스크로를 지급할까요?'))return;try{await api.adminResolveTrade(id,action);await load()}catch(e){alert(e.message)}}
 const d=data||{categories:[],sellers:[],trades:[]};
 const shortcuts=[['회원 관리','/admin/members','회원정보 · 포인트 수동 조정'],['USDT 충전','/admin/usdt','입금주소 · 환율 · 충전신청'],['공지사항 관리','/admin/notices','전체 게시판 최상단 공지 작성 · 수정 · 노출'],['고객센터 · 공지알림','/admin/communications','텔레그램 링크 · 개별/전체 알림'],['광고 슬롯','/admin/banner-settings','유료배너 설정 · 종료/환불'],['추천인 설정','/admin/referrals','추천 기준 · 월 한도'],['출금 상세관리','/admin/withdrawals','수취정보 · 지급/반려'],['관리자 로그','/admin/logs','운영 변경 이력']];
 return <main className="content" style={{maxWidth:1500,margin:'0 auto'}}>
  <div className="head"><div><h1>ANGEL PAY ADMIN</h1><p>N PAY · 마켓 · 에스크로 · 포인트 운영</p></div><div className="actions compact"><button className="btn" onClick={load}>새로고침</button><a className="btn" href="/">사용자 화면</a></div></div>
  <section className="card"><h2>관리 바로가기</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:10,marginTop:12}}>{shortcuts.map(([t,h,d])=><a key={h} href={h} className="card" style={{textDecoration:'none',padding:14}}><b style={{color:'#eaf4ff'}}>{t}</b><small style={{display:'block',color:'#8fa8c1',marginTop:6}}>{d}</small></a>)}</div></section>
  <section className="card" style={{marginTop:14}}><h2>운영 설정</h2><div className="form"><label className="field"><span>판매자 출금 수수료 (%)</span><input className="input" type="number" step="0.1" value={fee} onChange={e=>setFee(e.target.value)}/></label><label className="field"><span>최소 출금액 (P)</span><input className="input" type="number" value={minWithdraw} onChange={e=>setMinWithdraw(e.target.value)}/></label><label className="field"><span>VIP 판매자 가격 (P)</span><input className="input" type="number" value={vipPrice} onChange={e=>setVipPrice(e.target.value)}/></label><label className="field"><span>VIP 판매자 이용기간 (일)</span><input className="input" type="number" value={vipDays} onChange={e=>setVipDays(e.target.value)}/></label></div><div className="actions"><button className="btn primary" onClick={saveSettings}>설정 저장</button></div></section>
  <section className="card" style={{marginTop:14}}><div className="head"><div><h2>자유시장 카테고리</h2><p>사용자 자유시장 카테고리에 반영됩니다.</p></div></div><div className="form"><label className="field"><span>카테고리명</span><input className="input" value={cat.name} onChange={e=>setCat({...cat,name:e.target.value})}/></label><label className="field"><span>slug</span><input className="input" value={cat.slug} onChange={e=>setCat({...cat,slug:e.target.value})} placeholder="digital-goods"/></label><label className="field"><span>정렬순서</span><input className="input" type="number" value={cat.sort_order} onChange={e=>setCat({...cat,sort_order:e.target.value})}/></label></div><div className="actions"><button className="btn primary" onClick={addCategory}>카테고리 추가</button></div><div className="table" style={{marginTop:14}}><table><thead><tr><th>ID</th><th>카테고리</th><th>slug</th><th>정렬</th><th>상태</th><th>관리</th></tr></thead><tbody>{d.categories?.length?d.categories.map(c=><tr key={c.id}><td>#{c.id}</td><td>{c.name}</td><td>{c.slug}</td><td>{c.sort_order}</td><td>{c.is_active?'노출':'숨김'}</td><td><button className="btn" onClick={()=>toggleCategory(c)}>{c.is_active?'숨기기':'노출하기'}</button></td></tr>):<tr><td colSpan="6" className="empty">카테고리가 없습니다.</td></tr>}</tbody></table></div></section>
  <section className="card" style={{marginTop:14}}><h2>판매자 관리</h2><div className="table"><table><thead><tr><th>판매자</th><th>상태</th><th>VIP 만료</th><th>레벨</th><th>완료</th><th>누적 판매</th><th>분쟁</th><th>관리</th></tr></thead><tbody>{d.sellers?.length?d.sellers.map(s=><tr key={s.user_id}><td>{s.seller_name}</td><td>{s.status}</td><td>{s.vip_until?String(s.vip_until).replace('T',' ').slice(0,16):'-'}</td><td>Lv.{s.level}</td><td>{s.completed_sales||0}</td><td>{fmt(s.total_sales_amount)}</td><td>{s.dispute_count||0}</td><td className="nowrap"><button className="btn primary" onClick={()=>sellerStatus(s.user_id,'APPROVED')}>승인</button> <button className="btn danger" onClick={()=>sellerStatus(s.user_id,'SUSPENDED')}>정지</button> <button className="btn" onClick={()=>sellerStatus(s.user_id,'REJECTED')}>반려</button></td></tr>):<tr><td colSpan="8" className="empty">판매자 신청이 없습니다.</td></tr>}</tbody></table></div></section>
  <section className="card" style={{marginTop:14}}><h2>에스크로 / 분쟁 거래</h2><div className="table"><table><thead><tr><th>거래</th><th>유형</th><th>제목</th><th>금액</th><th>상태</th><th>생성</th><th>중개</th></tr></thead><tbody>{d.trades?.length?d.trades.map(t=><tr key={t.id}><td>#{t.id}</td><td>{t.trade_type}</td><td>{t.title_snapshot}</td><td>{fmt(t.amount)}</td><td>{t.status}</td><td>{t.created_at?.replace('T',' ').slice(0,19)}</td><td className="nowrap">{!['COMPLETED','CANCELLED'].includes(t.status)&&<><button className="btn" onClick={()=>tradeResolve(t.id,'REFUND')}>구매자 환불</button> <button className="btn primary" onClick={()=>tradeResolve(t.id,'RELEASE')}>판매자 지급</button></>}</td></tr>):<tr><td colSpan="7" className="empty">거래가 없습니다.</td></tr>}</tbody></table></div></section>
 </main>;
}
