'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api} from '../../lib/api';
const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';
const dt=x=>x?String(x).replace('T',' ').slice(0,19):'-';
const statusLabel=s=>({REQUESTED:'입금 대기',VERIFY_REQUESTED:'입금 확인중',PAID:'충전 완료',CANCELLED:'취소',EXPIRED:'만료'}[s]||s||'-');
const checkMsg=e=>{const s=String(e||'');if(!s)return '';if(s.includes('CONFIRMED_USDT_TX_NOT_FOUND'))return '아직 블록체인에서 확정된 USDT 입금이 확인되지 않았습니다.';if(s.includes('MATCHING_USDT_TX_NOT_FOUND'))return '신청 이후 이 주소로 들어온 매칭 가능한 USDT 입금을 찾지 못했습니다.';if(s.includes('AMOUNT_TOO_LOW'))return '확인된 입금액이 신청에 필요한 USDT 금액보다 적습니다.';if(s.includes('TRONGRID_HTTP_401')||s.includes('TRONGRID_HTTP_403'))return 'TronGrid API 인증에 실패했습니다. 관리자 설정을 확인해 주세요.';if(s.includes('TRONGRID_HTTP_429'))return 'TronGrid 요청 한도를 초과했습니다. 잠시 후 다시 확인해 주세요.';if(s.includes('TRONGRID_REQUEST_ERROR'))return 'TronGrid 연결 중 오류가 발생했습니다.';if(s.includes('CREDIT_ERROR'))return '입금은 확인됐지만 포인트 반영 중 오류가 발생했습니다. 관리자 확인이 필요합니다.';return s};
export default function WalletPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[data,setData]=useState(null),[withdrawals,setWithdrawals]=useState([]),[usdt,setUsdt]=useState(null),[tab,setTab]=useState('overview'),[chargeAmount,setChargeAmount]=useState(''),[busy,setBusy]=useState(false);
 const [withdrawAmount,setWithdrawAmount]=useState(''),[payoutMethod,setPayoutMethod]=useState('BANK'),[payoutDetails,setPayoutDetails]=useState(''),[withdrawNote,setWithdrawNote]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)});if(typeof window!=='undefined'){const t=new URLSearchParams(window.location.search).get('tab');setTab(['charge','withdraw','history'].includes(t)?t:'overview')}},[]);
 async function load(){try{const [w,x,u]=await Promise.all([api.wallet(),api.withdrawals(),api.usdtAutocharge().catch(()=>null)]);setData(w);setWithdrawals(x.items||[]);setUsdt(u)}catch(e){alert(e.message)}}
 useEffect(()=>{if(session)load()},[session]);
 if(!ready)return <div className="authPage"><div className="authCard">자금 정보를 불러오는 중...</div></div>;
 if(!session)return <div className="authPage"><div className="authCard"><h1>ANGEL PAY</h1><p>먼저 로그인하세요.</p><a className="btn primary" href="/">로그인 화면</a></div></div>;
 const w=data?.wallet||{},req=usdt?.active_request;
 async function createCharge(){const n=Math.floor(Number(chargeAmount));if(n<=0)return alert('충전 금액을 입력하세요.');setBusy(true);try{await api.createUsdtCharge(n);setChargeAmount('');await load()}catch(e){const m=String(e.message||'');if(m.includes('ACTIVE_CHARGE_REQUEST'))alert('진행 중인 충전신청이 있습니다. 먼저 기존 신청을 완료하세요.');else if(m.includes('NO_USDT_ADDRESS'))alert('현재 사용 가능한 입금주소가 없습니다. 고객센터로 문의하세요.');else alert(m)}finally{setBusy(false)}}
 async function verifyCharge(){if(!req?.id)return;setBusy(true);try{const r=await api.verifyUsdtCharge(req.id);await load();if(r?.status==='PAID')alert('입금 확인이 완료되어 포인트가 반영되었습니다.');else alert(checkMsg(r?.last_check_error)||'아직 입금 확인 중입니다. 잠시 후 다시 확인해 주세요.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function copyAddress(){if(!req?.address)return;try{await navigator.clipboard.writeText(req.address);alert('입금주소를 복사했습니다.')}catch{alert(req.address)}}
 async function withdraw(){if(Number(withdrawAmount)<=0)return alert('출금 금액을 입력하세요.');if(!payoutDetails.trim())return alert('수취 정보를 입력하세요.');try{await api.requestWithdrawal({amount:Number(withdrawAmount),payout_method:payoutMethod,payout_details:payoutDetails.trim(),user_note:withdrawNote.trim()||null});setWithdrawAmount('');setPayoutDetails('');setWithdrawNote('');await load();alert('출금 신청이 접수되었습니다.')}catch(e){alert(e.message)}}
 return <main className="fundsPage"><section className="fundsHero"><div><span className="eyebrow">N PAY FUNDS</span><h1>자금 관리</h1><p>충전, 에스크로, 판매대금, 출금을 관리합니다.</p></div><button className="softButton" onClick={load}>새로고침</button></section>
 <section className="balancePanel"><div><span>사용 가능</span><strong>{fmt(w.available_balance)}</strong></div><div><span>에스크로 보관</span><strong>{fmt(w.escrow_balance)}</strong></div><div><span>판매 정산</span><strong>{fmt(w.settlement_balance)}</strong></div><div><span>총 보유</span><strong>{fmt(Number(w.available_balance||0)+Number(w.escrow_balance||0)+Number(w.settlement_balance||0))}</strong></div></section>
 <div className="fundTabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>요약</button><button className={tab==='charge'?'active':''} onClick={()=>setTab('charge')}>충전</button><button className={tab==='withdraw'?'active':''} onClick={()=>setTab('withdraw')}>출금</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>포인트 내역</button></div>
 {tab==='overview'&&<section className="fundOverviewGrid"><button onClick={()=>setTab('charge')}><span>포인트 충전</span><b>USDT · TRC20</b><small>금액 입력 → 주소 발급 → 입금 → 확인요청</small></button><button onClick={()=>setTab('withdraw')}><span>판매대금 출금</span><b>{fmt(w.settlement_balance)}</b><small>출금 가능 판매대금을 확인하세요.</small></button><button onClick={()=>setTab('history')}><span>거래 원장</span><b>{(data?.ledger||[]).length}건</b><small>모든 포인트 변동 기록을 확인합니다.</small></button></section>}
 {tab==='charge'&&<section className="fundActionCard"><div className="sectionTitle"><h2>USDT 충전</h2><p>충전할 포인트 금액을 먼저 입력하면 해당 신청의 TRC20 입금주소와 필요한 USDT 금액이 표시됩니다.</p></div>
 {!req?<><div className="fundForm"><label><span>충전 금액</span><input type="number" value={chargeAmount} onChange={e=>setChargeAmount(e.target.value)} placeholder="예: 100000"/></label><button disabled={busy} onClick={createCharge}>{busy?'처리 중...':'충전신청'}</button></div><div className="note">현재 환산 기준: 1 USDT = {Number(usdt?.krw_rate||0).toLocaleString('ko-KR')}P · Google 환율 기준으로 신청 시점 환율이 고정됩니다.</div></>:<><div className="withdrawAvailable"><span>신청 금액</span><strong>{fmt(req.requested_points)}</strong><small>전송할 금액: <b>{Number(req.requested_usdt||0).toLocaleString(undefined,{maximumFractionDigits:6})} USDT</b></small></div><div className="withdrawAvailable" style={{marginTop:10}}><span>입금주소 · TRON(TRC20)</span><strong style={{fontSize:16,wordBreak:'break-all'}}>{req.address}</strong><button className="btn" onClick={copyAddress}>주소 복사</button></div><div className="note">반드시 위 주소로 TRON(TRC20) USDT를 전송하세요. 신청 이후 발생한 입금만 확인합니다.</div>{req.last_check_error&&<div className="note" style={{marginTop:10}}>{checkMsg(req.last_check_error)}{req.last_checked_at?` · 마지막 확인 ${dt(req.last_checked_at)}`:''}</div>}<div className="actions"><button className="btn primary" disabled={busy} onClick={verifyCharge}>{busy?'확인 중...':req.status==='VERIFY_REQUESTED'?'다시 입금확인':'입금 완료 · 충전확인요청'}</button></div></>}
 <div className="simpleHistory"><h3>최근 충전신청</h3>{usdt?.requests?.length?usdt.requests.slice(0,10).map(x=><div key={x.id}><b>{fmt(x.requested_points)} · {Number(x.requested_usdt).toLocaleString(undefined,{maximumFractionDigits:6})} USDT</b><span>{statusLabel(x.status)}</span><small>{dt(x.created_at)}{x.matched_txid?` · TX ${String(x.matched_txid).slice(0,14)}...`:''}</small></div>):<p>충전신청 내역이 없습니다.</p>}</div></section>}
 {tab==='withdraw'&&<section className="fundActionCard"><div className="sectionTitle"><h2>판매대금 출금</h2></div><div className="fundForm"><label><span>출금 금액</span><input type="number" value={withdrawAmount} onChange={e=>setWithdrawAmount(e.target.value)}/></label><label><span>출금 방식</span><select value={payoutMethod} onChange={e=>setPayoutMethod(e.target.value)}><option value="BANK">은행</option><option value="USDT_TRC20">USDT TRC20</option><option value="TRX">TRX</option><option value="OTHER">기타</option></select></label><label><span>수취 정보</span><input value={payoutDetails} onChange={e=>setPayoutDetails(e.target.value)}/></label><label><span>신청 메모</span><input value={withdrawNote} onChange={e=>setWithdrawNote(e.target.value)}/></label><button onClick={withdraw}>출금 신청</button></div></section>}
 {tab==='history'&&<section className="ledgerCard"><div className="sectionTitle"><h2>포인트 내역</h2></div><div className="table"><table><thead><tr><th>일시</th><th>구분</th><th>변동</th><th>이전</th><th>이후</th><th>내용</th></tr></thead><tbody>{(data?.ledger||[]).length?(data.ledger||[]).map(x=><tr key={x.id}><td>{dt(x.created_at)}</td><td>{x.entry_type}</td><td>{Number(x.amount).toLocaleString()}P</td><td>{fmt(x.balance_before)}</td><td>{fmt(x.balance_after)}</td><td>{x.memo||'-'}</td></tr>):<tr><td colSpan="6" className="empty">포인트 내역이 없습니다.</td></tr>}</tbody></table></div></section>}</main>
}
