'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api} from '../../lib/api';
const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';
const dt=x=>x?String(x).replace('T',' ').slice(0,19):'-';
export default function WalletPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[data,setData]=useState(null),[charges,setCharges]=useState([]),[withdrawals,setWithdrawals]=useState([]),[usdt,setUsdt]=useState(null),[tab,setTab]=useState('overview');
 const [amount,setAmount]=useState(''),[note,setNote]=useState(''),[withdrawAmount,setWithdrawAmount]=useState(''),[payoutMethod,setPayoutMethod]=useState('BANK'),[payoutDetails,setPayoutDetails]=useState(''),[withdrawNote,setWithdrawNote]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)});if(typeof window!=='undefined'){const t=new URLSearchParams(window.location.search).get('tab');setTab(['charge','usdt','withdraw','history'].includes(t)?t:'overview')}},[]);
 async function load(){try{const [w,c,x,u]=await Promise.all([api.wallet(),api.chargeRequests(),api.withdrawals(),api.usdtAutocharge().catch(()=>null)]);setData(w);setCharges(c.items||[]);setWithdrawals(x.items||[]);setUsdt(u)}catch(e){alert(e.message)}}
 useEffect(()=>{if(session)load()},[session]);
 if(!ready)return <div className="authPage"><div className="authCard">자금 정보를 불러오는 중...</div></div>;
 if(!session)return <div className="authPage"><div className="authCard"><h1>ANGEL PAY</h1><p>먼저 로그인하세요.</p><a className="btn primary" href="/">로그인 화면</a></div></div>;
 const w=data?.wallet||{};
 async function charge(){if(Number(amount)<=0)return alert('충전 금액을 입력하세요.');try{await api.requestCharge({amount:Number(amount),note:note||null});setAmount('');setNote('');await load();alert('충전 신청이 접수되었습니다.')}catch(e){alert(e.message)}}
 async function withdraw(){if(Number(withdrawAmount)<=0)return alert('출금 금액을 입력하세요.');if(!payoutDetails.trim())return alert('수취 정보를 입력하세요.');try{await api.requestWithdrawal({amount:Number(withdrawAmount),payout_method:payoutMethod,payout_details:payoutDetails.trim(),user_note:withdrawNote.trim()||null});setWithdrawAmount('');setPayoutDetails('');setWithdrawNote('');await load();alert('출금 신청이 접수되었습니다.')}catch(e){alert(e.message)}}
 async function copyAddress(){if(!usdt?.address)return;try{await navigator.clipboard.writeText(usdt.address);alert('USDT 입금주소를 복사했습니다.')}catch{alert(usdt.address)}}
 return <main className="fundsPage"><section className="fundsHero"><div><span className="eyebrow">N PAY FUNDS</span><h1>자금 관리</h1><p>충전, USDT 자동충전, 에스크로, 판매대금, 출금을 관리합니다.</p></div><button className="softButton" onClick={load}>새로고침</button></section>
 <section className="balancePanel"><div><span>사용 가능</span><strong>{fmt(w.available_balance)}</strong></div><div><span>에스크로 보관</span><strong>{fmt(w.escrow_balance)}</strong></div><div><span>판매 정산</span><strong>{fmt(w.settlement_balance)}</strong></div><div><span>총 보유</span><strong>{fmt(Number(w.available_balance||0)+Number(w.escrow_balance||0)+Number(w.settlement_balance||0))}</strong></div></section>
 <div className="fundTabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>요약</button><button className={tab==='charge'?'active':''} onClick={()=>setTab('charge')}>수동 충전</button><button className={tab==='usdt'?'active':''} onClick={()=>setTab('usdt')}>USDT 자동충전</button><button className={tab==='withdraw'?'active':''} onClick={()=>setTab('withdraw')}>출금</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>포인트 내역</button></div>
 {tab==='overview'&&<section className="fundOverviewGrid"><button onClick={()=>setTab('usdt')}><span>USDT 자동충전</span><b>TRC20</b><small>입금 확인 후 자동으로 포인트가 반영됩니다.</small></button><button onClick={()=>setTab('charge')}><span>수동 충전</span><b>충전 신청</b><small>관리자 승인 방식입니다.</small></button><button onClick={()=>setTab('withdraw')}><span>판매대금 출금</span><b>{fmt(w.settlement_balance)}</b><small>출금 가능 판매대금을 확인하세요.</small></button><button onClick={()=>setTab('history')}><span>거래 원장</span><b>{(data?.ledger||[]).length}건</b><small>모든 포인트 변동 기록을 확인합니다.</small></button></section>}
 {tab==='usdt'&&<section className="fundActionCard"><div className="sectionTitle"><h2>USDT 자동충전</h2><p>반드시 TRON(TRC20) 네트워크의 USDT만 전송하세요. 확인된 입금은 자동으로 포인트에 반영됩니다.</p></div>{usdt?.address?<><div className="withdrawAvailable"><span>내 전용 USDT(TRC20) 입금주소</span><strong style={{fontSize:16,wordBreak:'break-all'}}>{usdt.address}</strong><button className="btn" onClick={copyAddress}>주소 복사</button></div><div className="note">현재 환산 기준: 1 USDT = {Number(usdt.krw_rate||0).toLocaleString('ko-KR')}P · 다른 네트워크 또는 다른 토큰 전송 시 자동충전되지 않습니다.</div><div className="simpleHistory"><h3>최근 USDT 자동충전</h3>{usdt.deposits?.length?usdt.deposits.map(x=><div key={x.id}><b>{Number(x.amount_usdt).toLocaleString()} USDT → {fmt(x.credit_points)}</b><span>{x.status}</span><small>{dt(x.credited_at||x.detected_at)} · TX {String(x.txid||'').slice(0,14)}...</small></div>):<p>아직 자동충전 내역이 없습니다.</p>}</div></>:<div className="note">사용 가능한 입금주소가 없습니다. 관리자에게 문의하세요.</div>}</section>}
 {tab==='charge'&&<section className="fundActionCard"><div className="sectionTitle"><h2>수동 포인트 충전</h2></div><div className="fundForm"><label><span>충전 금액</span><input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label><span>메모</span><input value={note} onChange={e=>setNote(e.target.value)}/></label><button onClick={charge}>충전 신청</button></div></section>}
 {tab==='withdraw'&&<section className="fundActionCard"><div className="sectionTitle"><h2>판매대금 출금</h2></div><div className="fundForm"><label><span>출금 금액</span><input type="number" value={withdrawAmount} onChange={e=>setWithdrawAmount(e.target.value)}/></label><label><span>출금 방식</span><select value={payoutMethod} onChange={e=>setPayoutMethod(e.target.value)}><option value="BANK">은행</option><option value="USDT_TRC20">USDT TRC20</option><option value="TRX">TRX</option><option value="OTHER">기타</option></select></label><label><span>수취 정보</span><input value={payoutDetails} onChange={e=>setPayoutDetails(e.target.value)}/></label><label><span>신청 메모</span><input value={withdrawNote} onChange={e=>setWithdrawNote(e.target.value)}/></label><button onClick={withdraw}>출금 신청</button></div></section>}
 {tab==='history'&&<section className="ledgerCard"><div className="sectionTitle"><h2>포인트 내역</h2></div><div className="table"><table><thead><tr><th>일시</th><th>구분</th><th>변동</th><th>이전</th><th>이후</th><th>내용</th></tr></thead><tbody>{(data?.ledger||[]).length?(data.ledger||[]).map(x=><tr key={x.id}><td>{dt(x.created_at)}</td><td>{x.entry_type}</td><td>{Number(x.amount).toLocaleString()}P</td><td>{fmt(x.balance_before)}</td><td>{fmt(x.balance_after)}</td><td>{x.memo||'-'}</td></tr>):<tr><td colSpan="6" className="empty">포인트 내역이 없습니다.</td></tr>}</tbody></table></div></section>}</main>
}
