'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {BASE} from '../../../lib/api';

async function call(path,opts={}){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('로그인이 필요합니다.');const r=await fetch(BASE+path,{...opts,headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,...(opts.headers||{})}});let b={};try{b=await r.json()}catch{};if(!r.ok)throw new Error(b.detail||`HTTP ${r.status}`);return b}

export default function TelegramCommunityCategoryAdmin(){
 const [items,setItems]=useState([]),[name,setName]=useState(''),[sortOrder,setSortOrder]=useState('0'),[busy,setBusy]=useState(false),[editing,setEditing]=useState(null);
 async function load(){try{const r=await call('/v1/admin/telegram-community-categories');setItems(r.items||[])}catch(e){alert(e.message)}}
 useEffect(()=>{load()},[]);
 async function add(){if(!name.trim())return alert('카테고리명을 입력하세요.');setBusy(true);try{await call('/v1/admin/telegram-community-categories',{method:'POST',body:JSON.stringify({name:name.trim(),sort_order:Number(sortOrder||0),is_active:true})});setName('');setSortOrder('0');await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function save(){if(!editing?.name?.trim())return alert('카테고리명을 입력하세요.');setBusy(true);try{await call(`/v1/admin/telegram-community-categories/${editing.id}`,{method:'PUT',body:JSON.stringify({name:editing.name.trim(),sort_order:Number(editing.sort_order||0),is_active:!!editing.is_active})});setEditing(null);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function toggle(x){try{await call(`/v1/admin/telegram-community-categories/${x.id}`,{method:'PUT',body:JSON.stringify({is_active:!x.is_active})});await load()}catch(e){alert(e.message)}}
 async function remove(x){if(!confirm(`“${x.name}” 카테고리를 삭제할까요?\n기존 홍보글은 삭제되지 않고 기타 카테고리로 이동합니다.`))return;try{await call(`/v1/admin/telegram-community-categories/${x.id}`,{method:'DELETE'});await load()}catch(e){alert(e.message)}}
 return <main className="content" style={{maxWidth:1100,margin:'0 auto'}}>
  <div className="head"><div><h1>텔레그램 커뮤니티 카테고리</h1><p>커뮤니티 등록/검색에 표시되는 카테고리를 코드 수정 없이 관리합니다.</p></div><button className="btn" onClick={load}>새로고침</button></div>
  <section className="card" style={{marginBottom:16}}><div className="head"><div><h2>새 카테고리 추가</h2><p>정렬순서가 낮을수록 앞에 표시됩니다.</p></div></div><div className="form"><label className="field"><span>카테고리명</span><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="예: 텔레그램 뉴스"/></label><label className="field"><span>정렬순서</span><input className="input" type="number" value={sortOrder} onChange={e=>setSortOrder(e.target.value)}/></label></div><div className="actions"><button className="btn primary" disabled={busy} onClick={add}>{busy?'저장 중...':'카테고리 추가'}</button></div></section>
  <section className="card"><div className="table"><table><thead><tr><th>순서</th><th>카테고리명</th><th>노출상태</th><th>관리</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td>{x.sort_order}</td><td><b>{x.name}</b></td><td>{x.is_active?'노출':'숨김'}</td><td className="nowrap"><button className="btn primary" onClick={()=>setEditing({...x})}>수정</button> <button className="btn" onClick={()=>toggle(x)}>{x.is_active?'숨기기':'노출하기'}</button> <button className="btn danger" onClick={()=>remove(x)}>삭제</button></td></tr>):<tr><td colSpan="4" className="empty">등록된 카테고리가 없습니다.</td></tr>}</tbody></table></div></section>
  {editing&&<div className="modalBack" onClick={()=>setEditing(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="head"><div><h2>카테고리 수정</h2><p>이름을 변경하면 기존 홍보글의 카테고리명도 함께 변경됩니다.</p></div><button className="x" onClick={()=>setEditing(null)}>×</button></div><div className="form"><label className="field"><span>카테고리명</span><input className="input" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label className="field"><span>정렬순서</span><input className="input" type="number" value={editing.sort_order} onChange={e=>setEditing({...editing,sort_order:e.target.value})}/></label><label className="field full"><span>노출상태</span><select className="input" value={editing.is_active?'1':'0'} onChange={e=>setEditing({...editing,is_active:e.target.value==='1'})}><option value="1">노출</option><option value="0">숨김</option></select></label></div><div className="actions"><button className="btn" onClick={()=>setEditing(null)}>취소</button><button className="btn primary" disabled={busy} onClick={save}>수정 저장</button></div></div></div>}
 </main>;
}
