'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api} from '../../lib/api';
const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';

function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result||'');resolve(s.includes(',')?s.split(',')[1]:s)};r.onerror=()=>reject(new Error('이미지를 읽지 못했습니다.'));r.readAsDataURL(file)})}

export default function DisputesPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[trades,setTrades]=useState([]),[selected,setSelected]=useState(null),[evidence,setEvidence]=useState([]),[text,setText]=useState(''),[file,setFile]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){try{const r=await api.marketTrades();setTrades((r.items||[]).filter(t=>['DISPUTED','CANCEL_REQUESTED','SELLER_COMPLETED','ESCROWED','ACCEPTED'].includes(t.status)))}catch(e){alert(e.message)}}
 async function open(t){setSelected(t);try{const r=await api.tradeEvidence(t.id);setEvidence(r.items||[])}catch(e){alert(e.message)}}
 async function submit(){if(!selected)return;if(!text.trim()&&!file)return alert('내용 또는 이미지 증빙을 등록하세요.');setBusy(true);try{let fileBase64=null;if(file){if(file.size>5*1024*1024)throw new Error('이미지는 최대 5MB입니다.');if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw new Error('JPG, PNG, WEBP, GIF 이미지만 등록할 수 있습니다.');fileBase64=await fileToBase64(file)}await api.addTradeEvidence(selected.id,{evidence_type:file?'IMAGE':'TEXT',content:text.trim()||null,file_base64:fileBase64,file_name:file?.name||null,content_type:file?.type||null});setText('');setFile(null);await open(selected);alert('증빙이 안전하게 등록되었습니다.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 if(!ready)return <div className="authPage"><div className="authCard">불러오는 중...</div></div>;
 if(!session)return <div className="authPage"><div className="authCard"><h1>ANGEL PAY</h1><p>먼저 로그인하세요.</p></div></div>;
 return <main className="content" style={{maxWidth:1300,margin:'0 auto',paddingTop:30}}><div className="head"><div><span className="eyebrow">N PAY DISPUTE</span><h1 style={{margin:'6px 0'}}>분쟁 / 증빙센터</h1><p>거래별 증빙은 거래 당사자와 관리자만 확인할 수 있습니다.</p></div></div><div className="two" style={{marginTop:18}}><section className="card"><h2>거래 선택</h2>{trades.length?trades.map(t=><button key={t.id} className="btn" style={{display:'block',width:'100%',textAlign:'left',marginTop:7}} onClick={()=>open(t)}>#{t.id} · {t.title_snapshot} · {fmt(t.amount)} · {t.status}</button>):<div className="empty">증빙 등록 가능한 거래가 없습니다.</div>}</section><section className="card">{selected?<><div className="head"><div><h2>거래 #{selected.id}</h2><p>{selected.title_snapshot} · {selected.status}</p></div></div><div style={{display:'grid',gap:8,maxHeight:320,overflow:'auto'}}>{evidence.length?evidence.map(x=><div key={x.id} className="note"><b>{String(x.user_id)===String(session.user.id)?'내 증빙':'상대방 증빙'}</b><div style={{marginTop:5,whiteSpace:'pre-wrap'}}>{x.content||''}</div>{x.file_url&&<a href={x.file_url} target="_blank" rel="noreferrer" style={{color:'#79bfff'}}>첨부 이미지 보기</a>}<small style={{display:'block',marginTop:5}}>{x.created_at?.replace('T',' ').slice(0,19)}</small></div>):<div className="empty">등록된 증빙이 없습니다.</div>}</div><div className="form" style={{marginTop:15}}><label className="field full"><span>증빙 내용</span><textarea className="textarea" value={text} onChange={e=>setText(e.target.value)} placeholder="상황과 증빙 내용을 구체적으로 입력하세요."/></label><label className="field full"><span>이미지 첨부 · 최대 5MB</span><input className="input" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><div className="note">새 이미지 증빙은 비공개 저장소에 보관되며 조회 시 임시 접근 링크가 발급됩니다.</div><div className="actions"><button className="btn primary" disabled={busy} onClick={submit}>{busy?'등록 중...':'증빙 등록'}</button></div></>:<div className="empty">왼쪽에서 거래를 선택하세요.</div>}</section></div></main>;
}