'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {BASE} from '../../../lib/api';

const money=n=>Number(n||0).toLocaleString('ko-KR')+' P';
const date=v=>v?String(v).replace('T',' ').slice(0,16):'-';

export default function AdminProductsPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[items,setItems]=useState([]),[categories,setCategories]=useState([]),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{const s=data.session||null;setSession(s);setReady(true);if(s?.user?.app_metadata?.role==='admin')load()})},[]);
 async function call(path,opts={}){const {data:{session:s}}=await supabase.auth.getSession();if(!s?.access_token)throw new Error('로그인이 필요합니다.');const r=await fetch(BASE+path,{...opts,headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`,...(opts.headers||{})}});if(!r.ok){let d={};try{d=await r.json()}catch{};throw new Error(d.detail||`HTTP ${r.status}`)}return r.json()}
 async function load(){try{const [p,c]=await Promise.all([call('/v1/admin/market/products'),call('/v1/market/categories')]);setItems(p.items||[]);setCategories(c.items||[])}catch(e){alert(e.message)}}
 function edit(p){setEditing({id:p.id,category_id:p.category_id?String(p.category_id):'',title:p.title||'',description:p.description||'',price:String(p.price??''),stock:p.stock==null?'':String(p.stock),status:p.status||'ACTIVE'})}
 async function save(){if(!editing?.title.trim())return alert('상품명을 입력하세요.');setBusy(true);try{await call(`/v1/admin/market/products/${editing.id}`,{method:'PUT',body:JSON.stringify({category_id:editing.category_id?Number(editing.category_id):null,title:editing.title.trim(),description:editing.description||'',price:Number(editing.price||0),stock:editing.stock===''?null:Number(editing.stock),status:editing.status})});setEditing(null);await load();alert('판매글을 수정했습니다.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function status(p,status){try{await call(`/v1/admin/market/products/${p.id}`,{method:'PUT',body:JSON.stringify({status})});await load()}catch(e){alert(e.message)}}
 async function remove(p){if(!confirm(`판매글 "${p.title}"을 삭제할까요?\n거래 이력이 있으면 기록 보존을 위해 숨김 처리됩니다.`))return;try{const r=await call(`/v1/admin/market/products/${p.id}`,{method:'DELETE'});await load();alert(r.hidden?'거래 이력이 있어 판매글을 숨김 처리했습니다.':'판매글을 삭제했습니다.')}catch(e){alert(e.message)}}
 if(!ready)return <main className="content"><section className="card">권한 확인 중...</section></main>;
 if(session?.user?.app_metadata?.role!=='admin')return <main className="content"><section className="card">관리자 권한이 없습니다.</section></main>;
 const q=query.trim().toLowerCase();const shown=items.filter(p=>!q||String(p.title||'').toLowerCase().includes(q)||String(p.seller?.seller_name||'').toLowerCase().includes(q)||String(p.seller_id||'').toLowerCase().includes(q));
 return <main className="content" style={{maxWidth:1400,margin:'0 auto'}}>
  <div className="head"><div><h1>판매글 관리</h1><p>자유시장에 등록된 전체 판매글을 관리자 권한으로 관리합니다.</p></div><div className="actions compact"><button className="btn" onClick={load}>새로고침</button><a className="btn" href="/admin">관리자 메인</a></div></div>
  <section className="card"><div style={{display:'flex',gap:8,marginBottom:14}}><input className="input" style={{flex:1}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="상품명 / 판매자명 / 판매자 ID 검색"/></div><div className="table"><table><thead><tr><th>ID</th><th>상품</th><th>판매자</th><th>카테고리</th><th>가격</th><th>재고</th><th>상태</th><th>등록일</th><th>관리</th></tr></thead><tbody>{shown.length?shown.map(p=><tr key={p.id}><td>#{p.id}</td><td><b>{p.title}</b></td><td>{p.seller?.seller_name||p.seller_id}</td><td>{p.category?.name||'기타'}</td><td>{money(p.price)}</td><td>{p.stock==null?'제한 없음':p.stock}</td><td>{p.status}</td><td>{date(p.created_at)}</td><td className="nowrap"><button className="btn primary" onClick={()=>edit(p)}>수정</button> {p.status==='ACTIVE'?<button className="btn" onClick={()=>status(p,'HIDDEN')}>숨기기</button>:<button className="btn" onClick={()=>status(p,'ACTIVE')}>재노출</button>} <button className="btn danger" onClick={()=>remove(p)}>삭제</button></td></tr>):<tr><td colSpan="9" className="empty">판매글이 없습니다.</td></tr>}</tbody></table></div></section>
  {editing&&<div className="modalBack" onClick={()=>setEditing(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="head"><div><h2>판매글 수정</h2><p>상품 #{editing.id}</p></div><button className="x" onClick={()=>setEditing(null)}>×</button></div><div className="form"><label className="field"><span>카테고리</span><select className="input" value={editing.category_id} onChange={e=>setEditing({...editing,category_id:e.target.value})}><option value="">기타</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field"><span>판매가격</span><input className="input" type="number" min="0" value={editing.price} onChange={e=>setEditing({...editing,price:e.target.value})}/></label><label className="field full"><span>상품명</span><input className="input" value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label className="field"><span>재고</span><input className="input" type="number" min="0" value={editing.stock} onChange={e=>setEditing({...editing,stock:e.target.value})} placeholder="빈 값 = 제한 없음"/></label><label className="field"><span>상태</span><select className="input" value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="ACTIVE">판매중</option><option value="PAUSED">판매중지</option><option value="SOLD_OUT">품절</option><option value="HIDDEN">숨김</option></select></label><label className="field full"><span>상품 설명</span><textarea className="input" rows="8" value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label></div><div className="actions"><button className="btn" onClick={()=>setEditing(null)}>취소</button><button className="btn primary" disabled={busy} onClick={save}>{busy?'저장 중...':'수정 저장'}</button></div></div></div>}
 </main>;
}
