'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {api} from '../../../lib/api';
const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';
const dt=x=>x?String(x).replace('T',' ').slice(0,19):'-';
export default function AdminMembers(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[items,setItems]=useState([]),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[amount,setAmount]=useState(''),[memo,setMemo]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{const s=data.session||null;setSession(s);setReady(true);if(s?.user?.app_metadata?.role==='admin')load('')})},[]);
 async function load(q=search){try{const r=await api.adminMembers(q);setItems(r.items||[])}catch(e){alert(e.message)}}
 async function openMember(id){try{setSelected(await api.adminMember(id));setAmount('');setMemo('')}catch(e){alert(e.message)}}
 async function adjust(sign){if(!selected)return;const n=Math.floor(Number(amount));if(n<=0)return alert('금액을 입력하세요.');if(!memo.trim())return alert('처리 사유를 입력하세요.');setBusy(true);try{await api.adminAdjustMemberPoints(selected.id,{amount:sign*n,memo:memo.trim()});await openMember(selected.id);await load();alert(sign>0?'포인트를 추가했습니다.':'포인트를 차감했습니다.')}catch(e){const m=String(e.message||'');if(m.includes('INSUFFICIENT'))alert('사용 가능 잔액보다 많이 차감할 수 없습니다.');else alert(m)}finally{setBusy(false)}}
 if(!ready)return <main className="content"><section className="card">권한 확인 중...</section></main>;
 if(session?.user?.app_metadata?.role!=='admin')return <main className="content"><section className="card">관리자 권한이 없습니다.</section></main>;
 return <main className="content" style={{maxWidth:1350,margin:'0 auto'}}><div className="head"><div><h1>회원 관리</h1><p>회원 정보, 포인트 잔액, 충전내역을 확인하고 수동 포인트를 조정합니다.</p></div></div>
 <section className="card"><div style={{display:'flex',gap:8}}><input className="input" style={{flex:1}} value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="이메일 / 회원 ID / 닉네임 검색"/><button className="btn primary" onClick={()=>load()}>검색</button><button className="btn" onClick={()=>{setSearch('');load('')}}>전체</button></div><div className="table" style={{marginTop:14}}><table><thead><tr><th>이메일</th><th>가입일</th><th>최근접속</th><th>권한</th><th>추천코드</th><th>사용가능</th><th>에스크로</th><th>정산</th><th></th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td>{x.email||'-'}</td><td>{dt(x.created_at)}</td><td>{dt(x.last_sign_in_at)}</td><td>{x.role}</td><td>{x.referral_code||'-'}</td><td>{fmt(x.wallet?.available_balance)}</td><td>{fmt(x.wallet?.escrow_balance)}</td><td>{fmt(x.wallet?.settlement_balance)}</td><td><button className="btn" onClick={()=>openMember(x.id)}>관리</button></td></tr>):<tr><td colSpan="9" className="empty">회원이 없습니다.</td></tr>}</tbody></table></div></section>
 {selected&&<section className="card" style={{marginTop:14}}><div className="head"><div><h2>{selected.email||selected.id}</h2><p>{selected.id}</p></div><button className="btn" onClick={()=>setSelected(null)}>닫기</button></div><div className="stats"><div className="stat"><small>사용 가능</small><strong>{fmt(selected.wallet?.available_balance)}</strong></div><div className="stat"><small>에스크로</small><strong>{fmt(selected.wallet?.escrow_balance)}</strong></div><div className="stat"><small>판매 정산</small><strong>{fmt(selected.wallet?.settlement_balance)}</strong></div></div><div className="form" style={{marginTop:16}}><label className="field"><span>수동 조정 금액</span><input className="input" type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="예: 10000"/></label><label className="field"><span>처리 사유</span><input className="input" value={memo} onChange={e=>setMemo(e.target.value)} placeholder="예: 이벤트 지급 / 오류 정정"/></label></div><div className="actions"><button className="btn primary" disabled={busy} onClick={()=>adjust(1)}>+ 포인트 추가</button><button className="btn" disabled={busy} onClick={()=>adjust(-1)}>- 포인트 차감</button></div><div className="table" style={{marginTop:16}}><table><thead><tr><th>일시</th><th>구분</th><th>변동</th><th>이후잔액</th><th>내용</th></tr></thead><tbody>{selected.ledger?.length?selected.ledger.slice(0,30).map(x=><tr key={x.id}><td>{dt(x.created_at)}</td><td>{x.entry_type}</td><td>{Number(x.amount).toLocaleString()}P</td><td>{fmt(x.balance_after)}</td><td>{x.memo||'-'}</td></tr>):<tr><td colSpan="5" className="empty">원장 내역이 없습니다.</td></tr>}</tbody></table></div></section>}
 </main>;
}
