'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {api} from '../../../lib/api';
const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';
const dt=x=>x?String(x).replace('T',' ').slice(0,19):'-';
export default function AdminMembers(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[items,setItems]=useState([]),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[amount,setAmount]=useState(''),[memo,setMemo]=useState(''),[busy,setBusy]=useState(false);
 const [entitlements,setEntitlements]=useState(null),[bannerSlot,setBannerSlot]=useState('1'),[grantBusy,setGrantBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{const s=data.session||null;setSession(s);setReady(true);if(s?.user?.app_metadata?.role==='admin')load('')})},[]);
 async function load(q=search){try{const r=await api.adminMembers(q);setItems(r.items||[])}catch(e){alert(e.message)}}
 async function openMember(id){try{const [m,e]=await Promise.all([api.adminMember(id),api.adminMemberEntitlements(id)]);setSelected(m);setEntitlements(e);setAmount('');setMemo('');setBannerSlot(String(e.banner_slot_count>0?1:1))}catch(e){alert(e.message)}}
 async function refreshSelected(){if(!selected)return;const [m,e]=await Promise.all([api.adminMember(selected.id),api.adminMemberEntitlements(selected.id)]);setSelected(m);setEntitlements(e);await load()}
 async function adjust(sign){if(!selected)return;const n=Math.floor(Number(amount));if(n<=0)return alert('금액을 입력하세요.');if(!memo.trim())return alert('처리 사유를 입력하세요.');setBusy(true);try{await api.adminAdjustMemberPoints(selected.id,{amount:sign*n,memo:memo.trim()});await openMember(selected.id);await load();alert(sign>0?'포인트를 추가했습니다.':'포인트를 차감했습니다.')}catch(e){const m=String(e.message||'');if(m.includes('INSUFFICIENT'))alert('사용 가능 잔액보다 많이 차감할 수 없습니다.');else alert(m)}finally{setBusy(false)}}
 async function grantVip(days){if(!selected)return;if(!confirm(`${selected.email||selected.id} 회원에게 VIP 판매자 ${days}일 이용권을 지급할까요?\n포인트는 차감되지 않습니다.`))return;setGrantBusy(true);try{const r=await api.adminGrantVip(selected.id,days);await refreshSelected();alert(`VIP 판매자 ${days}일 지급 완료\n만료일: ${dt(r.vip_until)}`)}catch(e){const m=String(e.message||'');if(m.includes('SELLER_PROFILE_REQUIRED'))alert('판매자 등록 이력이 없는 회원입니다. 먼저 판매자 등록 후 지급하세요.');else alert(m)}finally{setGrantBusy(false)}}
 async function grantBanner(days){if(!selected)return;const slot=Number(bannerSlot);if(!slot)return alert('광고 슬롯을 선택하세요.');if(!confirm(`${selected.email||selected.id} 회원에게 광고슬롯 #${slot} ${days}일 이용권을 지급할까요?\n포인트는 차감되지 않습니다.`))return;setGrantBusy(true);try{const r=await api.adminGrantBanner(selected.id,slot,days);await refreshSelected();alert(`광고슬롯 #${slot} ${days}일 지급 완료\n만료일: ${dt(r.expires_at)}`)}catch(e){const m=String(e.message||'');if(m.includes('BANNER_SLOT_OCCUPIED'))alert('현재 다른 회원이 이용 중인 광고 슬롯입니다.');else if(m.includes('BANNER_LIMIT_2'))alert('해당 회원은 이미 최대 2개의 광고 슬롯을 이용 중입니다.');else alert(m)}finally{setGrantBusy(false)}}
 if(!ready)return <main className="content"><section className="card">권한 확인 중...</section></main>;
 if(session?.user?.app_metadata?.role!=='admin')return <main className="content"><section className="card">관리자 권한이 없습니다.</section></main>;
 return <main className="content" style={{maxWidth:1350,margin:'0 auto'}}><div className="head"><div><h1>회원 관리</h1><p>회원 정보, 포인트 잔액, 충전내역을 확인하고 수동 포인트 및 이용권을 지급합니다.</p></div></div>
 <section className="card"><div style={{display:'flex',gap:8}}><input className="input" style={{flex:1}} value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="이메일 / 회원 ID / 닉네임 검색"/><button className="btn primary" onClick={()=>load()}>검색</button><button className="btn" onClick={()=>{setSearch('');load('')}}>전체</button></div><div className="table" style={{marginTop:14}}><table><thead><tr><th>이메일</th><th>가입일</th><th>최근접속</th><th>권한</th><th>추천코드</th><th>사용가능</th><th>에스크로</th><th>정산</th><th></th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td>{x.email||'-'}</td><td>{dt(x.created_at)}</td><td>{dt(x.last_sign_in_at)}</td><td>{x.role}</td><td>{x.referral_code||'-'}</td><td>{fmt(x.wallet?.available_balance)}</td><td>{fmt(x.wallet?.escrow_balance)}</td><td>{fmt(x.wallet?.settlement_balance)}</td><td><button className="btn" onClick={()=>openMember(x.id)}>관리</button></td></tr>):<tr><td colSpan="9" className="empty">회원이 없습니다.</td></tr>}</tbody></table></div></section>
 {selected&&<><section className="card" style={{marginTop:14}}><div className="head"><div><h2>{selected.email||selected.id}</h2><p>{selected.id}</p></div><button className="btn" onClick={()=>{setSelected(null);setEntitlements(null)}}>닫기</button></div><div className="stats"><div className="stat"><small>사용 가능</small><strong>{fmt(selected.wallet?.available_balance)}</strong></div><div className="stat"><small>에스크로</small><strong>{fmt(selected.wallet?.escrow_balance)}</strong></div><div className="stat"><small>판매 정산</small><strong>{fmt(selected.wallet?.settlement_balance)}</strong></div></div><div className="form" style={{marginTop:16}}><label className="field"><span>수동 조정 금액</span><input className="input" type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="예: 10000"/></label><label className="field"><span>처리 사유</span><input className="input" value={memo} onChange={e=>setMemo(e.target.value)} placeholder="예: 이벤트 지급 / 오류 정정"/></label></div><div className="actions"><button className="btn primary" disabled={busy} onClick={()=>adjust(1)}>+ 포인트 추가</button><button className="btn" disabled={busy} onClick={()=>adjust(-1)}>- 포인트 차감</button></div></section>
 <section className="card" style={{marginTop:14}}><div className="head"><div><h2>이용권 지급</h2><p>관리자 지급은 회원 포인트를 차감하지 않으며, 이용 중인 경우 기존 만료일 뒤에 기간이 추가됩니다.</p></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:12}}><div className="card" style={{padding:16}}><b>VIP 판매자 이용권</b><p style={{color:'#8fa8c1',fontSize:12}}>현재 만료일: {dt(entitlements?.vip_until)}{!entitlements?.seller?' · 판매자 등록 필요':''}</p><div className="actions"><button className="btn primary" disabled={grantBusy||!entitlements?.seller} onClick={()=>grantVip(15)}>15일 지급</button><button className="btn primary" disabled={grantBusy||!entitlements?.seller} onClick={()=>grantVip(30)}>1달 지급</button></div></div><div className="card" style={{padding:16}}><b>광고슬롯 이용권</b><div style={{marginTop:10}}><select className="input" value={bannerSlot} onChange={e=>setBannerSlot(e.target.value)}>{Array.from({length:Number(entitlements?.banner_slot_count||0)},(_,i)=><option key={i+1} value={i+1}>광고슬롯 #{i+1}</option>)}</select></div><p style={{color:'#8fa8c1',fontSize:12,marginTop:8}}>현재 이용: {entitlements?.banners?.length?entitlements.banners.map(b=>`#${b.sort_order} (${dt(b.expires_at)})`).join(' / '):'없음'}</p><div className="actions"><button className="btn primary" disabled={grantBusy} onClick={()=>grantBanner(15)}>15일 지급</button><button className="btn primary" disabled={grantBusy} onClick={()=>grantBanner(30)}>1달 지급</button></div></div></div></section>
 <section className="card" style={{marginTop:14}}><div className="table"><table><thead><tr><th>일시</th><th>구분</th><th>변동</th><th>이후잔액</th><th>내용</th></tr></thead><tbody>{selected.ledger?.length?selected.ledger.slice(0,30).map(x=><tr key={x.id}><td>{dt(x.created_at)}</td><td>{x.entry_type}</td><td>{Number(x.amount).toLocaleString()}P</td><td>{fmt(x.balance_after)}</td><td>{x.memo||'-'}</td></tr>):<tr><td colSpan="5" className="empty">원장 내역이 없습니다.</td></tr>}</tbody></table></div></section></>}
 </main>;
}
