'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {api} from '../../../lib/api';
const dt=x=>x?String(x).replace('T',' ').slice(0,19):'-';
export default function AdminUsdt(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[data,setData]=useState(null),[address,setAddress]=useState(''),[enabled,setEnabled]=useState(true),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{const s=data.session||null;setSession(s);setReady(true);if(s?.user?.app_metadata?.role==='admin')load()})},[]);
 async function load(){try{const r=await api.adminUsdtAutocharge();setData(r);setEnabled(r.settings?.usdt_autocharge_enabled!==false)}catch(e){alert(e.message)}}
 async function add(){if(!address.trim())return;setBusy(true);try{await api.adminAddUsdtAddress(address.trim());setAddress('');await load();alert('입금주소를 등록했습니다.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function save(){setBusy(true);try{await api.adminUsdtSettings({usdt_autocharge_enabled:enabled});await load();alert('USDT 자동충전 설정을 저장했습니다.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function refreshRate(){setBusy(true);try{const r=await api.adminRefreshUsdtRate();await load();alert(`Google 환율을 갱신했습니다.\n1 USDT = ${Number(r.usdt_krw_rate||0).toLocaleString()}P`)}catch(e){alert(e.message)}finally{setBusy(false)}}
 if(!ready)return <main className="content"><section className="card">권한 확인 중...</section></main>;
 if(session?.user?.app_metadata?.role!=='admin')return <main className="content"><section className="card">관리자 권한이 없습니다.</section></main>;
 const addresses=data?.addresses||[],deposits=data?.deposits||[],st=data?.settings||{};
 return <main className="content" style={{maxWidth:1200,margin:'0 auto'}}><div className="head"><div><h1>USDT 자동충전 관리</h1><p>회원별 TRC20 입금주소와 Google 환율 기반 자동 포인트 충전을 관리합니다.</p></div><button className="btn" onClick={load}>새로고침</button></div>
 <section className="card"><h2>자동충전 설정</h2><div className="stats" style={{marginTop:12}}><div className="stat"><small>환율 기준</small><strong>Google Sheet</strong></div><div className="stat"><small>현재 1 USDT</small><strong>{Number(st.usdt_krw_rate||0).toLocaleString()} P</strong></div><div className="stat"><small>마지막 갱신</small><strong style={{fontSize:14}}>{dt(st.usdt_fx_last_updated_at)}</strong></div></div>{st.usdt_fx_last_error&&<div className="note" style={{marginTop:10,color:'#ff9eaa'}}>최근 환율 조회 오류: {st.usdt_fx_last_error}</div>}<div className="form" style={{marginTop:14}}><label className="field"><span>자동충전 상태</span><select className="input" value={enabled?'ON':'OFF'} onChange={e=>setEnabled(e.target.value==='ON')}><option value="ON">사용</option><option value="OFF">중지</option></select></label></div><div className="actions"><button className="btn" disabled={busy} onClick={refreshRate}>Google 환율 즉시 갱신</button><button className="btn primary" disabled={busy} onClick={save}>설정 저장</button></div><div className="note" style={{marginTop:10}}>환율은 5분마다 자동 갱신됩니다. Google Sheet 조회가 일시 실패하면 마지막 정상 환율을 계속 사용합니다.</div></section>
 <section className="card" style={{marginTop:14}}><h2>TRC20 입금주소 풀</h2><div className="note">개인키/시드가 아닌 공개 주소만 등록합니다. 회원이 자동충전 화면을 처음 열면 미배정 주소가 하나 자동 할당됩니다.</div><div style={{display:'flex',gap:8,marginTop:12}}><input className="input" style={{flex:1}} value={address} onChange={e=>setAddress(e.target.value)} placeholder="T로 시작하는 TRON 주소"/><button className="btn primary" disabled={busy} onClick={add}>주소 등록</button></div><div className="table" style={{marginTop:14}}><table><thead><tr><th>주소</th><th>상태</th><th>배정회원</th><th>배정일</th></tr></thead><tbody>{addresses.length?addresses.map(x=><tr key={x.id}><td style={{fontFamily:'monospace'}}>{x.address}</td><td>{x.user_id?'배정됨':'미배정'}</td><td>{x.user_id||'-'}</td><td>{dt(x.assigned_at)}</td></tr>):<tr><td colSpan="4" className="empty">등록된 입금주소가 없습니다.</td></tr>}</tbody></table></div></section>
 <section className="card" style={{marginTop:14}}><h2>최근 자동충전 내역</h2><div className="table"><table><thead><tr><th>시간</th><th>회원</th><th>주소</th><th>USDT</th><th>환율</th><th>환산</th><th>TXID</th></tr></thead><tbody>{deposits.length?deposits.map(x=><tr key={x.id}><td>{dt(x.credited_at||x.detected_at)}</td><td>{x.user_id}</td><td>{String(x.address).slice(0,10)}...</td><td>{Number(x.amount_usdt).toLocaleString()}</td><td>{Number(x.krw_rate||0).toLocaleString()}</td><td>{Number(x.credit_points).toLocaleString()}P</td><td style={{fontFamily:'monospace'}}>{String(x.txid).slice(0,16)}...</td></tr>):<tr><td colSpan="7" className="empty">자동충전 내역이 없습니다.</td></tr>}</tbody></table></div></section></main>;
}
