'use client';
import {useEffect,useMemo,useState} from 'react';
import {api} from '../lib/api';
import {supabase} from '../lib/supabase';

const TABS=[['send','메시지 발송'],['accounts','Telegram 계정'],['database','DB 관리'],['live','실시간 작업 로그'],['history','작업 이력'],['settings','설정']];
const Badge=({value})=>{const v=String(value||'-').toUpperCase();const c=['READY','SENT','RUNNING','RESOLVED','COMPLETED'].includes(v)?'ok':['FAILED','FROZEN','STOPPED'].includes(v)?'err':['WAITING','PROCESSING','PAUSED','CHECK_REQUIRED'].includes(v)?'wait':'';return <span className={'badge '+c}>{v}</span>};
const Field=({label,children,full})=><label className={'field '+(full?'full':'')}><span>{label}</span>{children}</label>;

export default function Home(){
 const [authReady,setAuthReady]=useState(false),[session,setSession]=useState(null),[authMode,setAuthMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authBusy,setAuthBusy]=useState(false);
 const USER=session?.user?.id||'';
 const [tab,setTab]=useState('send'),[worker,setWorker]=useState('checking'),[apiError,setApiError]=useState(''),[accounts,setAccounts]=useState([]),[batches,setBatches]=useState([]),[jobs,setJobs]=useState([]),[targets,setTargets]=useState([]),[events,setEvents]=useState([]),[selectedJob,setSelectedJob]=useState('');
 const [text,setText]=useState('안내드릴 내용이 있습니다. 아래 버튼을 눌러 확인해주세요.'),[buttonText,setButtonText]=useState('확인하기'),[buttonUrl,setButtonUrl]=useState('https://example.com'),[botToken,setBotToken]=useState(''),[botUser,setBotUser]=useState(''),[batchId,setBatchId]=useState(''),[delayMin,setDelayMin]=useState('2'),[delayMax,setDelayMax]=useState('5'),[globalDedupe,setGlobalDedupe]=useState(true),[filter,setFilter]=useState('ALL');
 const [modal,setModal]=useState(false),[connect,setConnect]=useState({api_id:'',api_hash:'',phone:'',code:'',password:'',challenge_id:''});
 const [bulkModal,setBulkModal]=useState(false),[bulkApiId,setBulkApiId]=useState(''),[bulkApiHash,setBulkApiHash]=useState(''),[bulkFiles,setBulkFiles]=useState(null),[bulkBusy,setBulkBusy]=useState(false);
 const [proxyModal,setProxyModal]=useState(false),[proxyAccount,setProxyAccount]=useState(null),[proxyUrl,setProxyUrl]=useState('');
 const [selectedBatch,setSelectedBatch]=useState(''),[batchContacts,setBatchContacts]=useState([]),[checkedContacts,setCheckedContacts]=useState([]),[batchBusy,setBatchBusy]=useState(false);
 const [chatModal,setChatModal]=useState(false),[chatAccount,setChatAccount]=useState(null),[dialogs,setDialogs]=useState([]),[selectedDialog,setSelectedDialog]=useState(null),[messages,setMessages]=useState([]),[chatBusy,setChatBusy]=useState(false);

 async function reload(){
   try{await api.health();setWorker('online')}catch(e){setWorker('offline');setApiError(`HEALTH: ${e.message}`);return}
   try{
     const [a,b,j]=await Promise.all([api.accounts(),api.batches(),api.jobs()]);
     setAccounts(a.items||[]);setBatches(b.items||[]);setJobs(j.items||[]);setApiError('');
     if(!batchId&&b.items?.[0])setBatchId(String(b.items[0].id));
     if(!selectedJob&&j.items?.[0])setSelectedJob(String(j.items[0].id));
   }catch(e){setApiError(e.message||String(e))}
 }

 useEffect(()=>{
   let mounted=true;
   supabase.auth.getSession().then(({data})=>{if(mounted){setSession(data.session||null);setAuthReady(true)}});
   const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next||null);setAuthReady(true)});
   return()=>{mounted=false;subscription.unsubscribe()};
 },[]);

 useEffect(()=>{if(!USER)return;reload();const i=setInterval(reload,6000);return()=>clearInterval(i)},[USER]);
 useEffect(()=>{if(!USER||!selectedJob)return;const f=async()=>{try{const [t,l]=await Promise.all([api.targets(selectedJob),api.logs(selectedJob)]);setTargets(t.items||[]);setEvents(l.items||[])}catch{}};f();const i=setInterval(f,1500);return()=>clearInterval(i)},[USER,selectedJob]);
 useEffect(()=>{if(!USER)return;const ch=supabase.channel(`hub24-${USER}`).on('postgres_changes',{event:'*',schema:'public',table:'jobs',filter:`user_id=eq.${USER}`},()=>reload()).on('postgres_changes',{event:'*',schema:'public',table:'job_targets',filter:`user_id=eq.${USER}`},()=>{if(selectedJob)api.targets(selectedJob).then(r=>setTargets(r.items||[])).catch(()=>{})}).on('postgres_changes',{event:'INSERT',schema:'public',table:'job_logs',filter:`user_id=eq.${USER}`},payload=>{if(!selectedJob||String(payload.new.job_id)!==String(selectedJob))return;setEvents(prev=>[...prev,payload.new].slice(-300))}).subscribe();return()=>{supabase.removeChannel(ch)}},[USER,selectedJob]);

 async function submitAuth(){if(!email||!password)return alert('이메일과 비밀번호를 입력하세요.');setAuthBusy(true);try{if(authMode==='login'){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}else{const {error}=await supabase.auth.signUp({email,password});if(error)throw error;alert('회원가입 요청이 완료되었습니다. 이메일 인증 설정에 따라 확인 후 로그인하세요.')}}catch(e){alert(e.message)}finally{setAuthBusy(false)}}
 async function logout(){await supabase.auth.signOut()}
 const stats=useMemo(()=>({accounts:accounts.length,ready:accounts.filter(x=>x.status==='READY').length,running:jobs.filter(x=>x.status==='RUNNING').length,sent:jobs.reduce((s,x)=>s+(x.sent_count||0),0)}),[accounts,jobs]);
 const current=jobs.find(x=>String(x.id)===String(selectedJob));
 const visible=targets.filter(x=>filter==='ALL'||String(x.state).toUpperCase()===filter);
 const detailBatch=batches.find(x=>String(x.id)===String(selectedBatch));

 async function upload(e){const f=e.target.files?.[0];if(!f)return;try{const r=await api.uploadBatch(f);alert(`DB 등록 완료: ${r.total_count}건 / 중복제거 ${r.duplicate_count}건`);await reload();setBatchId(String(r.id))}catch(e){alert(e.message)}}
 async function startJob(){if(worker!=='online')return alert('Worker가 연결되어 있지 않습니다.');if(!batchId||!text||!buttonText||!buttonUrl||!botToken||!botUser)return alert('DB/본문/버튼/Bot 설정을 확인하세요.');try{const j=await api.createJob({batch_id:Number(batchId),operation_mode:'CONTACT_AND_SEND',message_text:text,button_text:buttonText,button_url:buttonUrl,bot_username:botUser.replace(/^@/,''),bot_token:botToken,delay_min:Number(delayMin),delay_max:Number(delayMax),global_dedupe:globalDedupe});await api.startJob(j.id);setSelectedJob(String(j.id));setTab('live');await reload()}catch(e){alert(e.message)}}
 async function connectStart(){try{const r=await api.connectStart({api_id:Number(connect.api_id),api_hash:connect.api_hash,phone:connect.phone,proxy_url:null,label:connect.phone});setConnect({...connect,challenge_id:r.challenge_id})}catch(e){alert(e.message)}}
 async function connectVerify(){try{await api.connectVerify({challenge_id:connect.challenge_id,code:connect.code,password:connect.password||null});setModal(false);setConnect({api_id:'',api_hash:'',phone:'',code:'',password:'',challenge_id:''});await reload()}catch(e){alert(e.message)}}
 async function bulkUpload(){if(!bulkApiId||!bulkApiHash||!bulkFiles?.length)return alert('API ID / API HASH / SESSION 파일을 확인하세요.');setBulkBusy(true);try{const r=await api.uploadSessions(bulkFiles,bulkApiId,bulkApiHash);alert(`SESSION 일괄등록 완료\n성공 ${r.success_count}개 / 실패 ${r.failed_count}개`);setBulkModal(false);setBulkFiles(null);await reload()}catch(e){alert(e.message)}finally{setBulkBusy(false)}}
 async function saveProxy(){if(!proxyAccount)return;try{await api.updateProxy(proxyAccount.id,proxyUrl||null);setProxyModal(false);setProxyAccount(null);setProxyUrl('');await reload();alert('프록시 설정을 저장했습니다. 상태확인으로 연결 상태를 확인하세요.')}catch(e){alert(e.message)}}
 async function jobAction(name){if(!current)return;try{const r=await api[name](current.id);if(name==='resetProcessing')alert(`진행중 초기화: ${r.reset_count||0}건`);if(name==='reassignJob')alert(`대기 대상 재배정: ${r.reassigned||0}건`);await reload();const [t,l]=await Promise.all([api.targets(current.id),api.logs(current.id)]);setTargets(t.items||[]);setEvents(l.items||[])}catch(e){alert(e.message)}}
 async function openBatch(id){setSelectedBatch(String(id));setCheckedContacts([]);setBatchBusy(true);try{const r=await api.batchContacts(id);setBatchContacts(r.items||[])}catch(e){alert(e.message)}finally{setBatchBusy(false)}}
 async function deleteSelectedContacts(){if(!selectedBatch||!checkedContacts.length)return; if(!confirm(`선택한 ${checkedContacts.length}개 연락처를 삭제할까요?`))return;try{await api.deleteBatchContacts(selectedBatch,checkedContacts);await openBatch(selectedBatch);await reload()}catch(e){alert(e.message)}}
 async function deleteAllContacts(){if(!selectedBatch||!confirm('이 DB의 연락처를 전체 삭제할까요?'))return;try{await api.deleteAllBatchContacts(selectedBatch);await openBatch(selectedBatch);await reload()}catch(e){alert(e.message)}}
 async function removeBatch(id){if(!confirm('이 DB를 삭제할까요? 작업에 사용된 DB는 삭제되지 않습니다.'))return;try{await api.deleteBatch(id);if(String(selectedBatch)===String(id)){setSelectedBatch('');setBatchContacts([])}await reload()}catch(e){alert(e.message)}}
 async function openChats(a){setChatAccount(a);setChatModal(true);setDialogs([]);setMessages([]);setSelectedDialog(null);setChatBusy(true);try{const r=await api.dialogs(a.id);setDialogs(r.items||[])}catch(e){alert(e.message)}finally{setChatBusy(false)}}
 async function openDialog(d){setSelectedDialog(d);setChatBusy(true);try{const r=await api.messages(chatAccount.id,d.id);setMessages(r.items||[])}catch(e){alert(e.message)}finally{setChatBusy(false)}}

 if(!authReady)return <div className="authPage"><div className="authCard"><h1>HUB24 <span>MESSAGE</span></h1><p>로그인 상태 확인 중...</p></div></div>;
 if(!session)return <div className="authPage"><div className="authCard"><h1>HUB24 <span>MESSAGE</span></h1><p>사용자별 독립 Telegram 작업공간</p><div className="authTabs"><button className={authMode==='login'?'active':''} onClick={()=>setAuthMode('login')}>로그인</button><button className={authMode==='signup'?'active':''} onClick={()=>setAuthMode('signup')}>회원가입</button></div><label className="field"><span>이메일</span><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>비밀번호</span><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submitAuth()}/></label><button className="btn primary authSubmit" disabled={authBusy} onClick={submitAuth}>{authBusy?'처리중...':authMode==='login'?'로그인':'회원가입'}</button><div className="note">로그인 사용자별 SESSION · DB · JOB · 로그가 분리됩니다.</div></div></div>;

 return <div className="shell"><aside className="sidebar"><div className="brand">HUB24 <span>MESSAGE</span></div><div className="sub">Multi-user Web Control</div><div className="nav">{TABS.map(([k,n])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{n}</button>)}</div><div className="userBox"><small>현재 사용자</small><b>{session?.user?.email||'-'}</b><span>데이터/SESSION 독립</span><button className="link" onClick={logout}>로그아웃</button></div></aside><main className="content">
 <header className="top"><div><h1>HUB24 MESSAGE</h1><p>사용자별 Telegram API · SESSION · DB · JOB</p>{apiError&&<p className="apiError">API ERROR: {apiError}</p>}</div><div className={'worker '+worker}>● Worker {worker.toUpperCase()}</div></header>
 <div className="stats">{[['등록 SESSION',stats.accounts],['READY',stats.ready],['진행 작업',stats.running],['누적 성공',stats.sent]].map(([l,n])=><div className="stat" key={l}><small>{l}</small><strong>{n}</strong></div>)}</div>
 {tab==='send'&&<div className="two"><section className="card"><h2>새 발송 작업</h2><div className="form"><Field label="발송 DB"><select className="input" value={batchId} onChange={e=>setBatchId(e.target.value)}><option value="">DB 선택</option>{batches.map(b=><option key={b.id} value={b.id}>{b.name} · {b.total_count}건</option>)}</select></Field><Field label="작업 방식"><select className="input" disabled><option>연락처 추가 + 발송</option></select></Field><Field full label="본문 텍스트"><textarea className="textarea" value={text} onChange={e=>setText(e.target.value)}/></Field><Field label="버튼명"><input className="input" value={buttonText} onChange={e=>setButtonText(e.target.value)}/></Field><Field label="버튼 URL"><input className="input" value={buttonUrl} onChange={e=>setButtonUrl(e.target.value)}/></Field><Field label="Bot Token"><input type="password" className="input" value={botToken} onChange={e=>setBotToken(e.target.value)}/></Field><Field label="@Bot"><input className="input" value={botUser} onChange={e=>setBotUser(e.target.value)}/></Field><Field label="최소 간격"><input className="input" value={delayMin} onChange={e=>setDelayMin(e.target.value)}/></Field><Field label="최대 간격"><input className="input" value={delayMax} onChange={e=>setDelayMax(e.target.value)}/></Field></div><label className="check"><input type="checkbox" checked={globalDedupe} onChange={e=>setGlobalDedupe(e.target.checked)}/> 전화번호/Telegram UID 전체 성공이력 중복 방지</label><div className="actions"><button className="btn primary" onClick={startJob}>발송 시작</button><button className="btn" onClick={()=>setTab('live')}>실시간 작업 로그</button></div><div className="note">Telegram rate-limit/frozen 감지 시 전체 작업을 중지합니다. 자동 계정교체·제한 우회·자동 재시도는 사용하지 않습니다.</div></section><section className="card"><h2>미리보기</h2><div className="phone"><div className="tg">Telegram</div><div className="bubble">{text}<button>{buttonText}</button></div></div><label className="drop"><b>DB 업로드</b><input type="file" accept=".xlsx,.xlsm,.csv,.txt" onChange={upload}/><span>Excel / CSV / TXT · 번호 정규화 · 중복 제거</span></label></section></div>}
 {tab==='accounts'&&<section className="card"><div className="head"><div><h2>Telegram 계정</h2><p>개별 연결 또는 로그인된 SESSION 파일 일괄등록</p></div><div className="actions compact"><button className="btn" onClick={()=>setBulkModal(true)}>SESSION 일괄등록</button><button className="btn primary" onClick={()=>setModal(true)}>+ 계정 연결</button></div></div><div className="table"><table><thead><tr><th>ID</th><th>라벨</th><th>전화번호</th><th>상태</th><th>프록시</th><th>성공</th><th>최근 확인</th><th>관리</th></tr></thead><tbody>{accounts.length?accounts.map(a=><tr key={a.id}><td>#{a.id}</td><td>{a.label}</td><td>{a.phone_masked}</td><td><Badge value={a.status}/></td><td>{a.proxy_enabled?'사용':'미사용'}</td><td>{a.sent_count||0}</td><td>{a.last_check_at||'-'}</td><td className="nowrap"><button className="link" onClick={()=>api.refreshAccount(a.id).then(reload).catch(e=>alert(e.message))}>상태확인</button> <button className="link" onClick={()=>{setProxyAccount(a);setProxyUrl('');setProxyModal(true)}}>프록시 설정</button> <button className="link" onClick={()=>openChats(a)}>대화보기</button> <button className="link red" onClick={()=>confirm('삭제할까요?')&&api.deleteAccount(a.id).then(reload).catch(e=>alert(e.message))}>삭제</button></td></tr>):<tr><td colSpan="8" className="empty">연결된 SESSION이 없습니다.</td></tr>}</tbody></table></div></section>}
 {tab==='database'&&<><section className="card"><div className="head"><div><h2>DB 관리</h2><p>업로드 · 상세보기 · 선택삭제 · 전체삭제</p></div><label className="btn primary">+ DB 업로드<input hidden type="file" accept=".xlsx,.xlsm,.csv,.txt" onChange={upload}/></label></div><div className="batches">{batches.map(b=><div className={'batch '+(String(selectedBatch)===String(b.id)?'selected':'')} key={b.id}><b>{b.name}</b><strong>{b.total_count}건</strong><span>중복 제거 {b.duplicate_count||0}</span><div className="actions compact"><button className="btn" onClick={()=>openBatch(b.id)}>상세보기</button><button className="btn" onClick={()=>{setBatchId(String(b.id));setTab('send')}}>이 DB로 작업</button><button className="btn danger" onClick={()=>removeBatch(b.id)}>DB 삭제</button></div></div>)}{!batches.length&&<div className="empty">등록된 DB가 없습니다.</div>}</div></section>{selectedBatch&&<section className="card detailCard"><div className="head"><div><h2>{detailBatch?.name||'DB'} 상세</h2><p>현재 {batchContacts.length}건 표시</p></div><div className="actions compact"><button className="btn" onClick={()=>setCheckedContacts(checkedContacts.length===batchContacts.length?[]:batchContacts.map(x=>String(x.id)))}>{checkedContacts.length===batchContacts.length?'전체선택 해제':'전체선택'}</button><button className="btn danger" disabled={!checkedContacts.length} onClick={deleteSelectedContacts}>선택삭제 ({checkedContacts.length})</button><button className="btn danger" onClick={deleteAllContacts}>연락처 전체삭제</button></div></div>{batchBusy?<div className="empty">불러오는 중...</div>:<div className="table tall"><table><thead><tr><th><input type="checkbox" checked={batchContacts.length>0&&checkedContacts.length===batchContacts.length} onChange={()=>setCheckedContacts(checkedContacts.length===batchContacts.length?[]:batchContacts.map(x=>String(x.id)))}/></th><th>#</th><th>전화번호</th><th>Telegram UID</th><th>상태</th><th>상세</th><th>등록일</th></tr></thead><tbody>{batchContacts.length?batchContacts.map((c,i)=><tr key={c.id}><td><input type="checkbox" checked={checkedContacts.includes(String(c.id))} onChange={e=>setCheckedContacts(v=>e.target.checked?[...v,String(c.id)]:v.filter(x=>x!==String(c.id)))}/></td><td>{i+1}</td><td>{c.phone_display||c.phone}</td><td>{c.telegram_user_id||'-'}</td><td><Badge value={c.state||'NEW'}/></td><td>{c.detail||'-'}</td><td>{c.created_at||'-'}</td></tr>):<tr><td colSpan="7" className="empty">등록된 연락처가 없습니다.</td></tr>}</tbody></table></div>}</section>}</>}
 {tab==='live'&&<><section className="card summary"><div className="head"><div><h2>실시간 작업 로그</h2><p>대상 처리 현황과 Worker 로그를 자동 갱신</p></div><select className="input job" value={selectedJob} onChange={e=>setSelectedJob(e.target.value)}><option value="">JOB 선택</option>{jobs.map(j=><option key={j.id} value={j.id}>JOB #{j.id} · {j.status}</option>)}</select></div>{current&&<><div className="jobstats"><b>JOB #{current.id}</b><Badge value={current.status}/><span>전체 {current.total_count||0}</span><span className="green">성공 {current.sent_count||0}</span><span className="redText">실패 {current.failed_count||0}</span><span>대기 {current.pending_count||0}</span></div><div className="progress"><i style={{width:`${current.total_count?Math.round(((current.sent_count||0)+(current.failed_count||0))/current.total_count*100):0}%`}}/></div><div className="actions"><button className="btn primary" onClick={()=>jobAction('startJob')}>시작/재개</button><button className="btn" onClick={()=>jobAction('pauseJob')}>일시정지</button><button className="btn danger" onClick={()=>jobAction('stopJob')}>중지</button><button className="btn" onClick={()=>jobAction('resetProcessing')}>진행중 초기화</button><button className="btn" onClick={()=>jobAction('reassignJob')}>대기 재배정</button></div></>}</section><div className="live"><section className="card"><div className="head"><h2>대상 리스트</h2><div className="filters">{['ALL','WAITING','PROCESSING','SENT','FAILED','CHECK_REQUIRED'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="table tall"><table><thead><tr><th>#</th><th>전화번호</th><th>SESSION</th><th>UID</th><th>단계</th><th>상태</th><th>상세</th></tr></thead><tbody>{visible.length?visible.map((t,i)=><tr key={t.id}><td>{i+1}</td><td>{t.phone_display||t.phone}</td><td>{t.account_label||'-'}</td><td>{t.telegram_user_id||'-'}</td><td>{t.stage||'-'}</td><td><Badge value={t.state}/></td><td>{t.detail||'-'}</td></tr>):<tr><td colSpan="7" className="empty">표시할 대상이 없습니다.</td></tr>}</tbody></table></div></section><section className="card"><h2>Worker 실시간 로그</h2><div className="logs">{events.length?events.map(e=><div className={'log '+String(e.level).toLowerCase()} key={e.id}><time>{e.created_at?.slice(11,19)}</time><b>[{e.account_label||e.scope}]</b><span>{e.message}</span></div>):<div className="empty">로그가 없습니다.</div>}</div></section></div></>}
 {tab==='history'&&<section className="card"><h2>작업 이력</h2><div className="table"><table><thead><tr><th>JOB</th><th>DB</th><th>상태</th><th>전체</th><th>성공</th><th>실패</th><th>생성</th><th></th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td>#{j.id}</td><td>{j.batch_name||j.batch_id}</td><td><Badge value={j.status}/></td><td>{j.total_count||0}</td><td>{j.sent_count||0}</td><td>{j.failed_count||0}</td><td>{j.created_at}</td><td><button className="link" onClick={()=>{setSelectedJob(String(j.id));setTab('live')}}>열기</button></td></tr>)}</tbody></table></div></section>}
 {tab==='settings'&&<div className="two"><section className="card"><h2>사용자 설정</h2><ul className="list"><li>계정/SESSION은 현재 로그인 사용자 기준으로 분리됩니다.</li><li>DB와 작업 이력도 사용자별로 분리됩니다.</li><li>프록시는 Telegram 계정 메뉴에서 계정별로 설정합니다.</li></ul></section><section className="card"><h2>안전 동작</h2><ul className="list"><li>전화번호·UID 성공이력 중복검사</li><li>Rate-limit/Frozen 감지 시 작업 중단</li><li>자동 계정교체·제한 우회·자동 재시도 없음</li></ul></section></div>}
 </main>
 {modal&&<div className="modalBack"><div className="modal"><div className="head"><h2>Telegram 계정 연결</h2><button className="x" onClick={()=>setModal(false)}>×</button></div>{!connect.challenge_id?<div className="form"><Field label="API ID"><input className="input" value={connect.api_id} onChange={e=>setConnect({...connect,api_id:e.target.value})}/></Field><Field label="API HASH"><input type="password" className="input" value={connect.api_hash} onChange={e=>setConnect({...connect,api_hash:e.target.value})}/></Field><Field full label="전화번호"><input className="input" placeholder="+8210..." value={connect.phone} onChange={e=>setConnect({...connect,phone:e.target.value})}/></Field><div className="actions full"><button className="btn primary" onClick={connectStart}>인증코드 요청</button></div></div>:<div className="form"><Field full label="Telegram 인증코드"><input className="input" value={connect.code} onChange={e=>setConnect({...connect,code:e.target.value})}/></Field><Field full label="2단계 인증 비밀번호 (필요 시)"><input type="password" className="input" value={connect.password} onChange={e=>setConnect({...connect,password:e.target.value})}/></Field><div className="actions full"><button className="btn primary" onClick={connectVerify}>SESSION 연결 완료</button></div></div>}</div></div>}
 {bulkModal&&<div className="modalBack"><div className="modal"><div className="head"><div><h2>SESSION 일괄등록</h2><p>로그인 완료된 .session 파일 여러 개를 등록합니다.</p></div><button className="x" onClick={()=>setBulkModal(false)}>×</button></div><div className="form"><Field label="API ID"><input className="input" value={bulkApiId} onChange={e=>setBulkApiId(e.target.value)}/></Field><Field label="API HASH"><input type="password" className="input" value={bulkApiHash} onChange={e=>setBulkApiHash(e.target.value)}/></Field><Field full label="SESSION 파일"><input className="input" type="file" accept=".session" multiple onChange={e=>setBulkFiles(e.target.files)}/></Field><div className="note full">선택한 SESSION은 실제 로그인 상태를 확인한 뒤 정상 파일만 READY 계정으로 등록합니다.</div><div className="actions full"><button className="btn primary" disabled={bulkBusy} onClick={bulkUpload}>{bulkBusy?'검증/등록 중...':'일괄등록'}</button></div></div></div></div>}
 {proxyModal&&<div className="modalBack"><div className="modal"><div className="head"><div><h2>프록시 설정</h2><p>{proxyAccount?.label||'-'}</p></div><button className="x" onClick={()=>setProxyModal(false)}>×</button></div><Field label="Proxy URL"><input className="input" placeholder="socks5://user:pass@host:port" value={proxyUrl} onChange={e=>setProxyUrl(e.target.value)}/></Field><div className="note">빈 값으로 저장하면 해당 계정의 프록시를 해제합니다.</div><div className="actions"><button className="btn primary" onClick={saveProxy}>저장</button></div></div></div>}
 {chatModal&&<div className="modalBack"><div className="modal wide"><div className="head"><div><h2>Telegram 대화보기</h2><p>{chatAccount?.label||'-'} · 최근 대화/메시지 조회</p></div><button className="x" onClick={()=>setChatModal(false)}>×</button></div>{chatBusy&&<div className="note">Telegram에서 내용을 불러오는 중...</div>}<div className="chatGrid"><div className="dialogList">{dialogs.length?dialogs.map(d=><button key={d.id} className={selectedDialog?.id===d.id?'active':''} onClick={()=>openDialog(d)}><b>{d.name||d.id}</b><span>{d.is_user?'개인':d.is_group?'그룹':d.is_channel?'채널':'대화'} · 안읽음 {d.unread_count||0}</span></button>):<div className="empty">대화가 없습니다.</div>}</div><div className="messageList"><div className="messageTitle">{selectedDialog?.name||'대화를 선택하세요'}</div>{messages.length?messages.map(m=><div className={'chatMessage '+(m.out?'out':'in')} key={m.id}><small>{m.date?.replace('T',' ').slice(0,19)}</small><p>{m.text||'(텍스트 없음)'}</p></div>):<div className="empty">표시할 메시지가 없습니다.</div>}</div></div></div></div>}
 </div>;
}
