'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {api} from '../../../lib/api';
const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';
export default function AdminWithdrawals(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[items,setItems]=useState([]),[selected,setSelected]=useState(null),[reference,setReference]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 async function load(){try{const r=await api.adminMarketOverview();setItems(r.withdrawals||[])}catch(e){alert(e.message)}}
 useEffect(()=>{if(session?.user?.app_metadata?.role==='admin')load()},[session]);
 async function resolve(action){if(!selected)return;setBusy(true);try{await api.adminResolveWithdrawal(selected.id,{action,admin_reference:reference.trim()||null,admin_note:note.trim()||null});setSelected(null);setReference('');setNote('');await load();alert('처리되었습니다.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 if(!ready)return <div className="authPage"><div className="authCard">권한 확인 중...</div></div>;
 if(session?.user?.app_metadata?.role!=='admin')return <div className="authPage"><div className="authCard">관리자 권한이 없습니다.</div></div>;
 return <main className="content" style={{maxWidth:1500,margin:'0 auto'}}><div className="head"><div><h1>출금 상세 관리</h1><p>수취정보·지급참조·처리메모를 남긴 뒤 처리합니다.</p></div><button className="btn" onClick={load}>새로고침</button></div><section className="card"><div className="table"><table><thead><tr><th>ID</th><th>금액</th><th>실지급</th><th>방식</th><th>수취정보</th><th>메모</th><th>상태</th><th>처리</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td>#{x.id}</td><td>{fmt(x.requested_amount)}</td><td>{fmt(x.payout_amount)}</td><td>{x.payout_method||'-'}</td><td style={{maxWidth:260,wordBreak:'break-all'}}>{x.payout_details||'-'}</td><td>{x.user_note||'-'}</td><td>{x.status}</td><td>{x.status==='PENDING'?<button className="btn" onClick={()=>{setSelected(x);setReference(x.admin_reference||'');setNote(x.admin_note||'')}}>처리</button>:<span>{x.processed_at?.replace('T',' ').slice(0,16)||'-'}</span>}</td></tr>):<tr><td colSpan="8" className="empty">출금 신청이 없습니다.</td></tr>}</tbody></table></div></section>{selected&&<div className="modalBack"><div className="modal"><div className="head"><div><h2>출금 #{selected.id} 처리</h2><p>{selected.payout_method} · {selected.payout_details}</p></div><button className="x" onClick={()=>setSelected(null)}>×</button></div><label className="field"><span>외부 지급 참고번호 / TXID</span><input className="input" value={reference} onChange={e=>setReference(e.target.value)} placeholder="선택 입력"/></label><label className="field" style={{marginTop:10}}><span>관리자 처리 메모</span><textarea className="textarea" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="actions"><button className="btn danger" disabled={busy} onClick={()=>resolve('REJECT')}>반려·복구</button><button className="btn primary" disabled={busy} onClick={()=>resolve('PAID')}>지급완료</button></div></div></div>}</main>;
}
