import {supabase} from './supabase';

export const BASE=process.env.NEXT_PUBLIC_WORKER_URL||'https://hub24-message-worker.onrender.com';
async function request(path,options={}){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('로그인이 필요합니다.');const res=await fetch(BASE+path,{...options,headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,...(options.headers||{})}});if(!res.ok){let detail='';try{detail=(await res.json()).detail||''}catch{};throw new Error(detail||`HTTP ${res.status}`)}const ct=res.headers.get('content-type')||'';return ct.includes('application/json')?res.json():res.text()}
async function publicRequest(path){const res=await fetch(BASE+path,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);return res.json()}

export const api={
 health:async()=>{const res=await fetch(BASE+'/health');if(!res.ok)throw new Error(`HTTP ${res.status}`);return res.json()},publicSiteSettings:()=>publicRequest('/v1/public/site-settings'),
 accounts:()=>request('/v1/accounts'),connectStart:p=>request('/v1/accounts/connect/start',{method:'POST',body:JSON.stringify(p)}),connectVerify:p=>request('/v1/accounts/connect/verify',{method:'POST',body:JSON.stringify(p)}),deleteAccount:id=>request(`/v1/accounts/${id}`,{method:'DELETE'}),refreshAccount:id=>request(`/v1/accounts/${id}/status`,{method:'POST'}),updateProxy:(id,proxy_url)=>request(`/v1/accounts/${id}/proxy`,{method:'PUT',body:JSON.stringify({proxy_url})}),dialogs:id=>request(`/v1/accounts/${id}/dialogs?limit=100`),messages:(id,peerId)=>request(`/v1/accounts/${id}/dialogs/${peerId}/messages?limit=100`),
 uploadSessions:async(files,apiId,apiHash)=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('로그인이 필요합니다.');const fd=new FormData();[...files].forEach(f=>fd.append('files',f));fd.append('api_id',String(apiId));fd.append('api_hash',apiHash);const res=await fetch(BASE+'/v1/accounts/sessions/upload',{method:'POST',headers:{'Authorization':`Bearer ${session.access_token}`},body:fd});if(!res.ok){let detail='';try{detail=(await res.json()).detail||''}catch{};throw new Error(detail||`HTTP ${res.status}`)}return res.json()},
 uploadBatch:async file=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('로그인이 필요합니다.');const fd=new FormData();fd.append('file',file);const res=await fetch(BASE+'/v1/batches/upload',{method:'POST',headers:{'Authorization':`Bearer ${session.access_token}`},body:fd});if(!res.ok){let detail='';try{detail=(await res.json()).detail||''}catch{};throw new Error(detail||`HTTP ${res.status}`)}return res.json()},
 batches:()=>request('/v1/batches'),batchContacts:id=>request(`/v1/batches/${id}/contacts?limit=5000`),deleteBatchContacts:(id,ids)=>request(`/v1/batches/${id}/contacts/delete`,{method:'POST',body:JSON.stringify({ids})}),deleteAllBatchContacts:id=>request(`/v1/batches/${id}/contacts`,{method:'DELETE'}),deleteBatch:id=>request(`/v1/batches/${id}`,{method:'DELETE'}),
 jobs:()=>request('/v1/jobs'),createJob:p=>request('/v1/jobs',{method:'POST',body:JSON.stringify(p)}),job:id=>request(`/v1/jobs/${id}`),targets:id=>request(`/v1/jobs/${id}/targets?limit=1000`),startJob:id=>request(`/v1/jobs/${id}/start`,{method:'POST'}),pauseJob:id=>request(`/v1/jobs/${id}/pause`,{method:'POST'}),stopJob:id=>request(`/v1/jobs/${id}/stop`,{method:'POST'}),resetProcessing:id=>request(`/v1/jobs/${id}/reset-processing`,{method:'POST'}),reassignJob:id=>request(`/v1/jobs/${id}/reassign`,{method:'POST'}),logs:id=>request(`/v1/jobs/${id}/events?limit=300`),
 communityPosts:(board='FREE')=>request(`/v1/community/posts?board_type=${encodeURIComponent(board)}`),communityPost:id=>request(`/v1/community/posts/${id}`),createCommunityPost:p=>request('/v1/community/posts',{method:'POST',body:JSON.stringify(p)}),addCommunityComment:(id,content)=>request(`/v1/community/posts/${id}/comments`,{method:'POST',body:JSON.stringify({content})}),communityPermissions:()=>request('/v1/community/permissions'),pinCommunityPost:(id,is_pinned)=>request(`/v1/community/posts/${id}/pin`,{method:'PUT',body:JSON.stringify({is_pinned})}),
 referralMe:()=>request('/v1/referrals/me'),referralMembers:()=>request('/v1/referrals/members'),issueReferralCode:code=>request('/v1/referrals/code',{method:'POST',body:JSON.stringify({code})}),referralLeaderboard:()=>request('/v1/referrals/leaderboard'),
 notifications:()=>request('/v1/notifications'),readNotification:id=>request(`/v1/notifications/${id}/read`,{method:'POST'}),readAllNotifications:()=>request('/v1/notifications/read-all',{method:'POST'}),
 bannerSlots:()=>request('/v1/market/banner-slots'),purchaseBannerSlot:(slot,plan)=>request(`/v1/market/banner-slots/${slot}/purchase`,{method:'POST',body:JSON.stringify({plan})}),updateBannerCreative:(slot,p)=>request(`/v1/market/banner-slots/${slot}/creative`,{method:'PUT',body:JSON.stringify(p)}),
 marketCategories:()=>request('/v1/market/categories'),marketBanners:()=>request('/v1/market/banners'),marketSellers:(search='')=>request(`/v1/market/sellers?search=${encodeURIComponent(search)}`),sellerMe:()=>request('/v1/market/seller/me'),sellerApply:p=>request('/v1/market/seller/apply',{method:'POST',body:JSON.stringify(p)}),updateSellerProfile:p=>request('/v1/market/seller/profile',{method:'PUT',body:JSON.stringify(p)}),vipInfo:()=>request('/v1/market/vip-info'),purchaseVip:()=>request('/v1/market/seller/vip',{method:'POST'}),marketProducts:(categoryId='')=>request(`/v1/market/products${categoryId?`?category_id=${categoryId}`:''}`),createProduct:p=>request('/v1/market/products-v2',{method:'POST',body:JSON.stringify(p)}),buyProduct:(id,quantity=1)=>request(`/v1/market/products/${id}/buy`,{method:'POST',body:JSON.stringify({quantity})}),directEscrow:p=>request('/v1/market/direct-escrow',{method:'POST',body:JSON.stringify(p)}),marketTrades:()=>request('/v1/market/trades'),tradeMessages:id=>request(`/v1/market/trades/${id}/messages`),sendTradeMessage:(id,message)=>request(`/v1/market/trades/${id}/messages`,{method:'POST',body:JSON.stringify({message})}),tradeEvidence:id=>request(`/v1/market/trades/${id}/evidence`),addTradeEvidence:(id,p)=>request(`/v1/market/trades/${id}/evidence`,{method:'POST',body:JSON.stringify(p)}),sellerComplete:id=>request(`/v1/market/trades/${id}/seller-complete`,{method:'POST'}),buyerComplete:id=>request(`/v1/market/trades/${id}/buyer-complete`,{method:'POST'}),cancelTrade:id=>request(`/v1/market/trades/${id}/cancel-request`,{method:'POST'}),disputeTrade:id=>request(`/v1/market/trades/${id}/dispute`,{method:'POST'}),
 wallet:()=>request('/v1/wallet'),withdrawals:()=>request('/v1/wallet/withdrawals'),requestWithdrawal:p=>request('/v1/wallet/withdrawals-v2',{method:'POST',body:JSON.stringify(p)}),usdtAutocharge:()=>request('/v1/wallet/usdt-autocharge'),createUsdtCharge:amount=>request('/v1/wallet/usdt-charge-requests',{method:'POST',body:JSON.stringify({amount})}),verifyUsdtCharge:id=>request(`/v1/wallet/usdt-charge-requests/${id}/verify`,{method:'POST'}),
 adminUsdtAutocharge:()=>request('/v1/admin/usdt-autocharge'),adminAddUsdtAddress:address=>request('/v1/admin/usdt-autocharge/addresses',{method:'POST',body:JSON.stringify({address})}),adminUsdtSettings:p=>request('/v1/admin/usdt-autocharge/settings',{method:'PUT',body:JSON.stringify(p)}),adminRefreshUsdtRate:()=>request('/v1/admin/usdt-autocharge/refresh-rate',{method:'POST'}),adminMembers:(search='')=>request(`/v1/admin/members?search=${encodeURIComponent(search)}`),adminMember:id=>request(`/v1/admin/members/${id}`),adminAdjustMemberPoints:(id,p)=>request(`/v1/admin/members/${id}/points`,{method:'POST',body:JSON.stringify(p)}),adminSiteSettings:()=>request('/v1/admin/site-settings'),adminUpdateSiteSettings:p=>request('/v1/admin/site-settings',{method:'PUT',body:JSON.stringify(p)}),adminBroadcasts:()=>request('/v1/admin/broadcasts'),adminSendBroadcast:p=>request('/v1/admin/broadcasts',{method:'POST',body:JSON.stringify(p)}),
 adminMarketOverview:()=>request('/v1/admin/market/overview'),adminAddCategory:p=>request('/v1/admin/market/categories',{method:'POST',body:JSON.stringify(p)}),adminUpdateCategory:(id,p)=>request(`/v1/admin/market/categories/${id}`,{method:'PUT',body:JSON.stringify(p)}),adminMarketSettings:p=>request('/v1/admin/market/settings',{method:'PUT',body:JSON.stringify(p)}),adminVipSettings:p=>request('/v1/admin/market/vip-settings',{method:'PUT',body:JSON.stringify(p)}),adminBannerSlotSettings:banner_slot_count=>request('/v1/admin/market/banner-slot-settings',{method:'PUT',body:JSON.stringify({banner_slot_count})}),adminSellerStatus:(id,status)=>request(`/v1/admin/market/sellers/${id}`,{method:'PUT',body:JSON.stringify({status})}),adminResolveTrade:(id,action)=>request(`/v1/admin/market/trades/${id}/resolve`,{method:'POST',body:JSON.stringify({action})}),adminResolveWithdrawal:(id,p)=>request(`/v1/admin/market/withdrawals/${id}/resolve-v2`,{method:'POST',body:JSON.stringify(p)}),adminTradeEvidence:id=>request(`/v1/admin/market/trades/${id}/evidence`),adminLogs:()=>request('/v1/admin/logs'),adminBanners:()=>request('/v1/admin/market/banners'),adminAddBanner:p=>request('/v1/admin/market/banners',{method:'POST',body:JSON.stringify(p)}),adminUpdateBanner:(id,p)=>request(`/v1/admin/market/banners/${id}`,{method:'PUT',body:JSON.stringify(p)}),adminDeleteBanner:id=>request(`/v1/admin/market/banners/${id}`,{method:'DELETE'}),
};
