'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api,downloadAuthed} from '../../lib/api';
import {uploadCheckerFile} from '../../lib/checker-api';

const nf=n=>Number(n||0).toLocaleString('ko-KR');
const statusLabel=s=>({DRAFT:'신청 대기',QUEUED:'대기중',RUNNING:'검수중',COMPLETED:'완료',FAILED:'오류'}[s]||s);
const periodLabel=d=>Number(d||0)===0?'전체':`최근 ${d}일`;
export default function CheckerPage(){
 const [session,setSession]=useState(null),[ready,setReady]=useState(false),[cfg,setCfg]=useState(null),[jobs,setJobs]=useState([]),[file,setFile]=useState(null),[quote,setQuote]=useState(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState(null),[results,setResults]=useState([]),[activityDays,setActivityDays]=useState(1);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 async function load(){try{const [c,j]=await Promise.all([api.checkerConfig(),api.checkerJobs()]);setCfg(c);setJobs(j.items||[])}catch(e){console.error(e)}}
 useEffect(()=>{if(session)load()},[session]);
 useEffect(()=>{if(!session)return;const i=setInterval(load,5000);return()=>clearInterval(i)},[session]);
 async function analyze(){if(!file)return alert('CSV 또는 XLSX 파일을 선택하세요.');setBusy(true);try{const r=await uploadCheckerFile(file,activityDays);setQuote(r);if(r.job)await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function start(id){if(!cfg?.api_ready)return alert('검수 API가 아직 연결되지 않았습니다. 관리자에게 문의해주세요. 포인트는 차감되지 않았습니다.');if(!confirm('검수를 시작하면 신청 확정 건수 기준으로 포인트가 차감됩니다. 진행할까요?'))return;setBusy(true);try{await api.checkerStart(id);setQuote(null);setFile(null);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function openResults(j){setSelected(j);try{const r=await api.checkerResults(j.id,500);setResults(r.items||[])}catch(e){alert(e.message)}}
 async function dl(j,f='all'){try{await downloadAuthed(`/v1/checker/jobs/${j.id}/download?filter=${f}`,`가입자검수_${j.id}_${f}.xlsx`)}catch(e){alert(e.message)}}
 if(!ready)return <main className="content"><section className="card">로그인 확인 중...</section></main>;
 if(!session)return <main className="content"><section className="card"><h2>가입자 검수</h2><p>로그인 후 이용할 수 있습니다.</p><a className="btn primary" href="/">로그인</a></section></main>;
 const q=quote?.quote;
 return <main className="content" style={{maxWidth:1450,margin:'0 auto'}}>
  <div className="head"><div><h1>텔레그램 가입자 검수</h1><p>보유한 전화번호 파일을 업로드해 검수를 신청합니다. 결과와 관계없이 신청 확정 건수 기준으로 과금됩니다.</p></div><button className="btn" onClick={load}>새로고침</button></div>
  {!cfg?.api_ready&&<section className="card" style={{border:'1px solid #8a6530',marginBottom:14}}><b>검수 API 연결 대기중</b><p style={{marginBottom:0}}>업로드·수량분석·견적 확인은 가능하지만 외부 검수 API가 연결되기 전에는 검수 시작 및 포인트 차감이 되지 않습니다.</p></section>}
  <section className="card"><h2>검수 신청</h2><div className="note">CSV / XLSX 지원 · 최소 1,000건 · 최대 1,000,000건 · 중복/잘못된 번호는 신청 확정 전에 제외됩니다.</div>
   <div style={{marginTop:16}}><b style={{fontSize:13}}>접속 기간 설정</b><p style={{fontSize:11,color:'#8196ad',margin:'5px 0 9px'}}>가입 확인 결과에서 최근 접속기간을 기준으로 분류합니다.</p><div className="actions" style={{marginTop:0}}>{[{d:1,l:'1일'},{d:3,l:'3일'},{d:7,l:'7일'},{d:0,l:'전체'}].map(x=><button key={x.d} type="button" className={`btn ${activityDays===x.d?'primary':''}`} onClick={()=>{setActivityDays(x.d);setQuote(null)}}>{x.l}</button>)}</div></div>
   <div className="form" style={{marginTop:12}}><label className="field"><span>전화번호 파일</span><input className="input" type="file" accept=".csv,.xlsx,.xlsm,.txt" onChange={e=>{setFile(e.target.files?.[0]||null);setQuote(null)}}/></label></div><div className="actions"><button className="btn primary" disabled={busy||!file} onClick={analyze}>{busy?'분석 중...':'파일 분석 · 견적 확인'}</button></div>
   <div className="table" style={{marginTop:14}}><table><thead><tr><th>신청건수</th><th>건당 단가</th><th>예상금액</th></tr></thead><tbody><tr><td>1,000 ~ 7,999</td><td>1P</td><td>건수 × 1P</td></tr><tr><td>8,000 ~ 49,999</td><td>0.8P</td><td>건수 × 0.8P</td></tr><tr><td>50,000 ~ 99,999</td><td>0.7P</td><td>건수 × 0.7P</td></tr><tr><td>100,000 이상</td><td>0.6P</td><td>건수 × 0.6P</td></tr></tbody></table></div>
  </section>
  {q&&<section className="card" style={{marginTop:14}}><h2>파일 분석 완료</h2><div className="two"><div><div className="stat"><span>파일에서 읽은 번호</span><b>{nf(q.uploaded_count)}건</b></div><div className="stat"><span>검수 신청 가능 번호</span><b>{nf(q.requested_count)}건</b></div><div className="stat"><span>중복 제외</span><b>{nf(q.duplicate_count)}건</b></div><div className="stat"><span>형식 오류 제외</span><b>{nf(q.invalid_count)}건</b></div></div><div><div className="stat"><span>선택 기간</span><b>{q.activity_period||periodLabel(activityDays)}</b></div><div className="stat"><span>적용 단가</span><b>{q.eligible?`${q.unit_price}P / 건`:'-'}</b></div><div className="stat"><span>계산금액</span><b>{q.eligible?`${nf(q.estimated_cost)}P`:'-'}</b></div><div className="stat"><span>실제 차감</span><b>{q.eligible?`${nf(q.charged_points)}P`:'-'}</b></div></div></div>
   {!q.eligible?<div className="note" style={{marginTop:12,border:'1px solid #8a6530'}}>현재 유효번호가 <b>{nf(q.requested_count)}건</b>입니다. 최소 신청수량은 1,000건이므로 <b>{nf(q.missing_count)}건</b>을 더 추가해야 검수를 신청할 수 있습니다. 포인트는 차감되지 않았습니다.</div>:<><div className="note" style={{marginTop:10}}>소수점 금액은 N POINT가 정수 단위이므로 최종 합계에서 1P 단위로 올림 처리됩니다. 가입/미가입 결과 수에 따라 금액이 변하지 않습니다.</div><div className="actions"><button className="btn primary" disabled={busy||!cfg?.api_ready||!quote?.job} onClick={()=>start(quote.job.id)}>검수 시작 · {nf(q.charged_points)}P 결제</button></div></>}
  </section>}
  <section className="card" style={{marginTop:14}}><h2>검수 작업 내역</h2><div className="table"><table><thead><tr><th>ID</th><th>파일</th><th>기간</th><th>신청건수</th><th>단가</th><th>차감</th><th>진행</th><th>가입확인</th><th>상태</th><th>관리</th></tr></thead><tbody>{jobs.length?jobs.map(j=><tr key={j.id}><td>#{j.id}</td><td>{j.original_filename||'-'}</td><td>{periodLabel(j.activity_days)}</td><td>{nf(j.requested_count)}</td><td>{j.unit_price}P</td><td>{nf(j.charged_points)}P</td><td>{nf(j.completed_count)} / {nf(j.requested_count)}</td><td>{nf(j.registered_count)}</td><td>{statusLabel(j.status)}</td><td className="nowrap"><button className="btn" onClick={()=>openResults(j)}>상세</button>{j.status==='DRAFT'&&<button className="btn primary" disabled={!cfg?.api_ready} onClick={()=>start(j.id)}>시작</button>}{j.status==='COMPLETED'&&<button className="btn" onClick={()=>dl(j,'all')}>전체 Excel</button>}</td></tr>):<tr><td colSpan="10" className="empty">검수 작업이 없습니다.</td></tr>}</tbody></table></div></section>
  {selected&&<div className="modalBack"><div className="modal" style={{maxWidth:1000,width:'94%'}}><div className="head"><div><h2>검수 #{selected.id}</h2><p>{selected.original_filename} · {periodLabel(selected.activity_days)} · {statusLabel(selected.status)}</p></div><button className="x" onClick={()=>setSelected(null)}>×</button></div>{selected.status==='COMPLETED'&&<div className="actions"><button className="btn" onClick={()=>dl(selected,'all')}>전체 결과</button><button className="btn primary" onClick={()=>dl(selected,'registered')}>가입 확인 · {periodLabel(selected.activity_days)}</button><button className="btn" onClick={()=>dl(selected,'unknown')}>미가입/확인불가</button><button className="btn" onClick={()=>dl(selected,'error')}>오류</button></div>}<div className="table" style={{maxHeight:480,overflow:'auto',marginTop:10}}><table><thead><tr><th>전화번호</th><th>가입여부</th><th>기간분류</th><th>텔레그램 UID</th><th>텔레그램 ID</th><th>접속일자</th></tr></thead><tbody>{results.length?results.map(x=><tr key={x.id}><td>{x.phone}</td><td>{x.status==='REGISTERED'?'가입 확인':x.status}</td><td>{x.status==='REGISTERED'?(x.within_period?periodLabel(selected.activity_days):'선택 기간 외'):'-'}</td><td>{x.telegram_id||'-'}</td><td>{x.telegram_username||'-'}</td><td>{x.telegram_active||'-'}</td></tr>):<tr><td colSpan="6" className="empty">표시할 결과가 없습니다.</td></tr>}</tbody></table></div></div></div>}
 </main>
}
