'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {BASE} from '../../../lib/api';
const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';
const dt=v=>v?String(v).replace('T',' ').slice(0,16):'-';
export default function AdminReferralSettings(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[qualification,setQualification]=useState('10000'),[cap,setCap]=useState('100000'),[busy,setBusy]=useState(false),[codes,setCodes]=useState([]),[query,setQuery]=useState(''),[codeBusy,setCodeBusy]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{const s=data.session||null;setSession(s);setReady(true);if(s?.user?.app_metadata?.role==='admin')load(s)})},[]);
 async function call(path,opts={},s=session){const token=s?.access_token||(await supabase.auth.getSession()).data.session?.access_token;const r=await fetch(BASE+path,{...opts,headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok){let d={};try{d=await r.json()}catch{};throw new Error(d.detail||`HTTP ${r.status}`)}return r.json()}
 async function load(s=session){try{const [r,c]=await Promise.all([call('/v1/admin/referral-settings',{},s),call('/v1/admin/referral-codes',{},s)]);setQualification(String(r.referral_qualification_charge??10000));setCap(String(r.referral_monthly_reward_cap??100000));setCodes(c.items||[])}catch(e){alert(e.message)}}
 async function save(){setBusy(true);try{await call('/v1/admin/referral-settings',{method:'PUT',body:JSON.stringify({referral_qualification_charge:Number(qualification),referral_monthly_reward_cap:Number(cap)})});alert('추천인 보호 기준을 저장했습니다.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function toggleCode(c){const next=!c.is_active;if(!confirm(`${c.code} 추천코드를 ${next?'활성화':'중지'}할까요?`))return;setCodeBusy(c.code);try{await call(`/v1/admin/referral-codes/${encodeURIComponent(c.code)}`,{method:'PUT',body:JSON.stringify({is_active:next})});await load()}catch(e){alert(e.message)}finally{setCodeBusy('')}}
 const shown=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return codes;return codes.filter(c=>String(c.code||'').toLowerCase().includes(q)||String(c.member_name||'').toLowerCase().includes(q)||String(c.member_email||'').toLowerCase().includes(q))},[codes,query]);
 if(!ready)return <main className="content"><section className="card">권한 확인 중...</section></main>;
 if(session?.user?.app_metadata?.role!=='admin')return <main className="content"><section className="card">관리자 권한이 없습니다.</section></main>;
 return <main className="content" style={{maxWidth:1200,margin:'0 auto'}}>
  <div className="head"><div><h1>추천인 설정 · 추천코드 관리</h1><p>추천 기준과 회원별 추천코드 상태를 한 화면에서 관리합니다.</p></div><div className="actions compact"><button className="btn" onClick={()=>load()}>새로고침</button></div></div>
  <section className="card"><div className="form"><label className="field"><span>유효추천 인정 최소 첫 승인 입금</span><input className="input" type="number" min="0" value={qualification} onChange={e=>setQualification(e.target.value)}/></label><label className="field"><span>추천회원 1명당 월 보상 상한</span><input className="input" type="number" min="0" value={cap} onChange={e=>setCap(e.target.value)}/></label></div><div className="note" style={{marginTop:12}}>추천보상은 <b>승인 입금 금액의 2%</b>만 지급하며 출금에는 추천보상이 없습니다. 첫 승인 입금 {fmt(qualification)} 이상이면 추천왕 유효회원으로 인정되고, 해당 추천회원으로부터 발생하는 추천보상은 월 {fmt(cap)}까지 지급됩니다.</div><div className="actions"><button className="btn primary" disabled={busy} onClick={save}>{busy?'저장 중...':'설정 저장'}</button></div></section>
  <section className="card" style={{marginTop:14}}><div className="head"><div><h2>추천코드 관리</h2><p>코드 소유회원, 추천현황, 누적 추천보상과 사용 가능 여부를 확인합니다.</p></div></div><div style={{marginTop:12,maxWidth:420}}><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="추천코드 · 회원명 · 이메일 검색"/></div><div className="table" style={{marginTop:14}}><table><thead><tr><th>추천코드</th><th>회원</th><th>추천인원</th><th>유효추천</th><th>총 적립</th><th>생성일</th><th>상태</th><th>관리</th></tr></thead><tbody>{shown.length?shown.map(c=><tr key={c.code}><td><b>{c.code}</b></td><td><b>{c.member_name||'회원'}</b><small style={{display:'block',color:'#7890a8',marginTop:4}}>{c.member_email||'-'}</small></td><td>{Number(c.referral_count||0).toLocaleString()}명</td><td>{Number(c.qualified_count||0).toLocaleString()}명</td><td>{fmt(c.total_reward)}</td><td>{dt(c.created_at)}</td><td>{c.is_active?<span style={{color:'#58d39b'}}>활성</span>:<span style={{color:'#ff8c8c'}}>중지</span>}</td><td><button className={c.is_active?'btn danger':'btn primary'} disabled={codeBusy===c.code} onClick={()=>toggleCode(c)}>{codeBusy===c.code?'처리 중...':c.is_active?'코드 중지':'다시 활성화'}</button></td></tr>):<tr><td colSpan="8" className="empty">추천코드가 없습니다.</td></tr>}</tbody></table></div></section>
 </main>;
}
