'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {BASE} from '../../lib/api';

const categories=['주식/증권','해외선물','코인/가상자산','경제/뉴스','마케팅/비즈니스','구인구직','자유 커뮤니티','기타'];
const date=v=>v?String(v).replace('T',' ').slice(0,16):'-';

async function call(path,opts={}){
 const {data:{session}}=await supabase.auth.getSession();
 if(!session?.access_token)throw new Error('로그인이 필요합니다.');
 const r=await fetch(BASE+path,{...opts,headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,...(opts.headers||{})}});
 let b={};try{b=await r.json()}catch{}
 if(!r.ok)throw new Error(b.detail||`HTTP ${r.status}`);
 return b;
}

const emptyForm={community_name:'',category:'기타',description:'',telegram_url:'',image_url:'',tags:''};

export default function TelegramCommunityPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[items,setItems]=useState([]),[mine,setMine]=useState([]),[form,setForm]=useState(emptyForm),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[busy,setBusy]=useState(false),[showManage,setShowManage]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 async function load(){if(!session)return;try{const [a,b]=await Promise.all([call('/v1/telegram-communities'),call('/v1/telegram-communities/mine')]);setItems(a.items||[]);setMine(b.items||[])}catch(e){alert(e.message)}}
 useEffect(()=>{if(session)load()},[session]);
 const filtered=useMemo(()=>items.filter(x=>{const q=search.trim().toLowerCase();const text=[x.community_name,x.description,...(x.tags||[])].join(' ').toLowerCase();return (!category||x.category===category)&&(!q||text.includes(q))}),[items,search,category]);
 function payload(src){return {community_name:src.community_name.trim(),category:src.category||'기타',description:src.description||'',telegram_url:src.telegram_url.trim(),image_url:(src.image_url||'').trim()||null,tags:String(src.tags||'').split(',').map(x=>x.trim()).filter(Boolean)}}
 async function create(){if(!form.community_name.trim())return alert('커뮤니티명을 입력하세요.');if(!form.telegram_url.trim())return alert('Telegram 링크를 입력하세요.');setBusy(true);try{await call('/v1/telegram-communities',{method:'POST',body:JSON.stringify(payload(form))});setForm(emptyForm);await load();alert('커뮤니티 홍보글을 등록했습니다.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 function beginEdit(x){setEditing({...x,tags:(x.tags||[]).join(', ')})}
 async function saveEdit(){if(!editing)return;setBusy(true);try{await call(`/v1/telegram-communities/${editing.id}`,{method:'PUT',body:JSON.stringify(payload(editing))});setEditing(null);await load();alert('수정했습니다.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function setStatus(x,status){try{await call(`/v1/telegram-communities/${x.id}`,{method:'PUT',body:JSON.stringify({status})});await load()}catch(e){alert(e.message)}}
 async function remove(x){if(!confirm(`“${x.community_name}” 홍보글을 삭제할까요?`))return;try{await call(`/v1/telegram-communities/${x.id}`,{method:'DELETE'});await load()}catch(e){alert(e.message)}}
 if(!ready)return <main className="content"><section className="card">불러오는 중...</section></main>;
 if(!session)return <main className="content"><section className="card">로그인이 필요합니다.</section></main>;
 return <main className="content" style={{maxWidth:1460,margin:'0 auto'}}>
  <div className="head"><div><h1>텔레그램 커뮤니티</h1><p>Telegram 채널·그룹·커뮤니티를 소개하고 이용자에게 홍보할 수 있는 공간입니다.</p></div><div className="actions compact"><button className="btn" onClick={()=>setShowManage(v=>!v)}>{showManage?'목록 보기':'내 홍보글 관리'}</button><button className="btn primary" onClick={()=>document.getElementById('community-register')?.scrollIntoView({behavior:'smooth'})}>커뮤니티 등록</button></div></div>

  {!showManage&&<>
   <section className="card" style={{marginBottom:14}}><div className="form"><label className="field"><span>검색</span><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="커뮤니티명, 소개, 태그 검색"/></label><label className="field"><span>카테고리</span><select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option value="">전체</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div></section>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(280px,1fr))',gap:14,marginBottom:18}}>{filtered.length?filtered.map(x=><article key={x.id} className="card" style={{padding:0,overflow:'hidden'}}>{x.image_url?<div style={{height:160,background:`url(${x.image_url}) center/cover no-repeat`}}/>:<div style={{height:120,display:'grid',placeItems:'center',background:'linear-gradient(135deg,#102441,#173c69)',fontSize:38}}>✈️</div>}<div style={{padding:16}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><b style={{fontSize:16}}>{x.community_name}</b><span className="badge ok">{x.category}</span></div><p style={{fontSize:11,color:'#9fb4ca',lineHeight:1.65,minHeight:54,whiteSpace:'pre-wrap'}}>{x.description||'소개가 없습니다.'}</p>{x.tags?.length>0&&<div style={{display:'flex',gap:5,flexWrap:'wrap',margin:'9px 0'}}>{x.tags.map(t=><span key={t} style={{fontSize:9,color:'#78b6ff'}}>#{t}</span>)}</div>}<a className="btn primary" href={x.telegram_url} target="_blank" rel="noreferrer" style={{display:'block',textAlign:'center',textDecoration:'none',marginTop:12}}>Telegram 입장</a><small style={{display:'block',marginTop:10,color:'#647b94',fontSize:9}}>등록 {date(x.created_at)}</small></div></article>):<section className="card" style={{gridColumn:'1/-1',textAlign:'center',color:'#73849b'}}>등록된 커뮤니티가 없습니다.</section>}</div>
  </>}

  {showManage&&<section className="card" style={{marginBottom:18}}><div className="head"><div><h2>내 홍보글 관리</h2><p>직접 등록한 커뮤니티를 수정·숨김·재노출·삭제할 수 있습니다.</p></div></div><div className="table"><table><thead><tr><th>커뮤니티</th><th>카테고리</th><th>상태</th><th>등록일</th><th>관리</th></tr></thead><tbody>{mine.length?mine.map(x=><tr key={x.id}><td><b>{x.community_name}</b></td><td>{x.category}</td><td>{x.status}</td><td>{date(x.created_at)}</td><td className="nowrap"><button className="btn primary" onClick={()=>beginEdit(x)}>수정</button> {x.status==='ACTIVE'?<button className="btn" onClick={()=>setStatus(x,'HIDDEN')}>숨기기</button>:<button className="btn" onClick={()=>setStatus(x,'ACTIVE')}>재노출</button>} <button className="btn danger" onClick={()=>remove(x)}>삭제</button></td></tr>):<tr><td colSpan="5" className="empty">등록한 커뮤니티가 없습니다.</td></tr>}</tbody></table></div></section>}

  <section id="community-register" className="card"><div className="head"><div><h2>커뮤니티 등록</h2><p>상품 등록하듯 기본 정보를 입력하면 즉시 홍보 목록에 노출됩니다.</p></div></div><div className="form"><label className="field"><span>커뮤니티명</span><input className="input" value={form.community_name} onChange={e=>setForm({...form,community_name:e.target.value})} placeholder="예: N PAY 투자 커뮤니티"/></label><label className="field"><span>카테고리</span><select className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="field full"><span>Telegram 링크</span><input className="input" value={form.telegram_url} onChange={e=>setForm({...form,telegram_url:e.target.value})} placeholder="https://t.me/your_channel"/></label><label className="field full"><span>대표 이미지 URL (선택)</span><input className="input" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="https://.../image.jpg"/></label><label className="field full"><span>태그 · 쉼표로 구분</span><input className="input" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="주식, 정보공유, 커뮤니티"/></label><label className="field full"><span>커뮤니티 소개</span><textarea className="input" rows="7" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="어떤 커뮤니티인지 간단하고 명확하게 소개해주세요."/></label></div><div className="actions"><button className="btn primary" disabled={busy} onClick={create}>{busy?'등록 중...':'커뮤니티 등록'}</button></div><div className="note">Telegram 채널·그룹 홍보용 공간입니다. 허위 정보, 불법 거래, 사칭, 개인정보 노출 등 운영정책에 위반되는 글은 숨김 또는 삭제될 수 있습니다.</div></section>

  {editing&&<div className="modalBack" onClick={()=>setEditing(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="head"><div><h2>커뮤니티 수정</h2><p>홍보글 #{editing.id}</p></div><button className="x" onClick={()=>setEditing(null)}>×</button></div><div className="form"><label className="field"><span>커뮤니티명</span><input className="input" value={editing.community_name} onChange={e=>setEditing({...editing,community_name:e.target.value})}/></label><label className="field"><span>카테고리</span><select className="input" value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="field full"><span>Telegram 링크</span><input className="input" value={editing.telegram_url} onChange={e=>setEditing({...editing,telegram_url:e.target.value})}/></label><label className="field full"><span>대표 이미지 URL</span><input className="input" value={editing.image_url||''} onChange={e=>setEditing({...editing,image_url:e.target.value})}/></label><label className="field full"><span>태그</span><input className="input" value={editing.tags||''} onChange={e=>setEditing({...editing,tags:e.target.value})}/></label><label className="field full"><span>소개</span><textarea className="input" rows="7" value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label></div><div className="actions"><button className="btn" onClick={()=>setEditing(null)}>취소</button><button className="btn primary" disabled={busy} onClick={saveEdit}>수정 저장</button></div></div></div>}
 </main>;
}
