'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {BASE} from '../../lib/api';

const date=v=>v?String(v).replace('T',' ').slice(0,16):'-';
const medal=r=>r===1?'🥇':r===2?'🥈':r===3?'🥉':r<=10?`🏅${r}`:`${r}`;
async function call(path,opts={}){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('로그인이 필요합니다.');const r=await fetch(BASE+path,{...opts,headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,...(opts.headers||{})}});let b={};try{b=await r.json()}catch{};if(!r.ok)throw new Error(b.detail||`HTTP ${r.status}`);return b}
const emptyForm={community_name:'',category:'',description:'',telegram_url:'',image_url:'',tags:''};

export default function TelegramCommunityPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[items,setItems]=useState([]),[mine,setMine]=useState([]),[categories,setCategories]=useState([]),[form,setForm]=useState(emptyForm),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[busy,setBusy]=useState(false),[showManage,setShowManage]=useState(false),[showRegister,setShowRegister]=useState(false),[detail,setDetail]=useState(null),[comments,setComments]=useState([]),[comment,setComment]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 async function load(){if(!session)return;try{const [a,b,c]=await Promise.all([call('/v1/telegram-communities'),call('/v1/telegram-communities/mine'),call('/v1/telegram-community-categories')]);setItems(a.items||[]);setMine(b.items||[]);const cats=c.items||[];setCategories(cats);setForm(v=>({...v,category:v.category||cats[0]?.name||''}))}catch(e){alert(e.message)}}
 useEffect(()=>{if(session)load()},[session]);
 const filtered=useMemo(()=>items.filter(x=>{const q=search.trim().toLowerCase();const text=[x.community_name,x.description,...(x.tags||[])].join(' ').toLowerCase();return(!category||x.category===category)&&(!q||text.includes(q))}),[items,search,category]);
 function payload(src){return{community_name:src.community_name.trim(),category:src.category||categories[0]?.name||'기타',description:src.description||'',telegram_url:src.telegram_url.trim(),image_url:(src.image_url||'').trim()||null,tags:String(src.tags||'').split(',').map(x=>x.trim()).filter(Boolean)}}
 async function create(){if(!form.community_name.trim())return alert('커뮤니티명을 입력하세요.');if(!form.telegram_url.trim())return alert('Telegram 링크를 입력하세요.');if(!form.category)return alert('카테고리를 선택하세요.');setBusy(true);try{await call('/v1/telegram-communities',{method:'POST',body:JSON.stringify(payload(form))});setForm({...emptyForm,category:categories[0]?.name||''});setShowRegister(false);await load();alert('커뮤니티를 등록했습니다.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 function beginEdit(x){setEditing({...x,tags:(x.tags||[]).join(', ')})}
 async function saveEdit(){if(!editing)return;setBusy(true);try{await call(`/v1/telegram-communities/${editing.id}`,{method:'PUT',body:JSON.stringify(payload(editing))});setEditing(null);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function setStatus(x,status){try{await call(`/v1/telegram-communities/${x.id}`,{method:'PUT',body:JSON.stringify({status})});await load()}catch(e){alert(e.message)}}
 async function remove(x){if(!confirm(`“${x.community_name}” 홍보글을 삭제할까요?`))return;try{await call(`/v1/telegram-communities/${x.id}`,{method:'DELETE'});await load()}catch(e){alert(e.message)}}
 async function openDetail(x){setDetail(x);setComment('');try{await call(`/v1/telegram-communities/${x.id}/view`,{method:'POST'});const c=await call(`/v1/telegram-communities/${x.id}/comments`);setComments(c.items||[]);await load()}catch(e){alert(e.message)}}
 async function toggleLike(x){try{await call(`/v1/telegram-communities/${x.id}/like`,{method:'POST'});await load();if(detail?.id===x.id)setDetail(d=>({...d,liked_by_me:!d.liked_by_me,like_count:Number(d.like_count||0)+(d.liked_by_me?-1:1)}))}catch(e){alert(e.message)}}
 async function addComment(){if(!detail||!comment.trim())return;setBusy(true);try{await call(`/v1/telegram-communities/${detail.id}/comments`,{method:'POST',body:JSON.stringify({body:comment})});setComment('');const c=await call(`/v1/telegram-communities/${detail.id}/comments`);setComments(c.items||[]);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 if(!ready)return <main className="content"><section className="card">불러오는 중...</section></main>;
 if(!session)return <main className="content"><section className="card">로그인이 필요합니다.</section></main>;
 const panel={border:'1px solid #284869',borderRadius:12,background:'#0d1d31',overflow:'hidden'};
 const rowStyle={display:'grid',gridTemplateColumns:'72px minmax(180px,1fr) 110px 78px 78px 78px 48px',alignItems:'center',minHeight:48,borderTop:'1px solid #203952',padding:'0 14px',gap:10};
 const categoryOptions=categories.map(c=><option key={c.id||c.name} value={c.name}>{c.name}</option>);
 return <main className="content" style={{maxWidth:1180,margin:'0 auto'}}>
  <div className="head"><div><h1>텔레그램 커뮤니티</h1><p>많이 보고, 좋아하고, 대화하는 커뮤니티가 위로 올라옵니다.</p></div><div className="actions compact"><button className="btn" onClick={()=>setShowManage(v=>!v)}>{showManage?'커뮤니티 랭킹':'내 홍보글 관리'}</button><button className="btn primary" onClick={()=>setShowRegister(true)}>커뮤니티 등록</button></div></div>
  {!showManage&&<><section style={{...panel,marginBottom:14}}><div style={{padding:'14px 16px',display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,borderBottom:'1px solid #29496b'}}><div style={{display:'flex',alignItems:'center',gap:9}}><span style={{fontSize:20}}>⚓</span><b style={{fontSize:16}}>커뮤니티 랭킹</b></div><span style={{fontSize:9,color:'#708ba8'}}>조회 · 좋아요 · 댓글 · 최근 활동 반영</span></div><div style={{padding:12,display:'grid',gridTemplateColumns:'1fr 220px',gap:10}}><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="커뮤니티명, 소개, 태그 검색"/><select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option value="">전체 카테고리</option>{categoryOptions}</select></div></section>
   <section style={panel}><div style={{...rowStyle,minHeight:36,borderTop:0,color:'#6f89a5',fontSize:9,fontWeight:800}}><span>순위</span><span>커뮤니티</span><span>카테고리</span><span>조회</span><span>좋아요</span><span>댓글</span><span></span></div>{filtered.length?filtered.map((x,i)=><div key={x.id} style={{...rowStyle,background:i<3?'rgba(44,105,170,.08)':'transparent'}}><button onClick={()=>openDetail(x)} style={{border:0,background:'transparent',color:i===0?'#ffd86b':i===1?'#dbe7f3':i===2?'#e9a76f':'#ff9f42',fontWeight:950,fontSize:13,textAlign:'left',cursor:'pointer',padding:0}}>{medal(Number(x.rank||i+1))}</button><button onClick={()=>openDetail(x)} style={{border:0,background:'transparent',color:'#edf6ff',fontWeight:900,fontSize:12,textAlign:'left',cursor:'pointer',padding:0,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{x.community_name}</button><span style={{fontSize:9,color:'#84a3c2',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{x.category}</span><span style={{fontSize:9,color:'#8aa5bf'}}>👁 {Number(x.view_count||0).toLocaleString()}</span><button onClick={()=>toggleLike(x)} style={{border:0,background:'transparent',color:x.liked_by_me?'#ff7f96':'#8aa5bf',fontSize:9,cursor:'pointer',padding:0,textAlign:'left'}}>♥ {Number(x.like_count||0).toLocaleString()}</button><button onClick={()=>openDetail(x)} style={{border:0,background:'transparent',color:'#8aa5bf',fontSize:9,cursor:'pointer',padding:0,textAlign:'left'}}>💬 {Number(x.comment_count||0).toLocaleString()}</button><a href={x.telegram_url} target="_blank" rel="noreferrer" title="Telegram 열기" style={{color:'#86c8ff',textDecoration:'none',fontSize:15,textAlign:'right'}}>↗</a></div>):<div style={{padding:34,textAlign:'center',color:'#7189a3'}}>등록된 커뮤니티가 없습니다.</div>}</section><div style={{fontSize:9,color:'#5f7893',padding:'10px 2px'}}>순위는 조회수만으로 결정되지 않으며 좋아요 · 댓글 · 최근 활동을 함께 반영합니다.</div></>}
  {showManage&&<section className="card" style={{marginBottom:18}}><div className="head"><div><h2>내 홍보글 관리</h2><p>직접 등록한 커뮤니티를 수정·숨김·재노출·삭제할 수 있습니다.</p></div></div><div className="table"><table><thead><tr><th>커뮤니티</th><th>조회</th><th>좋아요</th><th>댓글</th><th>상태</th><th>관리</th></tr></thead><tbody>{mine.length?mine.map(x=><tr key={x.id}><td><b>{x.community_name}</b></td><td>{x.view_count||0}</td><td>{x.like_count||0}</td><td>{x.comment_count||0}</td><td>{x.status}</td><td className="nowrap"><button className="btn primary" onClick={()=>beginEdit(x)}>수정</button> {x.status==='ACTIVE'?<button className="btn" onClick={()=>setStatus(x,'HIDDEN')}>숨기기</button>:<button className="btn" onClick={()=>setStatus(x,'ACTIVE')}>재노출</button>} <button className="btn danger" onClick={()=>remove(x)}>삭제</button></td></tr>):<tr><td colSpan="6" className="empty">등록한 커뮤니티가 없습니다.</td></tr>}</tbody></table></div></section>}
  {showRegister&&<div className="modalBack" onClick={()=>setShowRegister(false)}><div className="modal wide" onClick={e=>e.stopPropagation()}><div className="head"><div><h2>커뮤니티 등록</h2><p>기본 정보와 Telegram 링크를 입력하면 랭킹에 참여합니다.</p></div><button className="x" onClick={()=>setShowRegister(false)}>×</button></div><div className="form"><label className="field"><span>커뮤니티명</span><input className="input" value={form.community_name} onChange={e=>setForm({...form,community_name:e.target.value})} placeholder="예: 엔페이 커뮤니티"/></label><label className="field"><span>카테고리</span><select className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="" disabled>카테고리 선택</option>{categoryOptions}</select></label><label className="field full"><span>Telegram 링크</span><input className="input" value={form.telegram_url} onChange={e=>setForm({...form,telegram_url:e.target.value})} placeholder="https://t.me/your_channel"/></label><label className="field full"><span>대표 이미지 URL · 선택</span><input className="input" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="https://.../image.jpg"/></label><label className="field full"><span>태그 · 쉼표로 구분</span><input className="input" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="주식, 정보공유, 경제"/></label><label className="field full"><span>소개</span><textarea className="input" rows="6" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="커뮤니티를 간단하게 소개해주세요."/></label></div><div className="actions"><button className="btn" onClick={()=>setShowRegister(false)}>취소</button><button className="btn primary" disabled={busy||!categories.length} onClick={create}>{busy?'등록 중...':'등록하기'}</button></div></div></div>}
  {detail&&<div className="modalBack" onClick={()=>setDetail(null)}><div className="modal wide" onClick={e=>e.stopPropagation()}><div className="head"><div><h2>{medal(Number(detail.rank||0))} {detail.community_name}</h2><p>👁 {detail.view_count||0} · ♥ {detail.like_count||0} · 💬 {detail.comment_count||0}</p></div><button className="x" onClick={()=>setDetail(null)}>×</button></div>{detail.image_url&&<div style={{height:220,borderRadius:12,background:`url(${detail.image_url}) center/cover no-repeat`,marginBottom:14}}/>}<p style={{whiteSpace:'pre-wrap',lineHeight:1.7,color:'#b9cadc'}}>{detail.description||'소개가 없습니다.'}</p><div className="actions"><button className={'btn '+(detail.liked_by_me?'primary':'')} onClick={()=>toggleLike(detail)}>{detail.liked_by_me?'♥ 좋아요 취소':'♡ 좋아요'}</button><a className="btn primary" href={detail.telegram_url} target="_blank" rel="noreferrer" style={{textDecoration:'none'}}>Telegram 입장</a></div><hr style={{border:0,borderTop:'1px solid #243246',margin:'18px 0'}}/><h3 style={{fontSize:14}}>댓글 {comments.length}</h3><div style={{display:'grid',gap:8,maxHeight:300,overflow:'auto'}}>{comments.length?comments.map(c=><div key={c.id} style={{padding:10,border:'1px solid #25364d',borderRadius:9}}><b style={{fontSize:10}}>{c.username||'user'}</b><p style={{fontSize:11,margin:'5px 0',whiteSpace:'pre-wrap'}}>{c.body}</p><small style={{color:'#667f99',fontSize:8}}>{date(c.created_at)}</small></div>):<div className="empty">첫 댓글을 남겨보세요.</div>}</div><div className="actions"><input className="input" value={comment} onChange={e=>setComment(e.target.value)} placeholder="댓글 입력" onKeyDown={e=>e.key==='Enter'&&addComment()}/><button className="btn primary" disabled={busy} onClick={addComment}>댓글 등록</button></div></div></div>}
  {editing&&<div className="modalBack" onClick={()=>setEditing(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="head"><h2>커뮤니티 수정</h2><button className="x" onClick={()=>setEditing(null)}>×</button></div><div className="form"><label className="field"><span>커뮤니티명</span><input className="input" value={editing.community_name} onChange={e=>setEditing({...editing,community_name:e.target.value})}/></label><label className="field"><span>카테고리</span><select className="input" value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{!categories.some(c=>c.name===editing.category)&&<option value={editing.category}>{editing.category}</option>}{categoryOptions}</select></label><label className="field full"><span>Telegram 링크</span><input className="input" value={editing.telegram_url} onChange={e=>setEditing({...editing,telegram_url:e.target.value})}/></label><label className="field full"><span>대표 이미지 URL</span><input className="input" value={editing.image_url||''} onChange={e=>setEditing({...editing,image_url:e.target.value})}/></label><label className="field full"><span>태그</span><input className="input" value={editing.tags||''} onChange={e=>setEditing({...editing,tags:e.target.value})}/></label><label className="field full"><span>소개</span><textarea className="input" rows="6" value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label></div><div className="actions"><button className="btn" onClick={()=>setEditing(null)}>취소</button><button className="btn primary" disabled={busy} onClick={saveEdit}>수정 저장</button></div></div></div>}
 </main>;
}
