'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {BASE} from '../../lib/api';

const categories=['주식/증권','해외선물','코인/가상자산','경제/뉴스','마케팅/비즈니스','구인구직','자유 커뮤니티','기타'];
const date=v=>v?String(v).replace('T',' ').slice(0,16):'-';
async function call(path,opts={}){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('로그인이 필요합니다.');const r=await fetch(BASE+path,{...opts,headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,...(opts.headers||{})}});let b={};try{b=await r.json()}catch{};if(!r.ok)throw new Error(b.detail||`HTTP ${r.status}`);return b}
const emptyForm={community_name:'',category:'기타',description:'',telegram_url:'',image_url:'',tags:''};

export default function TelegramCommunityPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[items,setItems]=useState([]),[mine,setMine]=useState([]),[form,setForm]=useState(emptyForm),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[busy,setBusy]=useState(false),[showManage,setShowManage]=useState(false),[detail,setDetail]=useState(null),[comments,setComments]=useState([]),[comment,setComment]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)})},[]);
 async function load(){if(!session)return;try{const [a,b]=await Promise.all([call('/v1/telegram-communities'),call('/v1/telegram-communities/mine')]);setItems(a.items||[]);setMine(b.items||[])}catch(e){alert(e.message)}}
 useEffect(()=>{if(session)load()},[session]);
 const filtered=useMemo(()=>items.filter(x=>{const q=search.trim().toLowerCase();const text=[x.community_name,x.description,...(x.tags||[])].join(' ').toLowerCase();return(!category||x.category===category)&&(!q||text.includes(q))}),[items,search,category]);
 function payload(src){return{community_name:src.community_name.trim(),category:src.category||'기타',description:src.description||'',telegram_url:src.telegram_url.trim(),image_url:(src.image_url||'').trim()||null,tags:String(src.tags||'').split(',').map(x=>x.trim()).filter(Boolean)}}
 async function create(){if(!form.community_name.trim())return alert('커뮤니티명을 입력하세요.');if(!form.telegram_url.trim())return alert('Telegram 링크를 입력하세요.');setBusy(true);try{await call('/v1/telegram-communities',{method:'POST',body:JSON.stringify(payload(form))});setForm(emptyForm);await load();alert('커뮤니티를 등록했습니다.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 function beginEdit(x){setEditing({...x,tags:(x.tags||[]).join(', ')})}
 async function saveEdit(){if(!editing)return;setBusy(true);try{await call(`/v1/telegram-communities/${editing.id}`,{method:'PUT',body:JSON.stringify(payload(editing))});setEditing(null);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function setStatus(x,status){try{await call(`/v1/telegram-communities/${x.id}`,{method:'PUT',body:JSON.stringify({status})});await load()}catch(e){alert(e.message)}}
 async function remove(x){if(!confirm(`“${x.community_name}” 홍보글을 삭제할까요?`))return;try{await call(`/v1/telegram-communities/${x.id}`,{method:'DELETE'});await load()}catch(e){alert(e.message)}}
 async function openDetail(x){setDetail(x);setComment('');try{await call(`/v1/telegram-communities/${x.id}/view`,{method:'POST'});const c=await call(`/v1/telegram-communities/${x.id}/comments`);setComments(c.items||[]);await load()}catch(e){alert(e.message)}}
 async function toggleLike(x){try{await call(`/v1/telegram-communities/${x.id}/like`,{method:'POST'});await load();if(detail?.id===x.id)setDetail(d=>({...d,liked_by_me:!d.liked_by_me,like_count:Number(d.like_count||0)+(d.liked_by_me?-1:1)}))}catch(e){alert(e.message)}}
 async function addComment(){if(!detail||!comment.trim())return;setBusy(true);try{await call(`/v1/telegram-communities/${detail.id}/comments`,{method:'POST',body:JSON.stringify({body:comment})});setComment('');const c=await call(`/v1/telegram-communities/${detail.id}/comments`);setComments(c.items||[]);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 if(!ready)return <main className="content"><section className="card">불러오는 중...</section></main>;
 if(!session)return <main className="content"><section className="card">로그인이 필요합니다.</section></main>;
 return <main className="content" style={{maxWidth:1460,margin:'0 auto'}}>
  <div className="head"><div><h1>텔레그램 커뮤니티</h1><p>조회수 · 좋아요 · 댓글 · 최근 활동을 반영해 순위가 실시간으로 변하는 링크공유 플랫폼입니다.</p></div><div className="actions compact"><button className="btn" onClick={()=>setShowManage(v=>!v)}>{showManage?'랭킹 보기':'내 홍보글 관리'}</button><button className="btn primary" onClick={()=>document.getElementById('community-register')?.scrollIntoView({behavior:'smooth'})}>커뮤니티 등록</button></div></div>
  {!showManage&&<><section className="card" style={{marginBottom:14}}><div className="form"><label className="field"><span>검색</span><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="커뮤니티명, 소개, 태그 검색"/></label><label className="field"><span>카테고리</span><select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option value="">전체</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="note">순위는 좋아요 6점 · 댓글 4점 · 조회수 보정 · 최근 활동 보정을 함께 반영합니다. 단순 조회수만으로 상단을 독점하지 않습니다.</div></section>
  <div style={{display:'grid',gap:10,marginBottom:18}}>{filtered.length?filtered.map(x=><article key={x.id} className="card" style={{padding:14,display:'grid',gridTemplateColumns:'54px 90px 1fr auto',gap:14,alignItems:'center'}}><div style={{textAlign:'center'}}><b style={{fontSize:24,color:x.rank<=3?'#7dc7ff':'#9fb4ca'}}>#{x.rank}</b><small style={{display:'block',fontSize:8,color:'#647b94'}}>RANK</small></div>{x.image_url?<div style={{width:90,height:72,borderRadius:10,background:`url(${x.image_url}) center/cover no-repeat`}}/>:<div style={{width:90,height:72,borderRadius:10,display:'grid',placeItems:'center',background:'#132b4b',fontSize:28}}>✈️</div>}<div style={{minWidth:0}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><b style={{fontSize:15}}>{x.community_name}</b><span className="badge ok">{x.category}</span></div><p style={{margin:'6px 0',fontSize:10,color:'#9fb4ca',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{x.description||'소개가 없습니다.'}</p><div style={{display:'flex',gap:12,fontSize:9,color:'#7992ad'}}><span>👁 {Number(x.view_count||0).toLocaleString()}</span><span>♥ {Number(x.like_count||0).toLocaleString()}</span><span>💬 {Number(x.comment_count||0).toLocaleString()}</span><span>점수 {x.rank_score}</span></div></div><div className="actions compact" style={{justifyContent:'flex-end'}}><button className={'btn '+(x.liked_by_me?'primary':'')} onClick={()=>toggleLike(x)}>{x.liked_by_me?'♥ 좋아요':'♡ 좋아요'}</button><button className="btn" onClick={()=>openDetail(x)}>상세 · 댓글</button><a className="btn primary" href={x.telegram_url} target="_blank" rel="noreferrer" style={{textDecoration:'none'}}>Telegram 입장</a></div></article>):<section className="card" style={{textAlign:'center',color:'#73849b'}}>등록된 커뮤니티가 없습니다.</section>}</div></>}
  {showManage&&<section className="card" style={{marginBottom:18}}><div className="head"><div><h2>내 홍보글 관리</h2><p>직접 등록한 커뮤니티를 수정·숨김·재노출·삭제할 수 있습니다.</p></div></div><div className="table"><table><thead><tr><th>커뮤니티</th><th>조회</th><th>좋아요</th><th>댓글</th><th>상태</th><th>관리</th></tr></thead><tbody>{mine.length?mine.map(x=><tr key={x.id}><td><b>{x.community_name}</b></td><td>{x.view_count||0}</td><td>{x.like_count||0}</td><td>{x.comment_count||0}</td><td>{x.status}</td><td className="nowrap"><button className="btn primary" onClick={()=>beginEdit(x)}>수정</button> {x.status==='ACTIVE'?<button className="btn" onClick={()=>setStatus(x,'HIDDEN')}>숨기기</button>:<button className="btn" onClick={()=>setStatus(x,'ACTIVE')}>재노출</button>} <button className="btn danger" onClick={()=>remove(x)}>삭제</button></td></tr>):<tr><td colSpan="6" className="empty">등록한 커뮤니티가 없습니다.</td></tr>}</tbody></table></div></section>}
  <section id="community-register" className="card"><div className="head"><div><h2>커뮤니티 등록</h2><p>상품 등록처럼 기본 정보와 Telegram 링크를 입력하면 랭킹에 참여합니다.</p></div></div><div className="form"><label className="field"><span>커뮤니티명</span><input className="input" value={form.community_name} onChange={e=>setForm({...form,community_name:e.target.value})}/></label><label className="field"><span>카테고리</span><select className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="field full"><span>Telegram 링크</span><input className="input" value={form.telegram_url} onChange={e=>setForm({...form,telegram_url:e.target.value})} placeholder="https://t.me/your_channel"/></label><label className="field full"><span>대표 이미지 URL</span><input className="input" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></label><label className="field full"><span>태그 · 쉼표로 구분</span><input className="input" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></label><label className="field full"><span>소개</span><textarea className="input" rows="6" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div className="actions"><button className="btn primary" disabled={busy} onClick={create}>{busy?'등록 중...':'커뮤니티 등록'}</button></div></section>
  {detail&&<div className="modalBack" onClick={()=>setDetail(null)}><div className="modal wide" onClick={e=>e.stopPropagation()}><div className="head"><div><h2>#{detail.rank} {detail.community_name}</h2><p>👁 {detail.view_count||0} · ♥ {detail.like_count||0} · 💬 {detail.comment_count||0}</p></div><button className="x" onClick={()=>setDetail(null)}>×</button></div><p style={{whiteSpace:'pre-wrap',lineHeight:1.7,color:'#b9cadc'}}>{detail.description}</p><div className="actions"><button className={'btn '+(detail.liked_by_me?'primary':'')} onClick={()=>toggleLike(detail)}>{detail.liked_by_me?'♥ 좋아요 취소':'♡ 좋아요'}</button><a className="btn primary" href={detail.telegram_url} target="_blank" rel="noreferrer" style={{textDecoration:'none'}}>Telegram 입장</a></div><hr style={{border:0,borderTop:'1px solid #243246',margin:'18px 0'}}/><h3 style={{fontSize:14}}>댓글 {comments.length}</h3><div style={{display:'grid',gap:8,maxHeight:300,overflow:'auto'}}>{comments.length?comments.map(c=><div key={c.id} style={{padding:10,border:'1px solid #25364d',borderRadius:9}}><b style={{fontSize:10}}>{c.username||'user'}</b><p style={{fontSize:11,margin:'5px 0',whiteSpace:'pre-wrap'}}>{c.body}</p><small style={{color:'#667f99',fontSize:8}}>{date(c.created_at)}</small></div>):<div className="empty">첫 댓글을 남겨보세요.</div>}</div><div className="actions"><input className="input" value={comment} onChange={e=>setComment(e.target.value)} placeholder="댓글 입력" onKeyDown={e=>e.key==='Enter'&&addComment()}/><button className="btn primary" disabled={busy} onClick={addComment}>댓글 등록</button></div></div></div>}
  {editing&&<div className="modalBack" onClick={()=>setEditing(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="head"><h2>커뮤니티 수정</h2><button className="x" onClick={()=>setEditing(null)}>×</button></div><div className="form"><label className="field"><span>커뮤니티명</span><input className="input" value={editing.community_name} onChange={e=>setEditing({...editing,community_name:e.target.value})}/></label><label className="field"><span>카테고리</span><select className="input" value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="field full"><span>Telegram 링크</span><input className="input" value={editing.telegram_url} onChange={e=>setEditing({...editing,telegram_url:e.target.value})}/></label><label className="field full"><span>대표 이미지 URL</span><input className="input" value={editing.image_url||''} onChange={e=>setEditing({...editing,image_url:e.target.value})}/></label><label className="field full"><span>태그</span><input className="input" value={editing.tags||''} onChange={e=>setEditing({...editing,tags:e.target.value})}/></label><label className="field full"><span>소개</span><textarea className="input" rows="6" value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label></div><div className="actions"><button className="btn" onClick={()=>setEditing(null)}>취소</button><button className="btn primary" disabled={busy} onClick={saveEdit}>수정 저장</button></div></div></div>}
 </main>;
}
