'use client';
import {useState} from 'react';
import {supabase} from '../../lib/supabase';
import {BASE} from '../../lib/api';

export default function SignupPage(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[referral,setReferral]=useState(''),[busy,setBusy]=useState(false),[valid,setValid]=useState(null);
 async function validate(){const code=referral.trim().toUpperCase();if(!code){setValid(false);return false}const res=await fetch(`${BASE}/v1/public/referral/validate?code=${encodeURIComponent(code)}`,{cache:'no-store'});if(!res.ok){setValid(false);throw new Error(`추천코드 확인 오류 HTTP ${res.status}`)}const data=await res.json();setValid(!!data.valid);return !!data.valid}
 async function signup(){if(!email||!password)return alert('이메일과 비밀번호를 입력하세요.');if(!referral.trim())return alert('추천코드를 입력해야 가입할 수 있습니다.');setBusy(true);try{const ok=await validate();if(!ok)return alert('사용할 수 없는 추천코드입니다.');const code=referral.trim().toUpperCase();const {error}=await supabase.auth.signUp({email,password,options:{data:{referral_code:code}}});if(error)throw error;alert('회원가입이 완료되었습니다. 로그인해주세요.');location.href='/'}catch(e){const m=e?.message||String(e);if(m.includes('REFERRAL_CODE_REQUIRED'))alert('추천코드가 필요합니다.');else if(m.includes('INVALID_REFERRAL_CODE')||m.includes('Database error saving new user'))alert('추천코드를 다시 확인해주세요.');else alert(m)}finally{setBusy(false)}}
 return <div className="authPage"><div className="authCard"><h1>ANGEL PAY</h1><p>N PAY 회원가입 · 추천코드가 반드시 필요합니다.</p><label className="field"><span>이메일</span><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>비밀번호</span><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field"><span>추천코드</span><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><input className="input" value={referral} onChange={e=>{setReferral(e.target.value.toUpperCase());setValid(null)}} placeholder="예: ANGEL7"/><button className="btn" type="button" onClick={()=>validate().then(ok=>alert(ok?'사용 가능한 추천코드입니다.':'사용할 수 없는 추천코드입니다.')).catch(e=>alert(e.message))}>코드 확인</button></div></label>{valid===true&&<div className="note" style={{borderColor:'#2f8f7a',color:'#86dfc3'}}>✓ 사용 가능한 추천코드입니다.</div>}{valid===false&&<div className="note" style={{borderColor:'#9f4555',color:'#ffabb7'}}>사용할 수 없는 추천코드입니다.</div>}<button className="btn primary authSubmit" disabled={busy} onClick={signup}>{busy?'가입 처리 중...':'추천코드로 회원가입'}</button><div className="note">추천코드가 없는 회원가입 요청은 서버에서 차단됩니다.</div><a href="/" className="link" style={{display:'block',textAlign:'center',marginTop:14}}>로그인으로 돌아가기</a></div></div>;
}
