'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {api} from '../../../lib/api';
const dt=x=>x?String(x).replace('T',' ').slice(0,19):'-';
export default function AdminCommunications(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[supportUrl,setSupportUrl]=useState(''),[members,setMembers]=useState([]),[targetType,setTargetType]=useState('ALL'),[targetUser,setTargetUser]=useState(''),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[linkUrl,setLinkUrl]=useState(''),[history,setHistory]=useState([]),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{const s=data.session||null;setSession(s);setReady(true);if(s?.user?.app_metadata?.role==='admin')load()})},[]);
 async function load(){try{const [st,m,b]=await Promise.all([api.adminSiteSettings(),api.adminMembers(''),api.adminBroadcasts()]);setSupportUrl(st.support_url||'');setMembers(m.items||[]);setHistory(b.items||[])}catch(e){alert(e.message)}}
 async function saveSupport(){setBusy(true);try{await api.adminUpdateSiteSettings({support_url:supportUrl.trim()});alert('고객센터 링크를 저장했습니다.');await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function send(){if(!title.trim()||!message.trim())return alert('제목과 내용을 입력하세요.');if(targetType==='USER'&&!targetUser)return alert('대상 회원을 선택하세요.');if(!confirm(targetType==='ALL'?'전체 회원에게 알림을 발송할까요?':'선택한 회원에게 알림을 발송할까요?'))return;setBusy(true);try{const r=await api.adminSendBroadcast({target_type:targetType,target_user_id:targetType==='USER'?targetUser:null,title:title.trim(),message:message.trim(),link_url:linkUrl.trim()||null});alert(`${Number(r.delivered_count||0).toLocaleString()}명에게 발송했습니다.`);setTitle('');setMessage('');setLinkUrl('');await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 if(!ready)return <main className="content"><section className="card">권한 확인 중...</section></main>;
 if(session?.user?.app_metadata?.role!=='admin')return <main className="content"><section className="card">관리자 권한이 없습니다.</section></main>;
 return <main className="content" style={{maxWidth:1200,margin:'0 auto'}}><div className="head"><div><h1>고객센터 · 공지/알림</h1><p>텔레그램 고객센터 연결주소와 회원 알림 발송을 관리합니다.</p></div><button className="btn" onClick={load}>새로고침</button></div>
 <section className="card"><h2>고객센터 연결</h2><div className="note">회원 화면의 사용방법 오른쪽 고객센터 버튼에 연결됩니다. t.me 또는 Telegram 링크만 등록할 수 있습니다.</div><div style={{display:'flex',gap:8,marginTop:12}}><input className="input" style={{flex:1}} value={supportUrl} onChange={e=>setSupportUrl(e.target.value)} placeholder="https://t.me/your_support"/><button className="btn primary" disabled={busy} onClick={saveSupport}>링크 저장</button></div></section>
 <section className="card" style={{marginTop:14}}><h2>공지 · 알림 발송</h2><div className="form"><label className="field"><span>발송 대상</span><select className="input" value={targetType} onChange={e=>setTargetType(e.target.value)}><option value="ALL">전체 회원</option><option value="USER">특정 회원</option></select></label>{targetType==='USER'&&<label className="field"><span>회원 선택</span><select className="input" value={targetUser} onChange={e=>setTargetUser(e.target.value)}><option value="">회원 선택</option>{members.map(m=><option key={m.id} value={m.id}>{m.email||m.id}</option>)}</select></label>}<label className="field"><span>제목</span><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="공지 제목"/></label><label className="field"><span>내용</span><textarea className="input" style={{minHeight:120}} value={message} onChange={e=>setMessage(e.target.value)} placeholder="회원 알림센터에 표시될 내용"/></label><label className="field"><span>이동 링크 (선택)</span><input className="input" value={linkUrl} onChange={e=>setLinkUrl(e.target.value)} placeholder="예: /wallet 또는 /market"/></label></div><div className="actions"><button className="btn primary" disabled={busy} onClick={send}>{busy?'처리 중...':'알림 발송'}</button></div></section>
 <section className="card" style={{marginTop:14}}><h2>최근 발송내역</h2><div className="table"><table><thead><tr><th>일시</th><th>대상</th><th>제목</th><th>발송수</th></tr></thead><tbody>{history.length?history.map(x=><tr key={x.id}><td>{dt(x.created_at)}</td><td>{x.target_type==='ALL'?'전체 회원':'특정 회원'}</td><td>{x.title}</td><td>{Number(x.delivered_count||0).toLocaleString()}명</td></tr>):<tr><td colSpan="4" className="empty">발송내역이 없습니다.</td></tr>}</tbody></table></div></section></main>;
}
