'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api,BASE} from '../../lib/api';

export default function PostBotTestPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[accounts,setAccounts]=useState([]),[accountId,setAccountId]=useState(''),[postCode,setPostCode]=useState(''),[target,setTarget]=useState('me'),[busy,setBusy]=useState(false),[result,setResult]=useState(null);
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{const s=data.session||null;setSession(s);setReady(true);if(s){try{const r=await api.accounts();const list=(r.items||r.accounts||[]).filter(x=>['READY','CONNECTED'].includes(String(x.status||'').toUpperCase()));setAccounts(list);if(list[0])setAccountId(String(list[0].id))}catch(e){alert(e.message)}}})},[]);
 async function send(){if(!accountId)return alert('테스트에 사용할 Telegram 계정을 선택하세요.');if(!postCode.trim())return alert('PostBot 게시물 코드를 입력하세요.');if(!target.trim())return alert('테스트 받을 대상을 입력하세요.');setBusy(true);setResult(null);try{const {data:{session:s}}=await supabase.auth.getSession();const r=await fetch(BASE+'/v1/telegram/postbot-test',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({account_id:Number(accountId),post_code:postCode.trim(),target:target.trim()})});let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||`HTTP ${r.status}`);setResult(body);alert('테스트 메시지를 전송했습니다. Telegram에서 이미지와 버튼을 확인하세요.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 if(!ready)return <main className="content"><section className="card">불러오는 중...</section></main>;
 if(!session)return <main className="content"><section className="card">로그인이 필요합니다.</section></main>;
 return <main className="content" style={{maxWidth:900,margin:'0 auto'}}><div className="head"><div><h1>@PostBot 테스트</h1><p>기존 발송 작업과 분리된 1건 전용 테스트입니다.</p></div><a className="btn" href="/">텔발로 돌아가기</a></div><section className="card"><div className="form"><label className="field"><span>담당 Telegram 계정</span><select className="input" value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">선택</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.label||a.phone||a.username||`계정 #${a.id}`}</option>)}</select></label><label className="field"><span>PostBot 게시물 코드</span><input className="input" value={postCode} onChange={e=>setPostCode(e.target.value)} placeholder="예: 40599y1mszb005s"/></label><label className="field full"><span>테스트 받을 대상</span><input className="input" value={target} onChange={e=>setTarget(e.target.value)} placeholder="me / @username / Telegram UID"/><small>먼저 본인 Saved Messages에서 확인하려면 me 를 그대로 사용하세요.</small></label></div><div className="actions"><button className="btn primary" disabled={busy} onClick={send}>{busy?'전송 중...':'1건 테스트 전송'}</button></div>{result&&<div style={{marginTop:16,padding:14,border:'1px solid #315575',borderRadius:10}}><b>전송 성공</b><div style={{marginTop:8,fontSize:12}}>message_id: {result.message_id||'-'} · inline 결과 {result.result_count||0}개</div></div>}</section></main>;
}
