'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api,BASE} from '../../lib/api';

export default function PostBotTestPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[accounts,setAccounts]=useState([]),[accountId,setAccountId]=useState(''),[postCode,setPostCode]=useState(''),[phone1,setPhone1]=useState(''),[phone2,setPhone2]=useState(''),[phone3,setPhone3]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null);
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{const s=data.session||null;setSession(s);setReady(true);if(s){try{const r=await api.accounts();const list=(r.items||r.accounts||[]).filter(x=>['READY','CONNECTED'].includes(String(x.status||'').toUpperCase()));setAccounts(list);if(list[0])setAccountId(String(list[0].id))}catch(e){alert(e.message)}}})},[]);
 async function send(){if(!accountId)return alert('테스트에 사용할 Telegram 계정을 선택하세요.');if(!postCode.trim())return alert('PostBot 게시물 코드를 입력하세요.');const phones=[phone1.trim(),phone2.trim(),phone3.trim()];if(phones.some(x=>!x))return alert('테스트 전화번호 3개를 모두 입력하세요.');const norm=x=>x.replace(/\D/g,'').replace(/^82/,'0');if(new Set(phones.map(norm)).size!==3)return alert('테스트 전화번호 3개는 서로 달라야 합니다.');setBusy(true);setResult(null);try{const {data:{session:s}}=await supabase.auth.getSession();const r=await fetch(BASE+'/v1/telegram/postbot-test',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({account_id:Number(accountId),post_code:postCode.trim(),phones})});let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||`HTTP ${r.status}`);setResult(body);alert(`3건 전화번호 테스트 완료: 연락처확인 ${body.resolved_count||0} / 전송성공 ${body.success_count||0} / 실패 ${body.failed_count||0}`)}catch(e){alert(e.message)}finally{setBusy(false)}}
 if(!ready)return <main className="content"><section className="card">불러오는 중...</section></main>;
 if(!session)return <main className="content"><section className="card">로그인이 필요합니다.</section></main>;
 return <main className="content" style={{maxWidth:900,margin:'0 auto'}}><div className="head"><div><h1>@PostBot 전화번호 3건 테스트</h1><p>실제 텔발과 같은 방식으로 전화번호 3개를 담당계정 연락처에 추가해 Telegram UID를 확인한 뒤 같은 PostBot 게시물을 전송합니다.</p></div><a className="btn" href="/">텔발로 돌아가기</a></div><section className="card"><div className="form"><label className="field"><span>담당 Telegram 계정</span><select className="input" value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">선택</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.label||a.phone||a.username||`계정 #${a.id}`}</option>)}</select></label><label className="field"><span>PostBot 게시물 코드</span><input className="input" value={postCode} onChange={e=>setPostCode(e.target.value)} placeholder="예: 40599y1mszb005s"/></label><label className="field"><span>테스트 전화번호 1</span><input className="input" value={phone1} onChange={e=>setPhone1(e.target.value)} placeholder="010-0000-0000"/></label><label className="field"><span>테스트 전화번호 2</span><input className="input" value={phone2} onChange={e=>setPhone2(e.target.value)} placeholder="010-0000-0000"/></label><label className="field"><span>테스트 전화번호 3</span><input className="input" value={phone3} onChange={e=>setPhone3(e.target.value)} placeholder="010-0000-0000"/></label></div><div className="note" style={{marginTop:10}}>입력 번호는 API 호출 직전에 +82 국제형식으로 변환됩니다. 기존 DB/JOB에는 추가하지 않고 이 테스트에서만 연락처 확인 후 전송합니다.</div><div className="actions"><button className="btn primary" disabled={busy} onClick={send}>{busy?'연락처 확인 · 전송 중...':'전화번호 3건 테스트 전송'}</button></div>{result&&<div style={{marginTop:16,padding:14,border:'1px solid #315575',borderRadius:10}}><b>테스트 결과 · 연락처확인 {result.resolved_count||0} / 전송성공 {result.success_count||0} / 실패 {result.failed_count||0}</b><div style={{marginTop:10,display:'grid',gap:8}}>{(result.items||[]).map((x,i)=><div key={i} style={{padding:10,border:'1px solid #244662',borderRadius:8}}><b>{x.phone}</b><div style={{fontSize:12,marginTop:4}}>UID: {x.telegram_user_id||'-'} · {x.contact_resolved?'연락처 확인':'미확인'} · {x.ok?`전송 성공 · message_id ${x.message_id||'-'}`:`전송 실패 · ${x.error||'알 수 없는 오류'}`}</div></div>)}</div></div>}</section></main>;
}
