'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {api,BASE} from '../../lib/api';

export default function PostBotTestPage(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[accounts,setAccounts]=useState([]),[accountId,setAccountId]=useState(''),[postCode,setPostCode]=useState(''),[target1,setTarget1]=useState('me'),[target2,setTarget2]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null);
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{const s=data.session||null;setSession(s);setReady(true);if(s){try{const r=await api.accounts();const list=(r.items||r.accounts||[]).filter(x=>['READY','CONNECTED'].includes(String(x.status||'').toUpperCase()));setAccounts(list);if(list[0])setAccountId(String(list[0].id))}catch(e){alert(e.message)}}})},[]);
 async function send(){if(!accountId)return alert('테스트에 사용할 Telegram 계정을 선택하세요.');if(!postCode.trim())return alert('PostBot 게시물 코드를 입력하세요.');if(!target1.trim()||!target2.trim())return alert('서로 다른 테스트 대상 2개를 입력하세요.');if(target1.trim().toLowerCase()===target2.trim().toLowerCase())return alert('테스트 대상 2개는 서로 달라야 합니다.');setBusy(true);setResult(null);try{const {data:{session:s}}=await supabase.auth.getSession();const r=await fetch(BASE+'/v1/telegram/postbot-test',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({account_id:Number(accountId),post_code:postCode.trim(),targets:[target1.trim(),target2.trim()]})});let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||`HTTP ${r.status}`);setResult(body);alert(`2건 동시 테스트 완료: 성공 ${body.success_count||0} / 실패 ${body.failed_count||0}`)}catch(e){alert(e.message)}finally{setBusy(false)}}
 if(!ready)return <main className="content"><section className="card">불러오는 중...</section></main>;
 if(!session)return <main className="content"><section className="card">로그인이 필요합니다.</section></main>;
 return <main className="content" style={{maxWidth:900,margin:'0 auto'}}><div className="head"><div><h1>@PostBot 2건 동시 테스트</h1><p>기존 발송 작업과 분리해 같은 담당계정이 서로 다른 대상 2곳에 같은 PostBot 게시물을 동시에 전송합니다.</p></div><a className="btn" href="/">텔발로 돌아가기</a></div><section className="card"><div className="form"><label className="field"><span>담당 Telegram 계정</span><select className="input" value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">선택</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.label||a.phone||a.username||`계정 #${a.id}`}</option>)}</select></label><label className="field"><span>PostBot 게시물 코드</span><input className="input" value={postCode} onChange={e=>setPostCode(e.target.value)} placeholder="예: 40599y1mszb005s"/></label><label className="field"><span>테스트 대상 1</span><input className="input" value={target1} onChange={e=>setTarget1(e.target.value)} placeholder="me / @username / Telegram UID"/></label><label className="field"><span>테스트 대상 2</span><input className="input" value={target2} onChange={e=>setTarget2(e.target.value)} placeholder="@username / Telegram UID"/></label></div><div className="actions"><button className="btn primary" disabled={busy} onClick={send}>{busy?'2건 전송 중...':'2건 동시 테스트 전송'}</button></div>{result&&<div style={{marginTop:16,padding:14,border:'1px solid #315575',borderRadius:10}}><b>테스트 결과 · 성공 {result.success_count||0} / 실패 {result.failed_count||0}</b><div style={{marginTop:10,display:'grid',gap:8}}>{(result.items||[]).map((x,i)=><div key={i} style={{padding:10,border:'1px solid #244662',borderRadius:8}}><b>{x.target}</b><div style={{fontSize:12,marginTop:4}}>{x.ok?`성공 · message_id ${x.message_id||'-'}`:`실패 · ${x.error||'알 수 없는 오류'}`}</div></div>)}</div></div>}</section></main>;
}
