'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {BASE} from '../../lib/api';

async function authToken(){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('로그인이 필요합니다.');return session.access_token}
async function jsonReq(path,options={}){const token=await authToken();const r=await fetch(BASE+path,{...options,headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`,...(options.headers||{})}});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.detail||`HTTP ${r.status}`);return b}

export default function InlinePostsPage(){
 const [bot,setBot]=useState(null),[pairing,setPairing]=useState(''),[posts,setPosts]=useState([]),[token,setToken]=useState('');
 const [code,setCode]=useState(''),[caption,setCaption]=useState(''),[buttonText,setButtonText]=useState(''),[buttonUrl,setButtonUrl]=useState(''),[image,setImage]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [b,p]=await Promise.all([jsonReq('/v1/inline-bot'),jsonReq('/v1/inline-posts')]);setBot(b.bot||null);setPairing(b.pairing_url||'');setPosts(p.items||[])}catch(e){setMsg(e.message)}};
 useEffect(()=>{load()},[]);
 async function register(){if(!token.trim())return alert('BotFather에서 발급받은 Bot Token을 입력하세요.');setBusy(true);try{const r=await jsonReq('/v1/inline-bot',{method:'POST',body:JSON.stringify({bot_token:token.trim()})});setBot(r.bot);setPairing(r.pairing_url||'');setToken('');setMsg(r.posts_require_image_refresh?'봇 교체 완료. 기존 게시물 코드는 유지되며 이미지만 새 봇 기준으로 다시 등록해야 합니다.':'개인 Inline Bot 등록 완료. 아래 연결 버튼을 눌러 Telegram에서 시작하세요.');await load()}catch(e){alert(e.message);setMsg(e.message)}finally{setBusy(false)}}
 async function createPost(){if(!image)return alert('이미지를 선택하세요.');if(!code.trim())return alert('게시물 코드를 입력하세요.');setBusy(true);try{const fd=new FormData();fd.append('code',code.trim().toUpperCase());fd.append('caption',caption);fd.append('button_text',buttonText);fd.append('button_url',buttonUrl);fd.append('image',image);const tk=await authToken();const r=await fetch(BASE+'/v1/inline-posts',{method:'POST',headers:{Authorization:`Bearer ${tk}`},body:fd});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.detail||`HTTP ${r.status}`);setCode('');setCaption('');setButtonText('');setButtonUrl('');setImage(null);setMsg(`게시물 코드 ${b.code} 등록 완료`);await load()}catch(e){alert(e.message);setMsg(e.message)}finally{setBusy(false)}}
 async function remove(id){if(!confirm('이 게시물을 삭제할까요?'))return;try{await jsonReq(`/v1/inline-posts/${id}`,{method:'DELETE'});await load()}catch(e){alert(e.message)}}
 return <div className="shell"><aside className="sidebar"><div className="brand">ANGEL PAY</div><div className="sub">N PAY · 엔페이</div><div className="nav"><button onClick={()=>location.href='/'}>메시지 발송</button><button onClick={()=>location.href='/image-send'}>이미지 발송</button><button className="active">게시물 관리</button></div></aside><main className="content"><header className="top"><div><h1>Inline 게시물 관리</h1><p>회원 본인의 개인 Inline Bot과 이미지·본문·URL 버튼 게시물 코드를 관리합니다.</p></div></header>
 <section className="card"><div className="head"><div><h2>내 Inline Bot</h2><p>BotFather에서 /setinline을 켠 뒤 Bot Token을 등록하세요.</p></div></div><div className="form"><label className="field"><span>Bot Token</span><input className="input" type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="123456789:AA..."/></label></div><div className="actions"><button className="btn primary" disabled={busy} onClick={register}>개인 봇 등록 / 교체</button>{bot&&<span style={{fontSize:12,color:'#9fb4ca'}}>@{bot.bot_username} · {bot.owner_chat_connected?'연결 완료':'연결 필요'}</span>}{pairing&&<button className="btn" onClick={()=>window.open(pairing,'_blank')}>Telegram에서 봇 연결</button>}</div></section>
 <section className="card"><div className="head"><div><h2>게시물 코드 등록</h2><p>코드는 직접 지정합니다. 예: STOCK001 / AUG28 / VIP_NOTICE</p></div></div><div className="form"><label className="field"><span>게시물 코드</span><input className="input" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="STOCK001"/></label><label className="field"><span>이미지</span><input className="input" type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0]||null)}/></label><label className="field"><span>버튼명</span><input className="input" value={buttonText} onChange={e=>setButtonText(e.target.value)} placeholder="자세히 보기"/></label><label className="field"><span>버튼 URL</span><input className="input" value={buttonUrl} onChange={e=>setButtonUrl(e.target.value)} placeholder="https://..."/></label></div><label className="field"><span>본문</span><textarea className="input" rows={5} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="이미지와 함께 표시할 본문"/></label><div className="actions"><button className="btn primary" disabled={busy||!bot?.owner_chat_connected} onClick={createPost}>게시물 코드 등록</button></div>{msg&&<div style={{marginTop:10,fontSize:12,color:'#8fc5ff'}}>{msg}</div>}</section>
 <section className="card"><div className="head"><div><h2>내 게시물</h2><p>이미지 발송에서 아래 코드를 그대로 선택하거나 입력합니다.</p></div></div>{posts.length?posts.map(p=><div key={p.id} style={{display:'grid',gridTemplateColumns:'160px 1fr auto',gap:12,alignItems:'center',padding:'10px 0',borderBottom:'1px solid #24364a'}}><b>{p.code}</b><div style={{fontSize:12,color:'#9fb4ca'}}>{p.image_file_id?'사용 가능':'이미지 재등록 필요'} · {p.button_text||'버튼 없음'}<div style={{color:'#71869c',marginTop:3}}>{p.caption||'본문 없음'}</div></div><button className="btn" onClick={()=>remove(p.id)}>삭제</button></div>):<div style={{color:'#71869c',fontSize:12}}>등록된 게시물이 없습니다.</div>}</section>
 </main></div>;
}
