'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import {api,BASE} from '../../../lib/api';
const fmt=n=>Number(n||0).toLocaleString('ko-KR')+' P';
export default function BannerSettingsAdmin(){
 const [ready,setReady]=useState(false),[session,setSession]=useState(null),[count,setCount]=useState(3),[saving,setSaving]=useState(false),[banners,setBanners]=useState([]),[selected,setSelected]=useState(null),[reason,setReason]=useState(''),[refund,setRefund]=useState('0');
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{const s=data.session||null;setSession(s);setReady(true);if(s?.user?.app_metadata?.role==='admin')await load()})},[]);
 async function load(){try{const [r,b]=await Promise.all([api.bannerSlots(),api.adminBanners()]);setCount(Number(r.slot_count||3));setBanners(b.items||[])}catch(e){alert(e.message)}}
 if(!ready)return <main className="content"><section className="card">권한 확인 중...</section></main>;
 if(!session||session.user?.app_metadata?.role!=='admin')return <main className="content"><section className="card"><h1>관리자 권한이 필요합니다.</h1></section></main>;
 async function save(){setSaving(true);try{await api.adminBannerSlotSettings(Number(count));await load();alert(`광고 슬롯을 ${count}개로 변경했습니다.`)}catch(e){const m=e.message||'';alert(m.includes('ACTIVE_PAID_BANNER_EXISTS')?'해당 범위에 아직 이용 중인 유료 광고가 있어 슬롯을 줄일 수 없습니다. 광고 기간 종료 또는 관리자 강제종료 후 다시 시도하세요.':m)}finally{setSaving(false)}}
 async function terminate(){if(!selected||!reason.trim())return alert('강제종료 사유를 입력하세요.');if(!confirm(`광고 ${selected.sort_order}번을 강제종료할까요?\n환불 ${fmt(refund)}`))return;setSaving(true);try{const {data:{session:s}}=await supabase.auth.getSession();const res=await fetch(`${BASE}/v1/admin/market/banners/${selected.id}/terminate`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({reason:reason.trim(),refund_amount:Number(refund||0)})});if(!res.ok){let d={};try{d=await res.json()}catch{};throw new Error(d.detail||`HTTP ${res.status}`)}setSelected(null);setReason('');setRefund('0');await load();alert('유료 광고를 종료했습니다.')}catch(e){alert(e.message)}finally{setSaving(false)}}
 const paid=banners.filter(b=>b.owner_user_id);
 return <main className="content" style={{maxWidth:1100,margin:'0 auto'}}><div className="head"><div><h1>광고 슬롯 설정</h1><p>노출 슬롯 수와 유료 광고 이용권을 관리합니다.</p></div></div><section className="card"><h2>노출 광고 슬롯 수</h2><p className="note">기본 3개. 이미 결제되어 이용 중인 광고가 숨겨지는 방향으로는 슬롯 수를 줄일 수 없습니다.</p><label className="field" style={{marginTop:14}}><span>광고 슬롯 수</span><select className="input" value={count} onChange={e=>setCount(Number(e.target.value))}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}개</option>)}</select></label><div className="actions"><button className="btn primary" disabled={saving} onClick={save}>설정 저장</button></div></section><section className="card" style={{marginTop:14}}><h2>유료 광고 이용 현황</h2><div className="table"><table><thead><tr><th>슬롯</th><th>소유자</th><th>상품</th><th>구매가</th><th>종료</th><th>관리</th></tr></thead><tbody>{paid.length?paid.map(b=><tr key={b.id}><td>{b.sort_order}번</td><td>{String(b.owner_user_id).slice(0,8)}...</td><td>{b.plan_code||'-'}</td><td>{fmt(b.purchase_price)}</td><td>{b.is_lifetime?'없음 (영구)':b.expires_at?.replace('T',' ').slice(0,16)}</td><td><button className="btn danger" onClick={()=>{setSelected(b);setRefund('0');setReason('')}}>강제종료</button></td></tr>):<tr><td colSpan="6" className="empty">이용 중인 유료광고가 없습니다.</td></tr>}</tbody></table></div></section>{selected&&<div className="modalBack"><div className="modal"><div className="head"><div><h2>광고 {selected.sort_order}번 강제종료</h2><p>삭제 사유와 환불금액이 기록되며 사용자에게 알림이 갑니다.</p></div><button className="x" onClick={()=>setSelected(null)}>×</button></div><label className="field"><span>종료 사유</span><textarea className="textarea" value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="field" style={{marginTop:10}}><span>환불 포인트</span><input className="input" type="number" min="0" value={refund} onChange={e=>setRefund(e.target.value)}/></label><div className="actions"><button className="btn" onClick={()=>setSelected(null)}>취소</button><button className="btn danger" disabled={saving} onClick={terminate}>강제종료</button></div></div></div>}</main>;
}
